### ISSUE TITLE
Funny bug in Multi-Genre Model

### ISSUE THREAD

**Issue by aufr33** [Anjok07/ultimatevocalremovergui#1]
Your new model is great! Compared to stock, this is progress. But I found one problematic song - "Gorillaz - Feel Good Inc.". In the instrumental, the bass disappears completely from 37 to 44 sec. [Demo](https://mega.nz/file/qdJxzCbb#VKis0R2VaE0CDV5PjgAiHTXw9mQj-AevOafnP50RS94).

I don't know if you used this song in your dataset, but when I did, I got the same weird result. For this reason, I removed it from my dataset and I advise you not to use this track either.

**Comment by Anjok07** [comment]
Thank you for the tip! I think I think I might have included it. I'll have to go over my dataset again. I had been putting it together over the course of 2 months. I'm actually still in the process of creating more models so I'll keep your tip in mind.

**Comment by aufr33** [comment]
By the way, I started to keep a list of songs in the OpenOffice Calc. With such a large dataset, this is a must.

**Comment by TRvlvr** [comment]
Good thinking.

Please feel free to give any feedback on the models and GUI. It's more than welcome!
