### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by lNoZl** [Anjok07/ultimatevocalremovergui#100]
**To Reproduce**
I used the command:
python VocalRemover.py

**Screenshots**
![image](https://user-images.githubusercontent.com/85001648/129410676-f051cf6d-9fbc-4558-9885-130aa016d6a0.png)
**Desktop (please complete the following information):**
 - OS: Windows 10 Home

**Additional context**
The app does not open

**Comment by KCGD** [comment]
make sure that you installed it with, and are using python 3.7.
If that's not your main version then a conda environment will also work

**Comment by Anjok07** [comment]
Please upgrade to UVR 5.2 and use the installer.
