### ISSUE TITLE
Size mismatch issue for new models (July)

### ISSUE THREAD

**Issue by geraldoramos** [Anjok07/ultimatevocalremovergui#102]
Hi,

This issue is similar to [this](https://github.com/Anjok07/ultimatevocalremovergui/issues/81), but I'm opening a new case since it's related to the newest models and the recommended solution in that thread did not work.

I've tried to use any of the [July](https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/5.0.2) models as following:

```
file_path='bin/example/test.wav'
model_path='models/HP2-4BAND-3090_4band_2.pth'
param_path='modelparams/4band_44100.json'

python3 inference.py -n 129605KB -g 0 -m $param_path -P $model_path -i $file_path
```

I tried with and without the ` -n 129605KB` flag. Also tried all the other models in the new `5.0.2` release.

The error returned is the following (many similar lines of these):

```
size mismatch for aux1_out.weight: copying a param with shape torch.Size([2, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 16, 1, 1]).
        size mismatch for aux2_out.weight: copying a param with shape torch.Size([2, 32, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 16, 1, 1]).
```
        
Other models work fine, such as `MGM-v5-4Band-44100-BETA1`.

Any help is appreciated!

Thanks!

**Comment by aufr33** [comment]
Use the -n 123821KB

**Comment by geraldoramos** [comment]
Thanks, @aufr33, it worked with `-n 537238KB`

**Comment by geraldoramos** [comment]
@aufr33 Actually,  is there a place we can check the values for each model? `-n 537238KB` works for `HP2-4BAND-3090_4band_2` but using others like `Vocal_HP_4BAND_3090` and `HP_4BAND_3090.pth` it returned the mismatch error.

Thanks again.

**Comment by aufr33** [comment]
The architecture name is just the size of the pth file in KiB.
