### ISSUE TITLE
EOFError: Ran out of input [INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by Vilagamer999** [Anjok07/ultimatevocalremovergui#103]
![image](https://user-images.githubusercontent.com/30276916/132240419-dc3d1c86-5d26-4ec0-9cb1-cd68584f001d.png)

**Specifications:**
```
Processor	Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz   3.60 GHz
Installed RAM	32,0 GB
System type	64-bit operating system, x64-based processor
Edition	Windows 10 Pro
Version	        20H2
OS build	19042.1202
```

**Comment by melonjack** [comment]
Check folder structure, png files im "img" folder and last but not least - permissions on all folders and files inside your "uvr-root-folder")
And yeah, pass requirements dependencies and check python version (but for me both 3.9 and 3.7 worked).

**Comment by Vilagamer999** [comment]
Checked file structure, all is as it should be.
Img files are also ok
Moved folder to c:/ still same error
Python version:
![image](https://user-images.githubusercontent.com/30276916/132317517-e59853de-fd14-4e0e-8676-46867b7725cd.png)

**Comment by melonjack** [comment]
Tried to type “python3” instead of python? Did all PATH enviroments are present in system?

**Comment by hubert17** [comment]
Same issue here. I hope somebody can help.

**Comment by hubert17** [comment]
Fixed. I've simply relocate the folder.
