### ISSUE TITLE
[INSTALLATION PROBLEM] can't create wheels for some packages

### ISSUE THREAD

**Issue by Giantfire33** [Anjok07/ultimatevocalremovergui#104]
When executing the first command in the directory, the following problem occurred:

pip install --no-cache-dir -r requirements.txt:
(after all libraries have been downloaded)

```
Building wheels for collected packages: librosa, numba, soundstretch, llvmlite
  Building wheel for librosa (setup.py) ... done
  Created wheel for librosa: filename=librosa-0.7.2-py3-none-any.whl size=1612900 sha256=97a3d894b03501bad95d2ff58cbb588ac49e3b98c2c44bed68f0a74299057b75
  Stored in directory: C:\Users\Michael\AppData\Local\Temp\pip-ephem-wheel-cache-3_8xtgjg\wheels\0a\4d\f4\93b38473e329fdd30bc85efc8f2985a6e8a2f1f52f2cd6e7c4
  Building wheel for numba (setup.py) ... error
```
then after a while it says:
```
ERROR: Failed building wheel for numba
Running setup.py clean for numba
ERROR: Failed cleaning build dir for numba
```

then it successfully creates wheel for soundstretch, but then it fails doing so for llvmlite

```
Running setup.py clean for llvmlite
Successfully built librosa soundstretch
Failed to build numba llvmlite
Installing collected packages: numpy, llvmlite, numba, SoundFile, tqdm, soundstretch, Pillow, opencv-python, librosa
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.37.0
    Uninstalling llvmlite-0.37.0:
      Successfully uninstalled llvmlite-0.37.0
    Running setup.py install for llvmlite ... error
```

`Rolling back uninstall of llvmlite...`

Operating System: Windows10 (10.0.19042 Build 19042)
-used the default command prompt
-full log: [log.txt](https://github.com/Anjok07/ultimatevocalremovergui/files/7122399/log.txt)

**Comment by ITAC85v2** [comment]
You need to install Numpy. Do this by running `python -m pip install numpy`. 

If there's an error installing it, let me know, since commonly you need to also install something else in order to install Numpy.

**Comment by Giantfire33** [comment]
i have numpy already installed
