### ISSUE TITLE
Got this error out of nowhere and can't find a way to fix it

### ISSUE THREAD

**Issue by Frenzi2003** [Anjok07/ultimatevocalremovergui#1053]
Alright, so, I've been using UVR5 with zero issues over the past couple of months, however, out of nowhere, today, I started getting either of those errors whenever I try running it:

![image](https://github.com/Anjok07/ultimatevocalremovergui/assets/100734227/40d2f739-9e60-4222-b42a-ee5c8edfcc6e)
![image](https://github.com/Anjok07/ultimatevocalremovergui/assets/100734227/fb5e2ba8-bf9c-40dd-b5bf-fc418a4895d8)

And no matter what I do, I can't seem to fix those errors.

Any help?

**Comment by ChrisTG742** [comment]
- Check if the file in question (the dll) is still present. If not, try re-installing UVR.
- Check if the CUDA is still present on your system. Maybe the CUDA installation got corrupted by some Windows updates or so. Try re-installing CUDA or the whole graphics driver.
HTH

**Comment by Frenzi2003** [comment]
> * Check if the file in question (the dll) is still present. If not, try re-installing UVR.
> 
>     * Check if the CUDA is still present on your system. Maybe the CUDA installation got corrupted by some Windows updates or so. Try re-installing CUDA or the whole graphics driver.
>       HTH

This worked! Thanks a lot!
