### ISSUE TITLE
AMD freezes

### ISSUE THREAD

**Issue by kiberline** [Anjok07/ultimatevocalremovergui#106]
On AMD process freezes and nothing happenes. 
![image](https://user-images.githubusercontent.com/85339450/132953331-85ac1586-c963-4022-a9ed-d0899f94f38b.png)

**Comment by aufr33** [comment]
I have not noticed any issues with AMD processors. Please specify your CPU / GPU.

**Comment by kiberline** [comment]
If I understand, the program works only on python 3.7?

чт, 16 сент. 2021 г., 16:13 aufr33 ***@***.***>:

**Comment by kiberline** [comment]
> I have not noticed any issues with AMD processors. Please specify your CPU / GPU.

AMD Ryzen 2700x. RAM is also full.  All 32 gigabytes

**Comment by Anjok07** [comment]
Please upgrade to UVR 5.2.0 and use the installer.
