### ISSUE TITLE
NoBackendError

### ISSUE THREAD

**Issue by neuromorphic-chair** [Anjok07/ultimatevocalremovergui#107]
**Describe the bug**

**To Reproduce**
1. Selected settings: any settings
2. Start Conversion
2. See error

**Expected behavior**
I expected a file to be produced.

**Screenshots**
If applicable, add screenshots to help explain your problem and annotate the images.

**Desktop (please complete the following information):**
 - OS: Windows 10 64-bit

**Additional context**
![image](https://user-images.githubusercontent.com/90221702/133602749-077ab26c-0828-4004-ad8e-478c88490282.png)

**Comment by aufr33** [comment]
Check:

ffmpeg
pip show librosa
