### ISSUE TITLE
Can not load Tkinter

### ISSUE THREAD

**Issue by Krelyshy** [Anjok07/ultimatevocalremovergui#1108]
When I try to launch UVR with `python UVR.py`, it fails with the following error:
```
Traceback (most recent call last):
File "/home/krel/apps/ultimatevocalremovergui-master/UVR.py", line 27, in <module>
import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
```

Installation of all modules went smoothly without any errors, when I try to install tkinter manually, pip fails as well, stating the following:
```
ERROR: Could not find a version that satisfies the requirement tkinter (from versions: none)
ERROR: No matching distribution found for tkinter
```

**Comment by prgarg007** [comment]
I believe you used wrong command to install tkinter.
Try using "pip install tkintertable" for installing tkinter.

**Comment by Krelyshy** [comment]
This command worked, however it's still strange that python hasn't installed it from requirements...

**Comment by Krelyshy** [comment]
Change of state, I now tried launching UVR again and tkinter is still reported as not found, exact same error as above.

**Comment by prgarg007** [comment]
How are you running the program ? Is it from the provide exe file ? Or you have installed the program manually ?

**Comment by Krelyshy** [comment]
On Linux, with `venv/bin/python UVR.py`

**Comment by prgarg007** [comment]
Got it, I believe issues is with the environment.
Try installing all requirements using 
sudo pip install -r requirement_file.txt

then after that when running the UVR gui file, run that also via 
sudo python3 file_name.py

Once try these steps and update on the status here. @Krelyshy

**Comment by Krelyshy** [comment]
I have an externally managed environment, with RPM, so I created the virtual environment in which I installed all the requirements... in other words, can't do sudo install

**Comment by Krelyshy** [comment]
OK, apparently, asking to install Tkinter system wide worked... can't it be installed as a venv package though?

**Comment by prgarg007** [comment]
I still think, its environment issue.
I believe when you are installing requirements, its installing in the main bash environment instead of in the externally managed environment & the program is running in the non installed libraries version. (Vice Versa also possible)

**Comment by prgarg007** [comment]
> OK, apparently, asking to install Tkinter system wide worked... can't it be installed as a venv package though?

Ya, apparently code is not running in the desired environment with libraries.

**Comment by Krelyshy** [comment]
> > OK, apparently, asking to install Tkinter system wide worked... can't it be installed as a venv package though?
> 
> Ya, apparently code is not running in the desired environment with libraries.

Strange... I used venv/bin/pip  +  venv/bin/python to work with it... welp, another computing mystery... thank you for the help though :-).

**Comment by prgarg007** [comment]
Glad ! It Worked For You. 
I am always reachable via email at pranavgarg37@gmail.com , for any help. I also work freelance.
