### ISSUE TITLE
MDX23C models not selectable for vocal splitting

### ISSUE THREAD

**Issue by ghost** [Anjok07/ultimatevocalremovergui#1109]
![uvr_mdx23c](https://github.com/Anjok07/ultimatevocalremovergui/assets/130250788/5c9c78d2-63c9-4b8c-af53-fd60c6986eaa)
As you can see, the 23-models are there, selectable und functional in the main window, but not selectable as vocal splitting model, while on my main workstation I can select them for splitting. I completely removed UVR and reinstalled twice making sure to remove settings and model residue, also tried the OpenCL package, both seem to have the same problem.

**Comment by Anjok07** [comment]
This isn't an error. The vocal splitter models are specifically karaoke models. We haven't trained any karaoke models for MDX23C yet.
