### ISSUE TITLE
[INSTALLATION PROBLEM] 

### ISSUE THREAD

**Issue by JohnSmith2007** [Anjok07/ultimatevocalremovergui#112]
**To Reproduce**
pip install --no-cache-dir -r requirements.txt

ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Screenshots**
![Screenshot (930)](https://user-images.githubusercontent.com/45465767/135355621-516f108a-df11-469e-9adb-06ebfcdaef4a.png)

 - OS: Windows 10

**Comment by CyberLykan** [comment]
Change the directory to where your UVR is.

**Comment by JohnSmith2007** [comment]
> Change the directory to where your UVR is.

oh ok. How do i do that? because i have no clue.

**Comment by GaganPathre** [comment]
Simply open the folder of UVR and type 'cmd' in address bar. This will open up the command prompt for the current folder location and you can move ahead for installation.

**Comment by JohnSmith2007** [comment]
Much dankeschon 😁

**Comment by GaganPathre** [comment]
> Much dankeschon 😁

You're welcome 😇
