### ISSUE TITLE
Error when I'm trying to open VocalRemover.py 

### ISSUE THREAD

**Issue by slavaspo** [Anjok07/ultimatevocalremovergui#114]
**Describe the bug**

**To Reproduce**
1. Selected settings: '...'
2. See error

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem and annotate the images.

**Desktop (please complete the following information):**

**Additional context**

**Comment by slavaspo** [comment]
This is the Error message when I'm trying to open VocalRemover.py file:
![image](https://user-images.githubusercontent.com/72882206/136044685-a66ca34b-9f07-40c6-9dec-c018226a51ac.png)

**Comment by GaganPathre** [comment]
> This is the Error message when I'm trying to open VocalRemover.py file: ![image](https://user-images.githubusercontent.com/72882206/136044685-a66ca34b-9f07-40c6-9dec-c018226a51ac.png)

The error suggests that you haven't installed the Pillow module which I required to run the application. 

Type "pip install Pillow" In the command prompt to install it.

**Comment by slavaspo** [comment]
![image](https://user-images.githubusercontent.com/72882206/136051582-97f7b716-f2f3-428a-a5f7-11667899d466.png)
I see the same Error when I'm trying to run it.
