### ISSUE TITLE
SavePath?

### ISSUE THREAD

**Issue by chirick86** [Anjok07/ultimatevocalremovergui#115]
Is there a way to save output file not in "separated" folder but define folder and name of the file with '-o' key or something?
for example:
`python inference.py -g 0 -m modelparams\4band_44100.json -n 123821KB -w 352 -P models\%model%.pth -nv -i %1 -o "c:\Instrumentals\%~n1_inst.wav"`

**Comment by ITAC85v2** [comment]
There isn't. It's as simple as that.

**Comment by Anjok07** [comment]
Please update to UVR version 5.2.0.
