### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by SamoanGerman** [Anjok07/ultimatevocalremovergui#117]
**Describe the bug**
Using the latest version of Ultimate Vocal Remover v5 on windows, on Python 3.7 with FFmpeg installed. Recieving this error when using the Drag n Drop option. I also don't really know what I'm doing for the most part.

![Screenshot (721)](https://user-images.githubusercontent.com/92365704/136927543-8ce00308-5e71-4a13-b509-fe1dc042c404.png)

**Comment by aufr33** [comment]
Have you created a **tmp** directory?
