### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by Makdeo** [Anjok07/ultimatevocalremovergui#119]
**To Reproduce**
Hello, I have a reoccurring issue when it comes to installing ultimatevocalremovergui that i cannot seem to solve.

**Screenshots**
![Screenshot (273)](https://user-images.githubusercontent.com/92700172/137653791-e53f201a-48c4-468b-b127-14683303b592.png)

**Desktop (please complete the following information):**
 -windows 10

**Additional context**
Any help is greatly appreciated.
Thank you very much.

**Comment by ITAC85v2** [comment]
Go to the link https://download.pytorch.org/whl/ and download the wheel files and install them manually. Pip sometimes seems to refuse to download them, not quite sure why.
