### ISSUE TITLE
Getting OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''

### ISSUE THREAD

**Issue by Waffled-II** [Anjok07/ultimatevocalremovergui#12]
After I install all the correct itemes,
I open a powershell to the ultimatevocalremovergui-2.2.0-GUI-Mod
Type in 

python VocalRemover.py

and I get this

Traceback (most recent call last):
  File "VocalRemover.py", line 27, in <module>
    os.chdir(base_path)  # Change the current working directory to the base path
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: ''

**Comment by aufr33** [comment]
Just edit the script like here: https://github.com/Anjok07/ultimatevocalremovergui/pull/10/files

**Comment by DilanBoskan** [comment]
This is also fixed in the new upcoming version. Currently viewable in the beta branch
