### ISSUE TITLE
deepextraction creates instrumental track rather than vocal

### ISSUE THREAD

**Issue by meckito** [Anjok07/ultimatevocalremovergui#120]
If I mix the original signal in the opposite phase and that from deepextraction, I get an improved vocal path. The algorithm seems to be working, but some operation is skipped or done incorrectly.

**Comment by ITAC85v2** [comment]
I'm pretty sure that's the point. It's meant to create a deep extraction for the instrumental to get rid of excess vocals, so there's no point into saving the vocals.
