### ISSUE TITLE
Can't open vocalremover.py

### ISSUE THREAD

**Issue by kurtiscollette** [Anjok07/ultimatevocalremovergui#121]
Installation seemed to go fine, but when I get to opening;
This is the error I get. I have no idea what this means as I don't code or anything remotely like that.

C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py
Traceback (most recent call last):
  File "VocalRemover.py", line 25, in <module>
    import inference_v2
  File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by GaganPathre** [comment]
> Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> 
> C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'



Try these commands...
pip install opencv-python.

pip install numpy

**Comment by kurtiscollette** [comment]
now this what I get;

C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py
Traceback (most recent call last):
  File "VocalRemover.py", line 25, in <module>
    import inference_v2
  File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 5, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

**Comment by kurtiscollette** [comment]
> > Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> Try these commands... pip install opencv-python.
> 
> pip install numpy
> 
> Then try to run the application.



> > Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> Try these commands... pip install opencv-python.
> 
> pip install numpy
> 
> Then try to run the application.

now this is what i get

C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py
Traceback (most recent call last):
  File "VocalRemover.py", line 25, in <module>
    import inference_v2
  File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 5, in <module>
    import librosa
ModuleNotFoundError: No module named 'librosa'

**Comment by GaganPathre** [comment]
> > > Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> > > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> > 
> > Try these commands... pip install opencv-python.
> > 
> > pip install numpy
> > 
> > Then try to run the application.
> 
> 
> 
> > > Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> > > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> > 
> > Try these commands... pip install opencv-python.
> > 
> > pip install numpy
> > 
> > Then try to run the application.
> 
> now this is what i get
> 
> C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py
> Traceback (most recent call last):
>   File "VocalRemover.py", line 25, in <module>
>     import inference_v2
>   File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 5, in <module>
>     import librosa
> ModuleNotFoundError: No module named 'librosa'

Install librosa with this statement:
pip install librosa

Extra: Whenever a module not found error is raised, try to install it with this command:
pip install  *module-name*

**Comment by kurtiscollette** [comment]
> > > > Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> > > > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> > > 
> > > 
> > > Try these commands... pip install opencv-python.
> > > pip install numpy
> > > Then try to run the application.
> > 
> > 
> > > > Installation seemed to go fine, but when I get to opening; This is the error I get. I have no idea what this means as I don't code or anything remotely like that.
> > > > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py Traceback (most recent call last): File "VocalRemover.py", line 25, in import inference_v2 File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> > > 
> > > 
> > > Try these commands... pip install opencv-python.
> > > pip install numpy
> > > Then try to run the application.
> > 
> > 
> > now this is what i get
> > C:\Users\The Mothership\Documents\UVR-V4GUI>python VocalRemover.py
> > Traceback (most recent call last):
> > File "VocalRemover.py", line 25, in 
> > import inference_v2
> > File "C:\Users\The Mothership\Documents\UVR-V4GUI\inference_v2.py", line 5, in 
> > import librosa
> > ModuleNotFoundError: No module named 'librosa'
> 
> Install librosa with this statement: pip install librosa
> 
> Extra: Whenever a module not found error is raised, try to install it with this command: pip install _module-name_

I think that did it, thanks!

**Comment by SkyryanMSM** [comment]
I tried to open it, but it closes on me.

**Comment by Anjok07** [comment]
> I tried to open it, but it closes on me.

Please update to version 5.2.0 using the Windows installer provided on the main page.
