### ISSUE TITLE
(V5) -n 129605KB doesn't work

### ISSUE THREAD

**Issue by Diego92Ita** [Anjok07/ultimatevocalremovergui#122]
**Describe the bug**
I've recently uninstalled and reinstall UVR v5 and I'm using a model that needs the "-n 129605KB" command to function. I get an error and I don't know how to solve it:
python .\inference.py -g 0 -n 129605KB -m .\modelparams\4band_44100.json -P .\models\WIP-Piano-4band-129605kb.pth -i '..\demucs-main\separated\mdx\14 - Knowledge\other.wav'

This is the error:

usage: inference.py [-h] [--gpu GPU] [--pretrained_model PRETRAINED_MODEL] --input INPUT [--nn_architecture {auto,31191KB,33966KB,123821KB,537238KB}]
                    [--model_params MODEL_PARAMS] [--window_size WINDOW_SIZE] [--output_image] [--deepextraction] [--postprocess] [--is_vocal_model] [--tta]
                    [--high_end_process {mirroring,mirroring2,bypass,none}] [--aggressiveness AGGRESSIVENESS] [--no_vocals] [--chunks CHUNKS] [--model_test_mode]
                    [--normalize] [--output_dir OUTPUT_DIR]
inference.py: error: argument --nn_architecture/-n: invalid choice: '129605KB' (choose from 'auto', '31191KB', '33966KB', '123821KB', '537238KB')

**Comment by aufr33** [comment]
129605KB architecture has been removed. Please use the older version if you still need these models.

**Comment by Diego92Ita** [comment]
Do v5 models work on v4?

**Comment by aufr33** [comment]
No, the v5 models are not compatible with v4.

**Comment by GaganPathre** [comment]
> No, the v5 models are not compatible with v4.

May we know how soon can we expect the V5 GUI?

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
