### ISSUE TITLE
Issue with new update 

### ISSUE THREAD

**Issue by jobason93** [Anjok07/ultimatevocalremovergui#123]
Run with TTA? [Y/N]: y
=======================================
          Choose Your Model
=======================================

a. HP2-4BAND-3090_4band_1
b. HP2-4BAND-3090_4band_1
c. HP_4BAND_3090
d. Vocal_HP_4BAND_3090
e. Vocal_HP_4BAND_3090_AGG
f. Ensemble All HP Instrumental Models (5 Models) - Final Outputs Save to Ensembled Folder!
g. Ensemble HP2 Models Only (3 Models) - Final Outputs Save to Ensembled Folder!
Type the letter associated with the option you choose and hit 'Enter': f
Running and Ensembling All HP Instrumental Models
Traceback (most recent call last):
  File "ensemble_inference.py", line 247, in <module>
    main()
  File "ensemble_inference.py", line 176, in main
    os.path.join('modelparams', c['model_params']) + '.json',
KeyError: 'model_params'
--------------------------------
Press any key to continue . . .

**Comment by aufr33** [comment]
Please upgrade to version 5.2
