### ISSUE TITLE
V5 Doesn't Work Anymore

### ISSUE THREAD

**Issue by fotisandstuff** [Anjok07/ultimatevocalremovergui#124]
Hello! I've been using the V5 CLI version for a long time (especially the excellent HP models), but recently I had a problem where the conversion would fail at 99% because it suddenly couldn't access the tmp folder. I re-installed everything (Python 3.7.0 plus all requirements) and now none of the .bat files work. V4 still works. I think V5 cannot communicate with my GPU anymore, because, in the Task Manager, I see an instance of python.exe using up lots of CPU (not GPU), but not doing anything else.

**Comment by ITAC85v2** [comment]
Does it return an error, or does it just completely fail? Because if it does return an error, please send it, else nobody can really help you.

**Comment by fotisandstuff** [comment]
It completely fails. It just returns "Running [x model]" forever and does nothing, while Python is simply using CPU without doing anything. Which Python version should I be using for V5?

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.

**Comment by fotisandstuff** [comment]
I updated to 5.2.0 and it works like a charm! Thank you for everything!
