### ISSUE TITLE
FIXED - Linux Mint install problems

### ISSUE THREAD

**Issue by CodesoundR** [Anjok07/ultimatevocalremovergui#1244]
Hi,
after following your instructions, the installation step crashes (after downloading all dependencies) in the 
`pip3 install -r requirements.txt`: PLEASE help me to fix this error: I tried a few times to install it, but I get the same problem....

https://imgur.com/IhQiZgi

`Collecting sklearn
  Downloading sklearn-0.0.post12.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
      rather than 'sklearn' for pip commands.
      
      Here is how to fix this error in the main use cases:
      - use 'pip install scikit-learn' rather than 'pip install sklearn'
      - replace 'sklearn' by 'scikit-learn' in your pip requirements files
        (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
      - if the 'sklearn' package is used by one of your dependencies,
        it would be great if you take some time to track which package uses
        'sklearn' instead of 'scikit-learn' and report it to their issue tracker
      - as a last resort, set the environment variable
        SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
      
      More information is available at
      https://github.com/scikit-learn/sklearn-pypi-package
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

**Comment by LordHansolo** [comment]
Hi @CodesoundR,

Solution 1 (suggested): Remove line `Dora==0.0.3` from `requirements.txt` before run `pip3 install -r requirements.txt`. The `Dora==0.0.3` package relies on the deprecated `sklearn` package. It looks like the `Dora` package is not utilized anywhere within `ultimatevocalremovergui` project at all so it should be safe to remove this dependency.

Solution 2: Run `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip3 install -r requirements.txt` instead of `pip3 install -r requirements.txt`. The `True` value of the environment variable `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL` will allow the installation of the deprecated `sklearn` package.

**Comment by root-at-pi** [comment]
Hey guys,

I'm still brand new here and tried to solve the problem yesterday.
Here is my approach:

```
  wget https://github.com/Anjok07/ultimatevocalremovergui/archive/refs/heads/master.zip
  unzip master.zip
  cd ultimatevocalremovergui-master/
  python3 -m venv pyve
  source pyve/bin/activate
> nano requirements.txt
> # Remove line with "Dora==0.0.3" and save
  pip3 install -r requirements.txt
> # Download Dora-0.0.3.tar.gz from https://pypi.org/project/Dora/#files :
> wget https://files.pythonhosted.org/packages/0c/7e/982758c0a46ccbb6356814066ccf5c849f283ea95bce098de81901adf1ab/Dora-0.0.3.tar.gz
> tar -xvzf Dora-0.0.3.tar.gz
> cd Dora-0.0.3/
> nano setup.py
> # Replace "sklearn" in line 16 with "scikit-learn" and save
> python3 setup.py install
```

Whether this is a clean way I can not judge, anyway it works ;)

**Comment by CodesoundR** [comment]
> Hi @CodesoundR,
> 
> Solution 1 (suggested): Remove line `Dora==0.0.3` from `requirements.txt` before run `pip3 install -r requirements.txt`. The `Dora==0.0.3` package relies on the deprecated `sklearn` package. It looks like the `Dora` package is not utilized anywhere within `ultimatevocalremovergui` project at all so it should be safe to remove this dependency.
> 
> Solution 2: Run `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True pip3 install -r requirements.txt` instead of `pip3 install -r requirements.txt`. The `True` value of the environment variable `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL` will allow the installation of the deprecated `sklearn` package.

Hi

Thank you so much for your suggestions! Now it works!!! Thanks again

**Comment by CodesoundR** [comment]
> Hey guys,
> 
> I'm still brand new here and tried to solve the problem yesterday. Here is my approach:
> 
> ```
>   wget https://github.com/Anjok07/ultimatevocalremovergui/archive/refs/heads/master.zip
>   unzip master.zip
>   cd ultimatevocalremovergui-master/
>   python3 -m venv pyve
>   source pyve/bin/activate
> > nano requirements.txt
> > # Remove line with "Dora==0.0.3" and save
>   pip3 install -r requirements.txt
> > # Download Dora-0.0.3.tar.gz from https://pypi.org/project/Dora/#files :
> > wget https://files.pythonhosted.org/packages/0c/7e/982758c0a46ccbb6356814066ccf5c849f283ea95bce098de81901adf1ab/Dora-0.0.3.tar.gz
> > tar -xvzf Dora-0.0.3.tar.gz
> > cd Dora-0.0.3/
> > nano setup.py
> > # Replace "sklearn" in line 16 with "scikit-learn" and save
> > python3 setup.py install
> ```
> 
> Whether this is a clean way I can not judge, anyway it works ;)
> 
> EDIT: Create a shell script to start
> 
> ```
> #!/bin/bash
> cd ~/ultimatevocalremovergui-master/
> source pyve/bin/activate
> python3 UVR.py
> ```

Thank you for your interest! Problem solved!
