### ISSUE TITLE
Maybe Installation problem but I can't figure it out

### ISSUE THREAD

**Issue by SzavulyBence** [Anjok07/ultimatevocalremovergui#125]
**Describe the bug**
Program won't start up

error message in terminal:
(MacOS Monterey 12.0.1, Python 3.7 did everything as written in the installation)

**when installing:**
pip3 install torch==1.8.1+cu111 torch-vision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.8.1+cu111
  Could not find a version that satisfies the requirement torch==1.8.1+cu111 (from versions: 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2, 1.1.0, 1.1.0.post2, 1.2.0, 1.3.0, 1.3.0.post2, 1.3.1, 1.4.0, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0)
No matching distribution found for torch==1.8.1+cu111
You are using pip version 10.0.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**So instead I used just** 
pip3 install torch torchvision torchaudio -f https://download.pytorch.org/whl/torch_stable.html
And installed correctly (something)

**And when trying to open it:**
python3 VocalRemover.py
Traceback (most recent call last):
  File "/Users/szavulybence/Documents/UVR-V4GUI/tkinterdnd2/TkinterDnD.py", line 53, in _require
    TkdndVersion = tkroot.tk.call('package', 'require', 'tkdnd')
_tkinter.TclError: dlopen(/Users/szavulybence/Documents/UVR-V4GUI/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib, 0x0006): tried: '/Users/szavulybence/Documents/UVR-V4GUI/tkinterdnd2/tkdnd/osx64/libtkdnd2.9.2.dylib' (no such file), '/usr/local/lib/libtkdnd2.9.2.dylib' (no such file), '/usr/lib/libtkdnd2.9.2.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "VocalRemover.py", line 982, in <module>
    root = MainWindow()
  File "VocalRemover.py", line 253, in __init__
    super().__init__()
  File "/Users/szavulybence/Documents/UVR-V4GUI/tkinterdnd2/TkinterDnD.py", line 285, in __init__
    self.TkdndVersion = _require(self)
  File "/Users/szavulybence/Documents/UVR-V4GUI/tkinterdnd2/TkinterDnD.py", line 55, in _require
    raise RuntimeError('Unable to load tkdnd library.')
RuntimeError: Unable to load tkdnd library.

**Comment by pangi123** [comment]
I had this issue as well. Turns out I was using the wrong python version. Installed an older version and the command worked fine

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
