### ISSUE TITLE
Too Many Options

### ISSUE THREAD

**Issue by HLRSajid** [Anjok07/ultimatevocalremovergui#126]
**Describe the flaw**
I think the number of options for conversion process is too many. 

**Expected behavior**
It will be good if the entire first column (from 'GPU Conversion' to 'Model Test mode') could be removed from GUI.
Redistribute the remaining options in the resulting freed-up space.

**Screenshots**
If applicable, add screenshots to help explain your problem and annotate the images.

**Additional context**
![UVRV4](https://user-images.githubusercontent.com/84619520/144619139-c5837a2e-cb6c-45eb-bfa7-51370da7de7a.png)

**Comment by ITAC85v2** [comment]
They're not going to remove them. It's part of the AI and they're actually useful. If you don't know what they mean, then don't mess with them. But they leave remained for those who do, like me.

**Comment by aufr33** [comment]
The new V5 will have a completely new GUI. I'm closing this Issue, ok?
