### ISSUE TITLE
new update is not working 

### ISSUE THREAD

**Issue by jobason93** [Anjok07/ultimatevocalremovergui#128]
Choose Your Model
=======================================

a. HP2-4BAND-3090_4band_1
b. HP2-4BAND-3090_4band_1
c. HP_4BAND_3090
d. Vocal_HP_4BAND_3090
e. Vocal_HP_4BAND_3090_AGG
f. Ensemble All HP Instrumental Models (5 Models) - Final Outputs Save to Ensembled Folder!
g. Ensemble HP2 Models Only (3 Models) - Final Outputs Save to Ensembled Folder!
Type the letter associated with the option you choose and hit 'Enter': f
Running and Ensembling All HP Instrumental Models
Traceback (most recent call last):
File "ensemble_inference.py", line 247, in
main()
File "ensemble_inference.py", line 176, in main
os.path.join('modelparams', c['model_params']) + '.json',
KeyError: 'model_params'
Press any key to continue . . .

**Comment by aufr33** [comment]
Hello. What specific scripts did you download?

**Comment by jobason93** [comment]
I literally download everything in the beta as a zip and I try to run the ensemble on the HP all it gave me that error

**Comment by jobason93** [comment]
can you help me with this

**Comment by overcast07** [comment]
@aufr33 I have had the same issues with using the ensembler with the Vocal_HP_4BAND_3090 model on both Windows 10 and macOS 10.14 using the current version of UVR 5.0.2. On both systems, I installed UVR 5.0.2 by downloading the source code from the repository and downloading the 5.0.2 models, installing requirements and such, and moving the 5.0.2 models into the models folder.

On macOS, this is what happens:
```
$ python3.7 ensemble_inference.py -g 0 -P "Vocal_HP_4BAND_3090" "HP_4BAND_3090" -i input.flac
Traceback (most recent call last):
  File "ensemble_inference.py", line 247, in <module>
    main()
  File "ensemble_inference.py", line 176, in main
    os.path.join('modelparams', c['model_params']) + '.json',
KeyError: 'model_params'
```

Using the model on its own without ensembling is fine (other than vocals/instrumentals being swapped). I can't identify anything more specific than this error occurring whenever that model is used in the ensembler.

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.

**Comment by jobason93** [comment]
Ty
