### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by thecoolman69420** [Anjok07/ultimatevocalremovergui#130]
(null): can't open file 'VocalRemover.py': [Errno 2] No such file or directory

**Comment by GaganPathre** [comment]
> (null): can't open file 'VocalRemover.py': [Errno 2] No such file or directory

You're executing the application from another directory which doesn't consists of the VocalRemover.py files. 

You can type cmd in the taskbar where your uvr is and try executing it.
