### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by fran985** [Anjok07/ultimatevocalremovergui#133]
Hey, i thought this phyton thing was easy, but now i have no idea how to make it work, i installed it and now i want to uninstall it.
I know this sounds stupid and it is because i am, i just installed 3,7 GB of i dont know what and i do not know how to get it off my computer, im sorry for this kind of "issue"
My question is if you could help me get rid of those files i installed on the cmd thing, thanks.

**Comment by Anjok07** [comment]
Control Panel > Uninstall Application

You wish to use UVR, please use the new UVR installer for version 5.2.0
