### ISSUE TITLE
AttributeError: "NoneType" object has no attribute "write"

### ISSUE THREAD

**Issue by DoubleF3lix** [Anjok07/ultimatevocalremovergui#136]
**Describe the bug**

**To Reproduce**
1. Selected settings: 
![image](https://user-images.githubusercontent.com/48461905/148702105-c033d97c-71c4-4da4-b5bb-20d033ff512c.png)

2. See error
![image](https://user-images.githubusercontent.com/48461905/148702111-c2fa3e30-84f2-49e4-99b5-3a61487e65ac.png)

**Expected behavior**
I expected the program to run, but it crashes as soon as I press "Start Conversion"

**Desktop (please complete the following information):**
 - OS: Windows 10, NVIDIA GTX 970

**Comment by aufr33** [comment]
We have released a new version 5.2. Please update.
