### ISSUE TITLE
Chunk option problem. [WinError 2]

### ISSUE THREAD

**Issue by chirick86** [Anjok07/ultimatevocalremovergui#137]
**Describe the bug**
When trying to process file with -c option it process normaly, and after process can't join it to one file, Can't find them

**To Reproduce**
PS D:\ultimatevocalremovergui-5-beta-cml> python inference.py -g 0 -c 5 -m modelparams\4band_44100.json -P models\HP_4BAND_3090.pth -nv -i "D:\ultimatevocalremovergui-5-beta-cml\separated\ToRemove\This.mkv"
loading model... done
loading & stft of wave source... C:\Users\chiri\AppData\Roaming\Python\Python37\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
done
Chunk 0
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:03<00:00,  5.53it/s]
inverse stft of Instruments... done
Chunk 1
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  9.03it/s]
inverse stft of Instruments... done
Chunk 2
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  9.05it/s]
inverse stft of Instruments... done
Chunk 3
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  8.94it/s]
inverse stft of Instruments... done
Chunk 4
100%|██████████████████████████████████████████████████████████████████████████████████| 21/21 [00:02<00:00,  9.00it/s]
inverse stft of Instruments... done
Traceback (most recent call last):
  File "inference.py", line 344, in <module>
    main()
  File "inference.py", line 299, in main
    subprocess.run(['sox'] + [f for f in chunks_filelist[stem].values()] + [fn])
  File "C:\Program Files\Python37\lib\subprocess.py", line 453, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37\lib\subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1155, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Не удается найти указанный файл
PS D:\ultimatevocalremovergui-5-beta-cml>

**Expected behavior**
I exepted to one joined file, not five separatly =)

**Screenshots**
![Clipboard Image](https://user-images.githubusercontent.com/20712560/152782389-d13beedf-83e3-4db7-acf1-aae968380e0a.jpg)
![Clipboard Image](https://user-images.githubusercontent.com/20712560/152784151-635aaee2-485e-4391-86c8-5f7244a2f69e.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
Without this option all works fine. Just wonder why not working with chunks cause need to use script to work on machines with less RAM

**Comment by chirick86** [comment]
I've tryind different options. models. params, tryed different files, wavs, tryed short files. The result always one. This. If I use --chunk option. Without it - all's good.

**Comment by aufr33** [comment]
Install sox: https://sourceforge.net/projects/sox/files/latest/download

**Comment by chirick86** [comment]
> Install sox: https://sourceforge.net/projects/sox/files/latest/download
And how it hepl with chunks options problem?

**Comment by aufr33** [comment]
The error says that it is impossible to execute an external **sox** command.

**Comment by chirick86** [comment]
Installed sox didn't helped. The same error.

**Comment by chirick86** [comment]
Oh, Ok It helped. I reinstalled sox from chocolately and now it's all good.
Thank you!
