### ISSUE TITLE
No Module named PIL.

### ISSUE THREAD

**Issue by Nicster205** [Anjok07/ultimatevocalremovergui#140]
Trying to set this up, and after rebuilding python, rebuilding all my modules, and even giving administrator permissions, I cannot think of what would cause this, besides the fact PIL is outdated and PILLOW should be used instead, it's even in the requirements.
```
C:\Users\user\Downloads\Compressed\uvr\UVR-V4GUI>vocalremover.py
Traceback (most recent call last):
  File "C:\Users\user\Downloads\Compressed\uvr\UVR-V4GUI\VocalRemover.py", line 10, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
```

**Comment by GaganPathre** [comment]
> Trying to set this up, and after rebuilding python, rebuilding all my modules, and even giving administrator permissions, I cannot think of what would cause this, besides the fact PIL is outdated and PILLOW should be used instead, it's even in the requirements.
> 
> ```
> C:\Users\user\Downloads\Compressed\uvr\UVR-V4GUI>vocalremover.py
> Traceback (most recent call last):
>   File "C:\Users\user\Downloads\Compressed\uvr\UVR-V4GUI\VocalRemover.py", line 10, in <module>
>     from PIL import Image
> ModuleNotFoundError: No module named 'PIL'
> ```

Run this command in cmd:
pip install Pillow

**Comment by DillFrescott** [comment]
Try completely uninstalling Pillow and reinstalling it.

**Comment by DillFrescott** [comment]
Just so you know, this project seems like it has died, based off of this exerpt:

`The official v5 GUI is still under developement and will be released some time in Q4 2021.`

And its still in beta...

**Comment by lifehackerhansol** [comment]
Using Pillow in project is done by importing PIL, that's what it is internally named. That has nothing to do with it. Something else is going on here. Also, WSL2 doesn't even support graphics output, so that won't fix anything (tried it out of sheer boredom just now and it fails to find a display output.)

`pip install -r requirements.txt` if you haven't done it yet, or `pip install Pillow`. If you have multiple python versions installed for whatever reason (like I do because my projects require Py3.8 at minimum) make sure you're running the pip specific to Py3.7 which is required here.

**Comment by chlorophyll-zz** [comment]
`pip install Pillow `did it for me. I vote for close.

**Comment by Nicster205** [comment]
> `pip install Pillow `did it for me. I vote for close.

I've already tried this, it was one of my first options,

> Using Pillow in project is done by importing PIL, that's what it is internally named. That has nothing to do with it. Something else is going on here. Also, WSL2 doesn't even support graphics output, so that won't fix anything (tried it out of sheer boredom just now and it fails to find a display output.)
> 
> `pip install -r requirements.txt` if you haven't done it yet, or `pip install Pillow`. If you have multiple python versions installed for whatever reason (like I do because my projects require Py3.8 at minimum) make sure you're running the pip specific to Py3.7 which is required here.

Already done aswell, but I have multiple versions of python, let me try uninstalling them.

**Comment by chlorophyll-zz** [comment]
> but I have multiple versions of python
then use `pip3` instead of `pip`
