### ISSUE TITLE
[V5] Error loading wave source?

### ISSUE THREAD

**Issue by LazyPainter** [Anjok07/ultimatevocalremovergui#141]
I previously had some problems with missing modules but I was able to re-install them properly but I get this message now:

Running HP2-4BAND-3090_4band_1
loading model... done
loading & stft of wave source... Traceback (most recent call last):
  File "inference.py", line 344, in <module>
    main()
  File "inference.py", line 157, in main
    wave, _ = librosa.load(args.input, bp['sr'], False, dtype=np.float32, res_type=bp['res_type'])
TypeError: load() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given

Any ideas?

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
