### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by LastDayAlive** [Anjok07/ultimatevocalremovergui#142]
![изображение](https://user-images.githubusercontent.com/45531680/155879894-a2d70fc5-6600-426e-890d-731019fd1660.png)
i'm trying to run the software, it returns that it can't initialize the sys standart stream.
IDK, maybe, it happens because of Shadow Defender which i use to test the software and prevent influece to the system. But i can not refuse to use the SD until this soft will works well

**Comment by aufr33** [comment]
Try regular cmd

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
