### ISSUE TITLE
UVR Dataset Trained Hybrid Demucs

### ISSUE THREAD

**Issue by 0xBEEEF** [Anjok07/ultimatevocalremovergui#146]
In the [issue](https://github.com/facebookresearch/demucs/issues/300) of the Demucs repository I read that a training with the help of the UVR dataset is currently being carried out. Since I find the values very impressive I wanted to ask here if the release of this is planned soon. I found the first values in the issue there very impressive. Since my goal is also to remove the voice from various recordings, I would find it very good if you could test this yourself soon.

**Comment by aufr33** [comment]
We tried to create our model for Demucs, but it didn't suit us. Therefore, we will train a new model. I think it will be ready in the summer.
