### ISSUE TITLE
GPU might not be supported.

### ISSUE THREAD

**Issue by Baorbao** [Anjok07/ultimatevocalremovergui#1497]
> Last Error Received:

Process: MDX-Net

The application was unable to allocate enough GPU memory to use this model. Please close any GPU intensive applications and try again.
If the error persists, your GPU might not be supported.

Raw Error Details:

OutOfMemoryError: "CUDA out of memory. Tried to allocate 2.20 GiB (GPU 0; 4.00 GiB total capacity; 2.54 GiB already allocated; 0 bytes free; 2.60 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF"
Traceback Error: "
  File "UVR.py", line 6638, in process_start
  File "separate.py", line 499, in seperate
  File "separate.py", line 594, in demix
  File "separate.py", line 635, in run_model
  File "torch\nn\modules\module.py", line 1190, in _call_impl
  File "onnx2pytorch\convert\model.py", line 224, in forward
  File "torch\nn\modules\module.py", line 1190, in _call_impl
  File "torch\nn\modules\conv.py", line 463, in forward
  File "torch\nn\modules\conv.py", line 459, in _conv_forward
"

Error Time Stamp [2024-08-06 18:29:14]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 5
window_size: 512
mdx_segment_size: 4000
batch_size: Default
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
overlap_mdx: Default
overlap_mdx23: 8
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_chunk_mdxnet: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
is_mdx23_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: Kim Vocal 2
chunks: Auto
margin: 44100
compensate: Auto
denoise_option: None
is_match_frequency_pitch: True
phase_option: Automatic
phase_shifts: None
is_save_align: False
is_match_silence: True
is_spec_match: False
is_mdx_c_seg_def: False
is_invert_spec: False
is_deverb_vocals: False
deverb_vocal_opt: Main Vocals Only
voc_split_save_opt: Lead Only
is_mixer_mode: False
mdx_batch_size: Default
mdx_voc_inst_secondary_model: No Model Selected
mdx_other_secondary_model: No Model Selected
mdx_bass_secondary_model: No Model Selected
mdx_drums_secondary_model: No Model Selected
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_time_correction: True
is_gpu_conversion: True
is_primary_stem_only: True
is_secondary_stem_only: False
is_testing_audio: False
is_auto_update_model_params: True
is_add_model_name: False
is_accept_any_input: False
is_task_complete: False
is_normalization: False
is_use_opencl: False
is_wav_ensemble: False
is_create_model_folder: False
mp3_bit_set: 320k
semitone_shift: 0
save_format: WAV
wav_type_set: PCM_16
device_set: Default
help_hints_var: True
set_vocal_splitter: No Model Selected
is_set_vocal_splitter: False
is_save_inst_set_vocal_splitter: False
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems
mdx_stems: All Stems

![image](https://github.com/user-attachments/assets/5acb5587-dcd6-4380-90b0-7f4f8fc33c57)

**Comment by ChrisTG742** [comment]
What graphics card do you have?

**Comment by Baorbao** [comment]
> What graphics card do you have?
Thanks for your interest! My graphics card is nvidia geforce rtx 3050 laptop gpu
![image](https://github.com/user-attachments/assets/692832d4-8e53-45ec-a0d6-f16da66793af)

**Comment by ChrisTG742** [comment]
Ok, the shared memory that is used for display (aka VRAM) is 4GB only. I think that is too less for usage with GPU-mode in this tool. You can try to tune settings like segments/window-size in the tool, but I think with 4GB you'll be out of luck.
So TL;DR: You need to use the CPU-mode on that laptop.

**Comment by Baorbao** [comment]
> Ok, the shared memory that is used for display (aka VRAM) is 4GB only. I think that is too less for usage with GPU-mode in this tool. You can try to tune settings like segments/window-size in the tool, but I think with 4GB you'll be out of luck. So TL;DR: You need to use the CPU-mode on that laptop.

got it, thanks for explaining.

**Comment by deton24** [comment]
Try out setting segments: 256 and overlap 0.25, if still the same, maybe even lower than that.
Still supported values for 4GB VRAM might be 480/0.38 as well (at least for not too long audio files above 5-6 minutes).
Kim Vocal 2 is pretty light model and still should be doable on 4GB VRAM.
If still nothing, make sure you use the latest Beta Roformer:
https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.6y2plb943p9v
You could also use voc_ft model instead, but there are better vocal models which should work for you, but Roformers will be slower:
https://docs.google.com/document/d/17fjNvJzj8ZGSer7c7OFe_CNfUKbAxEh_OBv94ZdRG5c/edit?tab=t.0#heading=h.n8ac32fhltgg
Eventually, make sure you use the latest GPU drivers and OS.
