### ISSUE TITLE
Discord for UVR and other audio splitting tools

### ISSUE THREAD

**Issue by Waffled-II** [Anjok07/ultimatevocalremovergui#15]
We have an unofficial discord for audio splitting tools (yes, including Ultimate Vocal Remover GUI). It’s mainly used for Spleeter but this app seems to work better.
Link: https://discord.gg/P7FhQFH

**Comment by Waffled-II** [comment]
Hopefully people will share models here!

**Comment by aufr33** [comment]
To train a good model, you will need a large dataset, 48-64 GB of RAM and 11 GB of VRAM. Therefore, no one shares models.

**Comment by DilanBoskan** [comment]
Opening for others to see

**Comment by DilanBoskan** [comment]
@Anjok07 I think we could put this link in the README file?
