### ISSUE TITLE
[DESIGN IMPROVEMENT]

### ISSUE THREAD

**Issue by chirick86** [Anjok07/ultimatevocalremovergui#153]
Need checkbox or dropdown list to choose what to extract. voice only, or instruments only.
It was possible in cli beta with -nv options (No-voice)
Now I can't use my .bat file and can't avoid vocal extraction
![Group 8](https://user-images.githubusercontent.com/20712560/162712436-7864485e-27b5-4060-ac56-c5029caa721a.png)

**Comment by sadness112** [comment]
Work on AMD GPU? Or is it necessary to have a CUDA only?

**Comment by bropines** [comment]
> Work on AMD GPU? Or is it necessary to have a CUDA only?
Only CUDA. Only PyTorch

**Comment by Anjok07** [comment]
This enhancement has been added. Please update to version 5.2.0 using the Windows installer provided on the main page.
