### ISSUE TITLE
Mono source process as stereo

### ISSUE THREAD

**Issue by chirick86** [Anjok07/ultimatevocalremovergui#154]
For some reason mono source changing to stereo after processing.
At lest on HP2_4BAND_44100_2.pth model
In cli beta version mono source processed as mono.

**Comment by aufr33** [comment]
AI only works in stereo. We can add auto-convert to mono if the input file is mono.

**Comment by daleyguy** [comment]
I only work with mono input files, so it would be great to have the output as mono also.
