### ISSUE TITLE
Incorrect behavior with 48khz audio

### ISSUE THREAD

**Issue by im4xxx** [Anjok07/ultimatevocalremovergui#155]
**Describe the bug**
It's freezing while "Loading wave source..." when source in 48kHz and duration more than 05:05min
duration less than 05:05min works fine.
v5-beta-cml works also fine.

**To Reproduce**
1. Selected settings: 
- file with duration more 05:05min 48kHz
- GPU Conversion
- Model = HP2_3BAND_44100_MSB2.pth
- Window Size = 512
- Aggression Setting = 10

2. See "Loading wave source..." and nothing happen

**Expected behavior** like in v4 or v5-beta-cml

**Desktop:**
 - OS: Windows 10 21H2
 - GPU: GTX 1650Ti
 - CPU: Ryzen 5 4600
 - RAM: 16gb

**Additional context**
after some testing i think that the problem some where in lines **246-256** in **inference_v5.py**
when i changed:
`X_wave[d], _ = librosa.load(music_file, bp['sr'], False, dtype=np.float32, res_type=bp['res_type'])`
to:
`X_wave[d], _ = librosa.load(music_file, False, False, dtype=np.float32, res_type=bp['res_type'])`
it didn't freeze any more, but final audio is stretching out, I guess because of resampling.

**Comment by aufr33** [comment]
Try replacing this file: https://github.com/Anjok07/ultimatevocalremovergui/blob/master/lib_v5/modelparams/3band_44100_msb2.json

**Comment by im4xxx** [comment]
> Try replacing this file: https://github.com/Anjok07/ultimatevocalremovergui/blob/master/lib_v5/modelparams/3band_44100_msb2.json

Thanks!
It works after the [18fbabc](https://github.com/Anjok07/ultimatevocalremovergui/commit/4d9122581e464350b870e9a9ee9449f97fa343b4) commit but just changing the .json didn't work for me
