### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by Nexys4t** [Anjok07/ultimatevocalremovergui#1555]
_**I'm using Windows 11**_
Despite trying to take down my antivirus(es) _**the computer is not letting me install UVR5**_

Antiviruses are McAfee and default Windows. Computer does not let me disable McAffee even for a few minutes, the option does not exist and even if trying with the Task Manager, it says I don't have permission to do that.

I used UVR5 in two other machines (modded Win10 called DeltaOS, and Win11 updated from Win10) with no issues, however I had to move a brand new one that is giving this error nonstop and _**puts the installer in quarintine over and over again, saying it has a virus.**_

_**Is there any .zip portable version of UVR5 and patches?**_ I can't build it from source code.

**Comment by 4qx** [comment]
I'd uninstall McAfee and go for something else, it's not a solution to begin with. Avast is free, and if [AV comparatives](https://www.av-comparatives.org/tests/real-world-protection-test-july-august-2024-factsheet/) is anything to go by, second best for Windows.

**Comment by Nexys4t** [comment]
> I'd uninstall McAfee and go for something else, it's not a great av solution to begin with. Avast is free, and if [AV comparatives](https://www.av-comparatives.org/tests/real-world-protection-test-july-august-2024-factsheet/) is anything to go by, is at the top for Windows solutions.

I despise Avast with all my soul haha...

I couldn't deactivate McAfee but I could let it "stop filtering" UVR5, It definetely works now
