### ISSUE TITLE
Untracked traceback error 

### ISSUE THREAD

**Issue by JJRicks** [Anjok07/ultimatevocalremovergui#156]
Got this error when using ensemble, reporting because the popup box said to. :D Thanks!
<img width="1541" alt="UVR bug" src="https://user-images.githubusercontent.com/42386719/163534505-870d96d0-1823-4d0c-bdf0-f5d409b49383.png">

**Comment by melonjack** [comment]
Confirm this bug.

**Comment by JJRicks** [comment]
No longer experiencing with latest commits
