### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by solouplay** [Anjok07/ultimatevocalremovergui#157]
**To Reproduce**
I've installed the latest version (I think it was released yesterday)- but unable to get it running. When I execute "VocalRemover.py"- I get the following error message:

Traceback (most recent call last):
  File "D:\Program\Python Vocal Remover\VocalRemover.py", line 784, in <module>
    root = MainWindow()
  File "D:\Program\Python Vocal Remover\VocalRemover.py", line 236, in __init__
    self.save_var = tk.BooleanVar(value=data['save'])
KeyError: 'save'

I am using IDLE 3.9.8.

**Screenshots**
![vrm_error](https://user-images.githubusercontent.com/103832058/163675339-065b510b-d4f8-4f2f-a56f-705ffc04161f.png)

Note here that the application does start- but it's frozen

**Desktop (please complete the following information):**
Windows 10 Version 1909

Any help is appreciated! 

Best regards
Solouplay

**Comment by im4xxx** [comment]
delete data.pkl in project directory and try again

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
