### ISSUE TITLE
speed up the conversation time

### ISSUE THREAD

**Issue by MC240** [Anjok07/ultimatevocalremovergui#158]
We want you to speed up the conversation time, as Tsurumsu did in his update of his programe
![Screenshot_20220411-045359_1](https://user-images.githubusercontent.com/103403288/163703702-76261c69-2788-47da-baa0-ccc201868d00.jpg)

**Comment by JJRicks** [comment]
Honestly I'd rather not sacrifice quality in the name of speed. Otherwise I'd use something else
