### ISSUE TITLE
Run on android

### ISSUE THREAD

**Issue by MC240** [Anjok07/ultimatevocalremovergui#159]
I want to run this program on Android in my phone is there any way?

**Comment by aufr33** [comment]
This is unlikely. AI is very computationally intensive.

You can use online services, for example, the Premium version of the [X-Minus](https://x-minus.pro/ai) or Google Colab notebook: https://colab.research.google.com/github/lucassantilli/UVR-Colab-GUI/blob/main/UVR_v5.ipynb
