### ISSUE TITLE
Error while using ensemble mode - "cannot import name 'nets_537227KB' from 'lib_v5'"

### ISSUE THREAD

**Issue by ceebu** [Anjok07/ultimatevocalremovergui#160]
**Describe the bug**
I am trying to use the ensemble HP2 model with Save all outputs enabled. When start conversion, the first two models run successfully and I get the ouputs files. However get the error in the title when trying to process the 3rd model.

&&&&&&&&&&&&&&&&&&&&&&&&  START copy paste &&&&&&&&&&&&&&&&&

C:\XXXXX\ultimatevocalremovergui-master\VocalRemover.py:92: DeprecationWarning: ANTIALIAS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  img = img.resize((size[0], int(size[0] * ratio)), Image.ANTIALIAS)
Model Parameters: lib_v5/modelparams/4band_44100.json
C:\XXXXXX\Python\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
100%|██████████████████████████████████████████████████████████████████████████████████| 95/95 [12:58<00:00,  8.20s/it]
Model Parameters: lib_v5/modelparams/4band_44100.json
100%|██████████████████████████████████████████████████████████████████████████████████| 95/95 [13:10<00:00,  8.32s/it]
  File "C:\XXXXXX\ultimatevocalremovergui-master\inference_v5_ensemble.py", line 280, in main
    from lib_v5 import nets_537227KB as nets

ImportError cannot import name 'nets_537227KB' from 'lib_v5' (unknown location)
Traceback Error: "  File "C:\XXXXXX\ultimatevocalremovergui-master\inference_v5_ensemble.py", line 280, in main
    from lib_v5 import nets_537227KB as nets
"
ImportError: "cannot import name 'nets_537227KB' from 'lib_v5' (unknown location)"
File: C:/XXXXXX/YTDL/YTDownloads/Vethala-Potta-MassTamilan.com.mp3
Please contact the creator and attach a screenshot of this error with the file and settings that caused it!

&&&&&&&&&&&&&&&&&&&&&&&& END copy paste &&&&&&&&&&&&&&&&&

**To Reproduce**
1. Selected settings: '...'
Conversion Method : Ensemble
Windows Size : 512
Choose Ensemble : HP 2 models
Save all outputs :enabled
3. See error
"cannot import name 'nets_537227KB' from 'lib_v5'"

**Expected behavior**
 I expect the ensemble model to complete the splitting operations

**Screenshots**
If applicable, add screenshots to help explain your problem and annotate the images.

https://imgur.com/a/uEV4Jdw

**Desktop (please complete the following information):**
 - OS: Win 11

**Additional context**

**Comment by ceebu** [comment]
Update: I was successfully able to run the ensemble option with HP1 models

**Comment by NathanYumekoe** [comment]
same issue here

**Comment by Anjok07** [comment]
This issue has been addressed. Please update to version 5.2.0 using the Windows installer provided on the main page.
