### ISSUE TITLE
Can't Install PyTorch [INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by ImSammy6** [Anjok07/ultimatevocalremovergui#161]
Whenever I use the command to install Pytorch, part of it will download (0.5-1GB), but then it'll stop and give me a long list of errors 
![image](https://user-images.githubusercontent.com/44005318/164103547-9ea2701c-5b7b-4ad6-9b5b-03ef08547ee2.png)

**Comment by Anjok07** [comment]
Please use the UVR v5.2 installer.
