### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by ijustwannaremovevocals** [Anjok07/ultimatevocalremovergui#162]
I am following the steps of the installation, but when I run the commands in step 6 I get this error:
![image](https://user-images.githubusercontent.com/104242839/164873509-469750df-6be2-4bda-9e5b-39ae83b8d384.png)

I am using Windows 10

**Comment by Anjok07** [comment]
Please update to version 5.2.0 using the Windows installer provided on the main page.
