### ISSUE TITLE
No error, uses CPU instead of GPU.

### ISSUE THREAD

**Issue by WubTheGame** [Anjok07/ultimatevocalremovergui#1649]
I understand it's difficult to impossible to diagnose without any error or log, but I really don't have one to provide. I've tried installing the OpenCL version (I primarily use the DirectML version because it actually works for me) but it only uses my CPU and without providing any errors or anything in logs. I'm running on a fresh installation, no additional models downloaded or anything. I've tried selecting GPU to auto and my 7900xt.

The only possible thing I could think of is that this may be a driver issue? (I use 23.11.1 so that Davinci Resolve works on my system). I read through changelogs, and _optimizations_ for AI have been made since, but as far as I could tell that doesn't necessarily mean an update is required.

**Comment by deton24** [comment]
Are you sure you're using the latest UVR version?
You can optionally try out the latest Roformer patch:
https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.6
I assume you have GPU Conversion checked.
Alternatively, try out copying DirectML.dll from your Windows installation into Ultimate Vocal Remover\torch_directml but it worked on some old drivers when GPU Conversion was crashing all the separations.

**Comment by WubTheGame** [comment]
Bold of both of us to assume I had GPU conversion checked, apparently. I somehow managed to have that off. Thank you.
