### ISSUE TITLE
Can't load wave source?

### ISSUE THREAD

**Issue by ColeDuck** [Anjok07/ultimatevocalremovergui#166]
After pressing start conversion, it cannot load wave source and pops us with an error message (screenshot)

I do not know how to reproduce it.

I expected it to work and convert.

-Windows 10

It's totally possible I messed up somewhere in the installation process. 

This app is amazing, I heard a few songs that had their vocals removed from it, and it literally sounded official. I thought it was, until I heard it was made with this. I have no idea how your team managed to do this, but great job! Any help with this would be greatly appreciated!
![i do not know](https://user-images.githubusercontent.com/104665699/166090707-310598ff-0206-49ff-86d4-bcf1a3e15730.png)

**Comment by Anjok07** [comment]
Greetings, 

This error is occurring because FFmpeg is missing or not fully installed.

**Comment by Anjok07** [comment]
I recommend anyone using 5.1 and below to please upgrade to 5.2. Nearly all of these errors have already been addressed.
