### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#169]
I use UVR installer
![Untitled](https://user-images.githubusercontent.com/66131317/168128918-897e03b4-37e5-4951-9de2-c5118d95a87e.png)

Process Method: VR Architecture

If this error persists, please contact the developers with the error details.

Traceback Error: "  File "inference_v5.py", line 739, in main
  File "inference_v5.py", line 711, in inference
  File "inference_v5.py", line 683, in _execute
  File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\nets_123812KB.py", line 106, in predict
    h = self.forward(x_mag, aggressiveness)
  File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\nets_123812KB.py", line 75, in forward
    aux2 = self.stg2_full_band_net(self.stg2_bridge(h))
  File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\nets_123812KB.py", line 34, in __call__
    h = self.dec2(h, e2)
  File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\layers_123821KB.py", line 79, in __call__
    h = self.conv(x)
  File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\layers_123821KB.py", line 25, in __call__
    return self.conv(x)
  File "torch\nn\modules\module.py", line 1051, in _call_impl
  File "torch\nn\modules\container.py", line 139, in forward
  File "torch\nn\modules\module.py", line 1051, in _call_impl
  File "torch\nn\modules\conv.py", line 443, in forward
  File "torch\nn\modules\conv.py", line 439, in _conv_forward
"
RuntimeError: "[enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 13762560 bytes."

**Comment by Anjok07** [comment]
> I use UVR installer
> ![Untitled](https://user-images.githubusercontent.com/66131317/168128918-897e03b4-37e5-4951-9de2-c5118d95a87e.png)
> 
> Process Method: VR Architecture
> 
> If this error persists, please contact the developers with the error details.
> 
> Traceback Error: "  File "inference_v5.py", line 739, in main
>   File "inference_v5.py", line 711, in inference
>   File "inference_v5.py", line 683, in _execute
>   File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\nets_123812KB.py", line 106, in predict
>     h = self.forward(x_mag, aggressiveness)
>   File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\nets_123812KB.py", line 75, in forward
>     aux2 = self.stg2_full_band_net(self.stg2_bridge(h))
>   File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\nets_123812KB.py", line 34, in __call__
>     h = self.dec2(h, e2)
>   File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\layers_123821KB.py", line 79, in __call__
>     h = self.conv(x)
>   File "C:\Users\Admin\AppData\Local\Programs\Ultimate Vocal Remover\lib_v5\layers_123821KB.py", line 25, in __call__
>     return self.conv(x)
>   File "torch\nn\modules\module.py", line 1051, in _call_impl
>   File "torch\nn\modules\container.py", line 139, in forward
>   File "torch\nn\modules\module.py", line 1051, in _call_impl
>   File "torch\nn\modules\conv.py", line 443, in forward
>   File "torch\nn\modules\conv.py", line 439, in _conv_forward
> "
> RuntimeError: "[enforce fail at ..\c10\core\CPUAllocator.cpp:79] data. DefaultCPUAllocator: not enough memory: you tried to allocate 13762560 bytes."

This error usually occurs due to lack of available system memory. Make sure you close any open programs that could be consuming too much RAM and try again.

**Comment by 404000** [comment]
I HAVE 8GB RAM

**Comment by Anjok07** [comment]
> I HAVE 8GB RAM

8GBs total or 8GBs available?

**Comment by 404000** [comment]
![Untitled](https://user-images.githubusercontent.com/66131317/168222976-bb1716eb-3a7b-44cd-82fc-566730b45841.png)

**Comment by Anjok07** [comment]
Make sure your CPU isn't under too heavy a load either.

UVR doesn't function well on Intel Celeron or Intel Pentium processors either.

**Comment by 404000** [comment]
![Untitled](https://user-images.githubusercontent.com/66131317/168224318-72e8c3e6-f385-41c1-991b-8da89bbe3643.png)

**Comment by Anjok07** [comment]
The v5 models are more computationally intensive than the v4 models. T

However, the new GUI is backward compatible with the v4 models. Go to the "Updates" tab in the help guide for more information on how to use them.

**Comment by 404000** [comment]
So why does this problem happen I have 5 GB of empty RAM (UVR installer only occupies 3 GB of RAM) and the processor has not yet reached 100%

**Comment by Anjok07** [comment]
PyTorch doesn't scale well with Intel Pentium and Celoron processors.

**Comment by hoffr** [comment]
can only use up to 1 chunk for a 4 minute file, but during processing it only uses 2gb ram. i have 12gb free during this, what's the deal?
