### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by bropines** [Anjok07/ultimatevocalremovergui#171]
Add the translation configs. I can translate functions and screenshots into Russian, Ukrainian and Polish. It would be very convenient and the program would become more widespread.

**Comment by bropines** [comment]
> > 添加翻译配置。我可以将功能和屏幕截图翻译成俄语，乌克兰语和波兰语。这将非常方便，该计划将变得更加广泛。
> > Can you translate Chinese？

Yes, but very bad. Although, I can ask a friend, he lives in China and will be able to translate everything
是的，但非常糟糕。 虽然，我可以问一个朋友，他住在中国，将能够翻译的一切 (translated with Yandex Translate)

**Comment by aufr33** [comment]
As soon as possible, we will post instructions for adding new languages. I will add Russian myself, since it is my native language.

**Comment by bropines** [comment]
> As soon as possible, we will post instructions for adding new languages. I will add Russian myself, since it is my native language.

Well, then there is a proposal to create a discord channel to communicate faster between you (developers) and us testers (users).

**Comment by aufr33** [comment]
> Well, then there is a proposal to create a discord channel to communicate faster between you (developers) and us testers (users).

Discord: https://discord.gg/frPP9Jjf
