### ISSUE TITLE
white text on white background in GUI on Linux

### ISSUE THREAD

**Issue by AwesomeGamer89** [Anjok07/ultimatevocalremovergui#177]
![image](https://user-images.githubusercontent.com/22873716/168449130-042c18d0-7a0f-4580-842c-86432950f459.png)
I use Linux mint, but I don't know what specifically causes this, since it's just the file browser. The text on the right had to be selected to show up, but there is text on the left that is white

https://user-images.githubusercontent.com/22873716/168451628-f2d846ff-7d1d-4332-b071-d8d3cf52d4e1.mp4

.

**Comment by aufr33** [comment]
I will try to reproduce this issue. In the meantime, you can drag & drop audio files into the window.
