### ISSUE TITLE
Installer EXE refuses to open

### ISSUE THREAD

**Issue by LanCeeXD** [Anjok07/ultimatevocalremovergui#185]
I've tried opening normally and with admin perms and it refuses to open.
AMD Ryzen 5 3600, 16GB DDR4 ram, GTX 980Ti 6GB OC, Windows 10 latest update.
not sure what else to add.

**Comment by Anjok07** [comment]
This could be due to your anti-virus flagging the application as a false positive. Are you unable to open the installer, or the application itself?

**Comment by rjdg14** [comment]
In my case (I'm not the OP) I seem to be getting "WinError 1455" when loading the launcher for the software (The paging file is too small for this operation to complete). I can load this older version of the software fine:

https://github.com/NaJeongMo/ultimatevocalremovergui

**Comment by LanCeeXD** [comment]
I'm unable to open the installer, and my antivirus hasn't been detecting the file at any point when I try to run it. File doesn't get deleted automatically either, it just doesn't do anything. Just tried disabling it to make sure, still absolutely nothing shows up. Even ran it as admin, nothing at all. Checked if anything was happening in Task Manager, but still nothing. Going to try redownloading now and hope for the best.

**Comment by LanCeeXD** [comment]
Reinstalled python today to try the exe installer however it still did not work, so I decided to do a manual install. everything was fine but whenever I try to open UVR.py, it flashes with a cmd window that closes itself immediately right after. No idea what the issue is. Yes the python version is correct.

**Comment by LanCeeXD** [comment]
update: i i tried different versions of python (3.7.0 and 3.9.13) and none of them work. but uvr4 opens just fine. i don't know what else to do.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
