### ISSUE TITLE
Demucs v3 AttributeError

### ISSUE THREAD

**Issue by zxcvqwerasdf** [Anjok07/ultimatevocalremovergui#193]
`AttributeError: "'Predictor' object has no attribute 'demucs'"`
inference_demucs.py line 75, in prediction
    samplerate = self.demucs.samplerate

**Comment by Anjok07** [comment]
This is a known issue. Please do the following: 

1. Close the application.
2. Go to the application folder and delete the data.pkl file
3. Open the application and try again.

**Comment by Anjok07** [comment]
This bug will be addressed so this never again in the next update.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
