### ISSUE TITLE
VR Architecture error

### ISSUE THREAD

**Issue by KovacsGergely01** [Anjok07/ultimatevocalremovergui#195]
![uvr](https://user-images.githubusercontent.com/107806677/174490485-408dae59-b365-479b-a1da-90e2352f8a6e.jpg)

**Comment by aufr33** [comment]
Make sure the output directory is writable

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
