### ISSUE TITLE
Demucs error

### ISSUE THREAD

**Issue by KovacsGergely01** [Anjok07/ultimatevocalremovergui#197]
![demucs](https://user-images.githubusercontent.com/107806677/174607312-d53f7e43-2222-464f-95cf-5454f500781d.jpg)

**Comment by Anjok07** [comment]
This is a known issue. Please do the following:

1. Close the application.
2. Go to the application folder and delete the data.pkl file
3. Open the application and try again.

This bug will be addressed in the next patch.

**Comment by KovacsGergely01** [comment]
Thanks for reply!

**Comment by Anjok07** [comment]
This is a known issue. Select Demucs Model under MDX-Net and effort should cease. This is a small bug that will be addressed in the next patch.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
