### ISSUE TITLE
VR Architecture error

### ISSUE THREAD

**Issue by KovacsGergely01** [Anjok07/ultimatevocalremovergui#198]
![vr problem](https://user-images.githubusercontent.com/107806677/174903437-01ce32c9-0aff-4e72-a341-8c8dec29436e.png)

**Comment by Anjok07** [comment]
> ![vr problem](https://user-images.githubusercontent.com/107806677/174903437-01ce32c9-0aff-4e72-a341-8c8dec29436e.png)
> 

UVR is not compatible with filenames containing special characters. Please rename the file ensuring it does not contain special characters and try again.

**Comment by KovacsGergely01** [comment]
Thanks for reply!

**Comment by Anjok07** [comment]
The song file name cannot have any special characters in it. UVR is not compatible with special characters at this time. Please rename the file and try again.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
