### ISSUE TITLE
[Bug] Processing a file containing unicode characters

### ISSUE THREAD

**Issue by h4rdee** [Anjok07/ultimatevocalremovergui#200]
Reproducing:
input filename: `Ø.mp3`

as output we have: `Ø_No_Reduction.wav` and an error message:
```
Error Received:

Missing file error raised.

FileNotFoundError - "[Errno 2] No such file or directory: 'D:/Misc/output/Ø_(Vocals).wav'"
```
and it fails to save `Ø_(Instrumental).wav` and `Ø_(Vocals).wav`, if we change Ø to O for example, everything works as intended

**Comment by 2DCool** [comment]
It happens to me too

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
