### ISSUE TITLE
UVR does not open after manual install (no error message)

### ISSUE THREAD

**Issue by LanCeeXD** [Anjok07/ultimatevocalremovergui#203]
Reinstalled python today to try the exe installer however it still did not work, so I decided to do a manual install. everything was fine but whenever I try to open UVR.py, it flashes with a cmd window that closes itself immediately right after. No idea what the issue is. Yes the python version is correct.

**Comment by aufr33** [comment]
Open CMD, change the current directory to the one where you have the UVR installed and type:

`python UVR.py`

or

`python3 UVR.py`
