### ISSUE TITLE
Error loading Python DLL python39.dll

### ISSUE THREAD

**Issue by LanCeeXD** [Anjok07/ultimatevocalremovergui#204]
encountered this while doing a manual v5.3 update to the manual install of UVR 5
![image](https://user-images.githubusercontent.com/18635351/176049545-a6ddf8ee-0449-434d-b8fa-ea8cb3fb1235.png)

**Comment by anitsekS** [comment]
same issue here

**Comment by LanCeeXD** [comment]
epic, reinstalled python again and now not even UVR4 works

**Comment by wosathena** [comment]
same issue

**Comment by chenyikuan110** [comment]
If you have this error, it's likely that you didn't download the 3.5GB full installer...

**Comment by SeanBannister** [comment]
Have tried installing both 5.3 and 5.4 versions of UVR. But I'm experiencing this problem on two different Win 10 systems, one was a fresh Win 10 install, tried installing pythong 3.9.13 and even tried copying the python39.dll to `C:\Users\[user]\AppData\Local\Programs\Ultimate Vocal Remover` while that gets rid of the error it still hangs on the splash screen.

@chenyikuan110 when you refer to a "3.5GB full installer" are you referring to python or UVR as I can't seem to find one for either.

**Comment by SeanBannister** [comment]
Figured it out, the exe file in "releases" is not the one you want, there's a separate exe linked from the README.md

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
