### ISSUE TITLE
White GUI splash screen when launching

### ISSUE THREAD

**Issue by Jack-Hewn** [Anjok07/ultimatevocalremovergui#205]
Hello. I just installed the UVR v5 GUI yesterday and it was working well. However, this morning, when I try to launch the application, the splash screen appears like normal, but then sits there and becomes white. I'm not sure if this is just an issue for me, but it's still frustrating. Regards.

Edit: I've found that if I "Run as administrator" on the shortcut or if I open its file location and run UVR.exe as administrator the application will launch. I guess it would mean that the system had trouble recognizing my account permissions, but I'm still unsure what the actual issue was/is. Nevertheless, at least now I can use the application.

![Screenshot 2022-06-28 104214](https://user-images.githubusercontent.com/67242053/176222982-93db554b-8db3-4211-bbf0-e4b7655c3611.png)
.

**Comment by EAIYHAY22** [comment]
同样出现！
