### ISSUE TITLE
Installer EXE refuses to open (no matter what version of Python I install)

### ISSUE THREAD

**Issue by LanCeeXD** [Anjok07/ultimatevocalremovergui#209]
I have tried these versions so far of python:
3.7.0 (works with UVR4 though)
3.9.13
3.9.4
3.8.10
none of then are letting me open the installer, and the manual install just flashes a cmd prompt that doesn't show anything and disappears right after again. it says to install python 3.9 nothing older than 3.6. Why isn't it just working with 3.7.0 from the get go?
AMD Ryzen 5 3600, GTX 980Ti 6GB, 16GB DDR4 RAM running off an NVMe SSD and antivirus turned off and in admin mode. Nothing happens, my cursor only has the blue circle next to it for a second or two then disappears and nothing happens.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
