### ISSUE TITLE
Visual Curly Braces Visual Fix

### ISSUE THREAD

**Issue by DilanBoskan** [Anjok07/ultimatevocalremovergui#21]
![image](https://user-images.githubusercontent.com/3925151/98599482-3d606400-2299-11eb-8361-a30ba49fa8c2.png)

_Originally posted by @ManOrMonster in https://github.com/Anjok07/ultimatevocalremovergui/issues/19#issuecomment-724293973_

**Comment by ManOrMonster** [comment]
I'm getting this now instead:

![image](https://user-images.githubusercontent.com/3925151/98604109-591b3880-22a0-11eb-944f-a3605042d365.png)

**Comment by DilanBoskan** [comment]
I mean.. I know the issue, but I will need some time finding the fix.

**Comment by ManOrMonster** [comment]
No problem, I just saw that it was closed and wanted you to know about the new issue.

**Comment by DilanBoskan** [comment]
I will address it on the original issue, this is just for the visual bug
