### ISSUE TITLE
Quality: removing vocals for classical music

### ISSUE THREAD

**Issue by rubjo** [Anjok07/ultimatevocalremovergui#210]
Here's an interesting one: Has anyone found good settings and results when dealing with classical vocal music?

Example: extracted soundtrack from https://www.youtube.com/watch?v=oxBeqYpadTs

I tried a lot of models and settings (some of which took up to 15 minutes on my computer), but the results were never really good - with either low quality / noisy instrumentals or several seconds here and there with full vocals included.

As a comparison, the same audio file processed in under a minute using https://x-minus.pro/ai was actually pretty decent (no affiliation with that site, just tried it out).

Any tips? Maybe this project is way better with pop/rock/other genres.

**Comment by Anjok07** [comment]
A new version of UVR along with brand new models are being released this weekend. UVR has a partnership with X-Minus and currently they're using the models to be released this weekend to UVR.

**Comment by rubjo** [comment]
Good to know, thanks for the update!

**Comment by rubjo** [comment]
Going to close this one, as latest version performs really well. Am still interested in models producing the best results for classical music, but will just have to experiment with different settings there, I think.
