### ISSUE TITLE
Não consigo instalar no BigLinux ou em outras distribuições, alguém pode me ajudar?

### ISSUE THREAD

**Issue by ev2bss** [Anjok07/ultimatevocalremovergui#211]
Já tentei instalar o Ultimate Vocal Remover em várias distribuições linux, como Fedora, Ubuntu, Mint, entre outros. Agora estou tentando instalar no BigLinux (baseado no Manjaro) que é minha distro diária. Alguém poderia me ajudar com um tutorial de intalação para o linux? Já tentei instalar e sempre me deparo com diversos erros. 
![Screenshot_20220709_202337](https://user-images.githubusercontent.com/109004882/178126215-2049dd56-2c3d-41e7-bf02-6c64b90b6657.png)
![Screenshot_20220709_204636](https://user-images.githubusercontent.com/109004882/178126217-e05b7d9c-fe0a-4984-a14f-c857d094c801.png)

**Comment by Anjok07** [comment]
I will be opening a separate branch for Linux very soon.
