### ISSUE TITLE
Something is messing

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#212]
Even though I installed dora .it gives me a message that dora is not installed
and Even though I Copied and paste the c:/users/admin/miniconda3/lib/site-packages/dora directory to the UVR directory .it gives me a message that dora is not installed 
![Untitled](https://user-images.githubusercontent.com/66131317/174425339-cff2bc9c-e681-4f10-8904-2b89f1bb2ae0.png)

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
