### ISSUE TITLE
Unable to use demucsv3 process method 

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [Anjok07/ultimatevocalremovergui#216]
![image](https://user-images.githubusercontent.com/78225592/180018908-68aded6d-c83f-46b3-85e7-6c8e91d0e795.png)
 
 This started to happen unexpectedly and here are my settings:
 
![image](https://user-images.githubusercontent.com/78225592/180019250-1d25e892-13f8-48ef-8336-8ad75e378e1b.png)

**Comment by Anjok07** [comment]
This is a known issue. A work around is to

- Choose MDX-Net as the process method.
- Make sure the "Demucs Model" checkbutton is ticked.
- Switch back over to Demucs v3.
- The error will cease.

I'm releasing a new patch with brand new models this weekend that addresses this error and has a ton more features.

**Comment by Anjok07** [comment]
This issue has been resolved. Please upgrade to UVR v5.4.
