### ISSUE TITLE
Multi-language

### ISSUE THREAD

**Issue by NULL204** [Anjok07/ultimatevocalremovergui#221]
I hope more languages will be released

**Comment by Anjok07** [comment]
This is something I'd like to add. However, it will require crowd sourcing efforts to help me translate as I only speak English..

**Comment by NULL204** [comment]
You can actually use the help of deepl.com, I'm from China and I feel it's very accurate.
After the first edition is published, we can give feedback about the problems in the translation, which saves a lot of time.
(Translated by deepl)
