### ISSUE TITLE
5.4.0 traceback error

### ISSUE THREAD

**Issue by LGlassySky** [Anjok07/ultimatevocalremovergui#223]
when I choose "ensemble mode" and click "start processing" then pop-up that, Traceback Error:"File"inference_v5_ensemble. py", line 2027, in main UnboundLocalError:"local variable ' mdx ensem' referenced before assignment"

**Comment by LGlassySky** [comment]
![image](https://user-images.githubusercontent.com/36590171/180605819-3d83ddd8-56cd-4e01-b7e2-c5998793094e.png)

**Comment by LGlassySky** [comment]
![image](https://user-images.githubusercontent.com/36590171/180605842-85a4afb6-f7f5-4dfd-8baf-187dac2bce99.png)

**Comment by Anjok07** [comment]
Go from the "Settings" menu click Customize Ensemble and reselect the models.

Also, did the font sizes get bigger after you upgraded?

**Comment by LGlassySky** [comment]
Thanks! that problem has solved when I upgraded. 
I remember some text of GUI was a little too large on v5.3.0, but my computer's DPI setting to 175%.I'm not sure if this is the reason.
