### ISSUE TITLE
macOS can't run this project [ bitpack , win32api ]

### ISSUE THREAD

**Issue by Chocovanilazuki** [Anjok07/ultimatevocalremovergui#225]
My test computer details:
macOS 12.5 (21G72)
intel Core i9

After I followed the ' Manual Installation ( For Developers ) ' to install this project, I found it can't run.
At first, it shows ' can't import name bitpack '

`File "/Users/chocovanilazuki/Downloads/ultimatevocalremovergui-5.3.0/diffq/base.py", line 21, in <module>
    from . import bitpack
ImportError: cannot import name 'bitpack' from partially initialized module 'diffq' (most likely due to a circular import) (/Users/chocovanilazuki/Downloads/ultimatevocalremovergui-5.3.0/diffq/__init__.py)
`

Then I found this project is relied on the ' win32api '. Only runs on Windows.

**Comment by RigoLigoRLC** [comment]
After fiddling with it for an entire night, I got it running on my M1 Mac. I have to say, this project has more issues than assuming Win32 API is present.

- It's referencing GUI-icon.png which isn't the correct case - (case sensitivity, Windows developers! Get it right!) and assumes a backslash path delimiter (Windows developers - Can you feel my hatred on backslashes?) so the program don't find the ICON and crashes (funny thing that it crashes for something ever so slightly wrong)
- Doesn't ship a uvr_patch_version.txt that is read at startup (for checking updates) and crashes (same thing as above, duh)
- Ships an x86_64 libtkdnd which isn't processed by Rosetta, and compiling tkdnd on M1 is really difficult since nobody did support on that. In my knowledge Tkdnd just adds drag and drop to Tcl/tk and so the developer of UVR5 **SHOULD DROP THIS DEPENDENCY** for compatibility
- Ships a Windows AMD64 binpack in diffq so it's not gonna load at all, you'll have to replace that with a proper version
- Assumes you're on Windows and calls sox**.exe** so if you put a macOS SoX into the respective folder it still fails to use it

And when I was configuring all this in a venv, Python dependencies are very messy. If you just do the pip install -r requirements.txt as README instructed you'll face tons of errors, mostly because the dependency is messy and something magically depends on an older SciPy & NumPy which isn't delivered in wheels. And if you try to compile Scipy/Numpy on M1, good luck fiddling with that. I ended up ignoring these weird versioning issues and just went with the latest wheels. No issues so far.

Many many small issues adds up. It's painful to debug through all this. It couldn't utilize M1 hardware (pure CPU) but ANE doesn't support a very large neural network either so I think this is the best case.

<img width="732" alt="图片" src="https://user-images.githubusercontent.com/49363666/180660184-48f0fb42-4f79-4156-93e1-e92527c26aa3.png">

**Comment by BruceZhang1993** [comment]
same issue on Arch Linux, I am trying to package this project on aur but no work.

**Comment by Anjok07** [comment]
> After fiddling with it for an entire night, I got it running on my M1 Mac. I have to say, this project has more issues than assuming Win32 API is present.
> 
> - It's referencing GUI-icon.png which isn't the correct case - (case sensitivity, Windows developers! Get it right!) and assumes a backslash path delimiter (Windows developers - Can you feel my hatred on backslashes?) so the program don't find the ICON and crashes (funny thing that it crashes for something ever so slightly wrong)
> - Doesn't ship a uvr_patch_version.txt that is read at startup (for checking updates) and crashes (same thing as above, duh)
> - Ships an x86_64 libtkdnd which isn't processed by Rosetta, and compiling tkdnd on M1 is really difficult since nobody did support on that. In my knowledge Tkdnd just adds drag and drop to Tcl/tk and so the developer of UVR5 **SHOULD DROP THIS DEPENDENCY** for compatibility
> - Ships a Windows AMD64 binpack in diffq so it's not gonna load at all, you'll have to replace that with a proper version
> - Assumes you're on Windows and calls sox**.exe** so if you put a macOS SoX into the respective folder it still fails to use it
> 
> And when I was configuring all this in a venv, Python dependencies are very messy. If you just do the pip install -r requirements.txt as README instructed you'll face tons of errors, mostly because the dependency is messy and something magically depends on an older SciPy & NumPy which isn't delivered in wheels. And if you try to compile Scipy/Numpy on M1, good luck fiddling with that. I ended up ignoring these weird versioning issues and just went with the latest wheels. No issues so far.
> 
> Many many small issues adds up. It's painful to debug through all this. It couldn't utilize M1 hardware (pure CPU) but ANE doesn't support a very large neural network either so I think this is the best case.
> 
> <img width="732" alt="图片" src="https://user-images.githubusercontent.com/49363666/180660184-48f0fb42-4f79-4156-93e1-e92527c26aa3.png">

Thank you for this! I didn't have a MacBook to test this with so this is incredibly helpful for when I start making this Mac compatible.

**Comment by Anjok07** [comment]
> > After fiddling with it for an entire night, I got it running on my M1 Mac. I have to say, this project has more issues than assuming Win32 API is present.
> > 
> > - It's referencing GUI-icon.png which isn't the correct case - (case sensitivity, Windows developers! Get it right!) and assumes a backslash path delimiter (Windows developers - Can you feel my hatred on backslashes?) so the program don't find the ICON and crashes (funny thing that it crashes for something ever so slightly wrong)
> > - Doesn't ship a uvr_patch_version.txt that is read at startup (for checking updates) and crashes (same thing as above, duh)
> > - Ships an x86_64 libtkdnd which isn't processed by Rosetta, and compiling tkdnd on M1 is really difficult since nobody did support on that. In my knowledge Tkdnd just adds drag and drop to Tcl/tk and so the developer of UVR5 **SHOULD DROP THIS DEPENDENCY** for compatibility
> > - Ships a Windows AMD64 binpack in diffq so it's not gonna load at all, you'll have to replace that with a proper version
> > - Assumes you're on Windows and calls sox**.exe** so if you put a macOS SoX into the respective folder it still fails to use it
> > 
> > And when I was configuring all this in a venv, Python dependencies are very messy. If you just do the pip install -r requirements.txt as README instructed you'll face tons of errors, mostly because the dependency is messy and something magically depends on an older SciPy & NumPy which isn't delivered in wheels. And if you try to compile Scipy/Numpy on M1, good luck fiddling with that. I ended up ignoring these weird versioning issues and just went with the latest wheels. No issues so far.
> > 
> > Many many small issues adds up. It's painful to debug through all this. It couldn't utilize M1 hardware (pure CPU) but ANE doesn't support a very large neural network either so I think this is the best case.
> > 
> > <img width="732" alt="图片" src="https://user-images.githubusercontent.com/49363666/180660184-48f0fb42-4f79-4156-93e1-e92527c26aa3.png">
> 
> Thank you for this! I didn't have a MacBook to test this with so this is incredibly helpful for when I start making this Mac compatible.

If you manage to debug through most of this create a pull request for a Mac specific install and I'll merge it.

**Comment by sonic-r85** [comment]
Thank you very much to the developers for developing such excellent software. Unfortunately, there is an Apple computer with only an m1 chip. I don't know if you can also develop a Mac version.

**Comment by blacklein** [comment]
> After fiddling with it for an entire night, I got it running on my M1 Mac. I have to say, this project has more issues than assuming Win32 API is present.
> 
> * It's referencing GUI-icon.png which isn't the correct case - (case sensitivity, Windows developers! Get it right!) and assumes a backslash path delimiter (Windows developers - Can you feel my hatred on backslashes?) so the program don't find the ICON and crashes (funny thing that it crashes for something ever so slightly wrong)
> * Doesn't ship a uvr_patch_version.txt that is read at startup (for checking updates) and crashes (same thing as above, duh)
> * Ships an x86_64 libtkdnd which isn't processed by Rosetta, and compiling tkdnd on M1 is really difficult since nobody did support on that. In my knowledge Tkdnd just adds drag and drop to Tcl/tk and so the developer of UVR5 **SHOULD DROP THIS DEPENDENCY** for compatibility
> * Ships a Windows AMD64 binpack in diffq so it's not gonna load at all, you'll have to replace that with a proper version
> * Assumes you're on Windows and calls sox**.exe** so if you put a macOS SoX into the respective folder it still fails to use it
> 
> And when I was configuring all this in a venv, Python dependencies are very messy. If you just do the pip install -r requirements.txt as README instructed you'll face tons of errors, mostly because the dependency is messy and something magically depends on an older SciPy & NumPy which isn't delivered in wheels. And if you try to compile Scipy/Numpy on M1, good luck fiddling with that. I ended up ignoring these weird versioning issues and just went with the latest wheels. No issues so far.
> 
> Many many small issues adds up. It's painful to debug through all this. It couldn't utilize M1 hardware (pure CPU) but ANE doesn't support a very large neural network either so I think this is the best case.
> 
> <img alt="图片" width="732" src="https://user-images.githubusercontent.com/49363666/180660184-48f0fb42-4f79-4156-93e1-e92527c26aa3.png">

I am using M1 mac too, but got many errors while building. Would you please share steps of how to build this project on M1 mac. Thanks a lot!

**Comment by sonic-r85** [comment]
> > After fiddling with it for an entire night, I got it running on my M1 Mac. I have to say, this project has more issues than assuming Win32 API is present.
> > 
> > * It's referencing GUI-icon.png which isn't the correct case - (case sensitivity, Windows developers! Get it right!) and assumes a backslash path delimiter (Windows developers - Can you feel my hatred on backslashes?) so the program don't find the ICON and crashes (funny thing that it crashes for something ever so slightly wrong)
> > * Doesn't ship a uvr_patch_version.txt that is read at startup (for checking updates) and crashes (same thing as above, duh)
> > * Ships an x86_64 libtkdnd which isn't processed by Rosetta, and compiling tkdnd on M1 is really difficult since nobody did support on that. In my knowledge Tkdnd just adds drag and drop to Tcl/tk and so the developer of UVR5 **SHOULD DROP THIS DEPENDENCY** for compatibility
> > * Ships a Windows AMD64 binpack in diffq so it's not gonna load at all, you'll have to replace that with a proper version
> > * Assumes you're on Windows and calls sox**.exe** so if you put a macOS SoX into the respective folder it still fails to use it
> > 
> > And when I was configuring all this in a venv, Python dependencies are very messy. If you just do the pip install -r requirements.txt as README instructed you'll face tons of errors, mostly because the dependency is messy and something magically depends on an older SciPy & NumPy which isn't delivered in wheels. And if you try to compile Scipy/Numpy on M1, good luck fiddling with that. I ended up ignoring these weird versioning issues and just went with the latest wheels. No issues so far.
> > Many many small issues adds up. It's painful to debug through all this. It couldn't utilize M1 hardware (pure CPU) but ANE doesn't support a very large neural network either so I think this is the best case.
> > <img alt="图片" width="732" src="https://user-images.githubusercontent.com/49363666/180660184-48f0fb42-4f79-4156-93e1-e92527c26aa3.png">
> 
> I am using M1 mac too, but got many errors while building. Would you please share steps of how to build this project on M1 mac. Thanks a lot!

I　installed parallets desktop 17 and windows11

**Comment by Anjok07** [comment]
> After fiddling with it for an entire night, I got it running on my M1 Mac. I have to say, this project has more issues than assuming Win32 API is present.
> 
> - It's referencing GUI-icon.png which isn't the correct case - (case sensitivity, Windows developers! Get it right!) and assumes a backslash path delimiter (Windows developers - Can you feel my hatred on backslashes?) so the program don't find the ICON and crashes (funny thing that it crashes for something ever so slightly wrong)
> - Doesn't ship a uvr_patch_version.txt that is read at startup (for checking updates) and crashes (same thing as above, duh)
> - Ships an x86_64 libtkdnd which isn't processed by Rosetta, and compiling tkdnd on M1 is really difficult since nobody did support on that. In my knowledge Tkdnd just adds drag and drop to Tcl/tk and so the developer of UVR5 **SHOULD DROP THIS DEPENDENCY** for compatibility
> - Ships a Windows AMD64 binpack in diffq so it's not gonna load at all, you'll have to replace that with a proper version
> - Assumes you're on Windows and calls sox**.exe** so if you put a macOS SoX into the respective folder it still fails to use it
> 
> And when I was configuring all this in a venv, Python dependencies are very messy. If you just do the pip install -r requirements.txt as README instructed you'll face tons of errors, mostly because the dependency is messy and something magically depends on an older SciPy & NumPy which isn't delivered in wheels. And if you try to compile Scipy/Numpy on M1, good luck fiddling with that. I ended up ignoring these weird versioning issues and just went with the latest wheels. No issues so far.
> 
> Many many small issues adds up. It's painful to debug through all this. It couldn't utilize M1 hardware (pure CPU) but ANE doesn't support a very large neural network either so I think this is the best case.
> 
> <img width="732" alt="图片" src="https://user-images.githubusercontent.com/49363666/180660184-48f0fb42-4f79-4156-93e1-e92527c26aa3.png">

**All of this** has been addressed.

UVR is now fully compatible with MacOS!

Please download the new version here (make sure to choose the installation for your architecture) - 

https://github.com/Anjok07/ultimatevocalremovergui#macos-installation
