### ISSUE TITLE
Are there plans to support MAC m1 GUI

### ISSUE THREAD

**Issue by Flyfish2046** [Anjok07/ultimatevocalremovergui#226]
Running in Win11 VIRTUAL at Parallels Desktop 17 for MAC M1 takes 5 hours for a 5 minute song ， It's really hard

**Comment by kebugcheckex** [comment]
I assume your setup involves instruction translations, which is not efficient for this kind of computation heavy workload. I'm working on porting this project to Linux/macOS. Hopefully you can run the code natively in the future.

**Comment by Anjok07** [comment]
UVR is now fully compatible with MacOS!

Please download the new version here (make sure to choose the installation for your architecture) - 

https://github.com/Anjok07/ultimatevocalremovergui#macos-installation
