### ISSUE TITLE
v5.4.0: Suddenly not able to use GPU Conversion

### ISSUE THREAD

**Issue by KatieBelli** [Anjok07/ultimatevocalremovergui#228]
I can use GPU Conversion when using the model **MDX Net MAIN** but it doesn't work on Demucs v3.

MDX:

![mdx net](https://user-images.githubusercontent.com/109644887/180651909-32360e54-af26-4f94-a83f-dca75e5d4593.PNG)

Demucs v3 error:

![demucs error](https://user-images.githubusercontent.com/109644887/180651912-aa972182-9805-4cf6-a106-ebdf08cbf6ba.PNG)

I was able to extract with GPU Conversion in the previous version but here it doesn't work. Even when I disable GPU Conversion it still shows a similiar error.

How can I solve this?

**Comment by Anjok07** [comment]
This is because you have "Split Mode" off and the chunk size is likely set to full. The chunk size menu was moved to the "Demucs Advanced Settings" menu.If you wish to have Split Mode off, you'll need to set the Chunk size to "Auto" or I recommend setting "Segment" to a number between 8-60.

**Comment by Anjok07** [comment]
> I can use GPU Conversion when using the model **MDX Net MAIN** but it doesn't work on Demucs v3.
> 
> MDX:
> 
> ![mdx net](https://user-images.githubusercontent.com/109644887/180651909-32360e54-af26-4f94-a83f-dca75e5d4593.PNG)
> 
> Demucs v3 error:
> 
> ![demucs error](https://user-images.githubusercontent.com/109644887/180651912-aa972182-9805-4cf6-a106-ebdf08cbf6ba.PNG)
> 
> I was able to extract with GPU Conversion in the previous version but here it doesn't work. Even when I disable GPU Conversion it still shows a similiar error.
> 
> How can I solve this?

This is because you have "Split Mode" off and the chunk size is likely set to full. The chunk size option was moved to the "Demucs Advanced Settings" menu. If you wish to have Split Mode off, you'll need to set the Chunk size to "Auto" or I recommend setting "Segment" to a number between 8-60.

**Comment by KatieBelli** [comment]
> >
> 
> This is because you have "Split Mode" off and the chunk size is likely set to full. The chunk size option was moved to the "Demucs Advanced Settings" menu. If you wish to have Split Mode off, you'll need to set the Chunk size to "Auto" or I recommend setting "Segment" to a number between 8-60.

This worked, thank you!
