### ISSUE TITLE
Release link down

### ISSUE THREAD

**Issue by pianomanx** [Anjok07/ultimatevocalremovergui#229]
The site: **https://uvr.uvr.workers.dev/** is up, however all the links are giving 'content offline' status.

big fan of the project btw :) extremely well done.

**Comment by Anjok07** [comment]
> The site: **https://uvr.uvr.workers.dev/** is up, however all the links are giving 'content offline' status.
> 
> big fan of the project btw :) extremely well done.

Hello and thank you!

The links have been replaced. Please try again.

**Comment by pausebreakalex** [comment]
Still not working currently.

Currently when I click on the latest version I get:
`"HTTPError: Forbidden\n    at responseErrorThrower (worker.js:179:26)\n    at async onGet (worker.js:2749:19)\n    at async handleRequest (worker.js:2942:42)"`

**Comment by Anjok07** [comment]
Thank you for the update. I believe it is fixed now. However, I've gone ahead and added a mirror link.
