### ISSUE TITLE
ImportError: cannot import name 'bitpack' from 'diffq'

### ISSUE THREAD

**Issue by seq2193** [Anjok07/ultimatevocalremovergui#232]
![523](https://user-images.githubusercontent.com/109962092/180771361-705818fa-f4e4-47a6-a3b3-616e030dd9c6.PNG)
I wrote colab ,
But the following error occurs, how can I solve it?
thanks!
Is this command correct?
https://colab.research.google.com/drive/1iqg9OroA5JFJ2xQPAAOM07G3enfDGfJo?usp=sharing

**Comment by RigoLigoRLC** [comment]
You will need to replace diffq provided in the source tree with a correct version for the host system. It contains a dynamic library which is OS specific. In the source tree there's an Windows x64 version and it clearly won't work for a cloud server that probably based on Linux.

**Comment by seq2193** [comment]
> 您需要將源代碼樹中提供的 diffq 替換為主機系統的正確版本。它包含一個特定於操作系統的動態庫。在源代碼樹中有一個 Windows x64 版本，它顯然不適用於可能基於 Linux 的雲服務器。

![55](https://user-images.githubusercontent.com/109962092/180920907-75c15427-a0f6-4d51-afd0-7055b38480ba.PNG)
Seems to be the problem.
No .pyd file for linux

**Comment by Anjok07** [comment]
I updated the repository and deleted the diffq folder. I added it to the requirements.txt instead.

**Comment by seq2193** [comment]
![58](https://user-images.githubusercontent.com/109962092/181252122-5d0d6e19-bec5-4c5c-a8fb-2fb167902d31.PNG)
![39](https://user-images.githubusercontent.com/109962092/181252312-2a192eea-510d-4fc4-977c-efad19ac8d21.PNG)
ModuleNotFoundError: No module named 'win32api'
