### ISSUE TITLE
InvalidProtobuf: "[ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from models/MDX_Net_Models/UVR-MDX-NET_Main_390.onnx failed:Protobuf parsing failed."

### ISSUE THREAD

**Issue by k-popfilters** [Anjok07/ultimatevocalremovergui#236]
i am trying to use the 340 model and a splash screen said something about correct params i just clicked okay and then i got this error?? surely it isnt the params at fault here something is definitely broken :) (iam on the current beta version for the discord mods) :)

**Comment by Anjok07** [comment]
This happened due to the links breaking. Please delete the generated "UVR-MDX-NET_Main_390.onnx" file in the models/MDX-Net_Models directory and try again in about 5 minutes. The links have been fixed.
