### ISSUE TITLE
Problems with downloading model errors

### ISSUE THREAD

**Issue by yueyin85** [Anjok07/ultimatevocalremovergui#239]
I am downloading VR Arch Single Model v5:5_HP-Karaoke-UVR
Model, prompt: Download Failed
HTTP Error 404: Not Found. Is there no support for this model anymore? or other reasons. By the way, isn't there a specific description for each model? Where to check? Thanks!

**Comment by Anjok07** [comment]
> 

Thank you for the heads up! I will fix this

**Comment by Anjok07** [comment]
Please hit the model refresh button. This issue has been resolved.
