### ISSUE TITLE
Suspicious.low.ml.score on VirusTotal

### ISSUE THREAD

**Issue by ArgX11** [Anjok07/ultimatevocalremovergui#243]
While scanning the [UVR_v5.4_Update_Package.exe](https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.4.0/UVR_v5.4_Update_Package.exe) package VirusTotal showed this result.
https://www.virustotal.com/gui/file/50468e9a9e55f66b1f8f39eb019f352d17ebf68c9d6fff0c96c04fcbf6a772ca

Could you kindly clarify on this?

**Comment by Anjok07** [comment]
I can assure you UVR is 100% safe. I need to work on getting the application signed so it isn't falsely flagged as a virus.
