### ISSUE TITLE
Vr architecture error

### ISSUE THREAD

**Issue by KovacsGergely01** [Anjok07/ultimatevocalremovergui#244]
![image](https://user-images.githubusercontent.com/107806677/181967605-2864d49d-5c9c-4647-aba6-c6a0e3a85f1b.png)

**Comment by Anjok07** [comment]
This error is usually due to the track being too large to process. How long is the file in duration?

**Comment by KovacsGergely01** [comment]
> This error is usually due to the track being too large to process. How long is the file in duration?

Uh 23 minutes
