### ISSUE TITLE
Unable to perfectly separate some back vocals from an instrumental song.

### ISSUE THREAD

**Issue by MohammedMehdiTBER** [Anjok07/ultimatevocalremovergui#246]
Tried Ensemble using Demucs mdx_extra + MDX-9482 + VR 7-HP, but VR 7-HP ruins some bell instruments in the beginning of this song:

**_John Siegler & Wayne Sharpe - Yu-Gi-Oh! Theme_**

The track is already instrumental, but not fully.
I want a way to remove the:”

> yoooou move, yugioh, to to to duel.

” vocals.
I don't have GPU to try every option as It takes a long time. Thus, I hope someone helps.

**Comment by MohammedMehdiTBER** [comment]
Link to the song FLAC:
https://mvsep.com/en/result.php?res=20220731001432-efc4156224-01_John_Siegler_and_Wayne_Sharpe_Yu_Gi_Oh_Theme

**Comment by thenormal** [comment]
> Tried Ensemble using Demucs mdx_extra + MDX-9482 + VR 7-HP, but VR 7-HP ruins some bell instruments in the beginning of this song:
> 
> **_John Siegler & Wayne Sharpe - Yu-Gi-Oh! Theme_**
> 
> The track is already instrumental, but not fully. I want a way to remove the:”
> 
> > yoooou move, yugioh, to to to duel.
> 
> ” vocals. I don't have GPU to try every option as It takes a long time. Thus, I hope someone helps.

Demucs v3 (md_extra model) seems to provide the best results. Sometimes, however, the vocals are not properly processed with it. When that happens, I use Multi-AI Ensemble mode with the following settings for better vocals extraction:

![180645083-9311c06d-bc3e-4dd6-af20-58adc6bdd167](https://user-images.githubusercontent.com/28772244/182552163-5868d2da-0998-4286-9844-b345d6a0051a.png)
![180645086-7b2a3ebd-ff98-47a6-97af-967e72ea13aa](https://user-images.githubusercontent.com/28772244/182552199-3512b868-8d92-481b-bb27-300382277193.png)
