### ISSUE TITLE
VR Architecture Error

### ISSUE THREAD

**Issue by Cowared** [Anjok07/ultimatevocalremovergui#247]
A error reported every time I run on my PC :(

GPU: RTX2060 6G
RAM: 16G

I am sure that my card was working using CUDA, I could hear the fan noises and see the GPU utilization rate was almost full.
If it just had something to do with my settings, you can check my screenshot below:

![Screennshot 2022-07-31 140506](https://user-images.githubusercontent.com/88995984/182013028-99dea497-331b-4cc6-9506-b6b5f2036afc.jpg)

And Error Log:

==========
Last Error Received:

Error Received while processing "4175640287.flac":
Process Method: VR Architecture

If this error persists, please contact the developers with the error details.

Traceback Error: "  File "inference_v5.py", line 842, in main
  File "lib_v5\spec_utils.py", line 365, in cmb_spectrogram_to_wave_d
  File "lib_v5\spec_utils.py", line 263, in spectrogram_to_wave"
MemoryError: "Unable to allocate 177. MiB for an array with shape (513, 22589) and data type complex128"

Error Time Stamp [2022-07-31 14:02:05]

==========

**Comment by Anjok07** [comment]
This error is usually due to the track being too large to process. How long is the audio file in duration?

**Comment by Cowared** [comment]
It's kind of you to reply! :D
Here is my screenshot of my music file from PotPlayer:
![Screenshot 2022-08-01 143844](https://user-images.githubusercontent.com/88995984/182087868-aac4f089-a421-4d02-8a8f-47b6a1f32d72.jpg)
It basically a .FLAC file and 4min 22s long.
Might 28.4MB music file was too large to infer on my PC? XD

**Comment by Anjok07** [comment]
You're welcome! Ahh, the issue definitely wasn't the audio duration. It might have been the window size causing issues. Try setting the Window Size to 512 and try again.

**Comment by Cowared** [comment]
Unfortunately error reported again...... :<

![Screenshot 2022-08-01 150623](https://user-images.githubusercontent.com/88995984/182091952-33f35a92-95ea-4c8b-9b06-170c69f870a1.jpg)

Error Log:

==========
Last Error Received:

Error Received while processing "4175640287.flac":
Process Method: VR Architecture

The application was unable to allocate enough GPU memory to use this model.
Please close any GPU intensive applications and try again.
If the error persists, your GPU might not be supported.

Raw error details:

Traceback Error: "  File "inference_v5.py", line 709, in main
  File "inference_v5.py", line 681, in inference
  File "inference_v5.py", line 653, in _execute
  File "G:\Ultimate Vocal Remover\lib_v5\nets_123821KB.py", line 106, in predict
    h = self.forward(x_mag, aggressiveness)
  File "G:\Ultimate Vocal Remover\lib_v5\nets_123821KB.py", line 78, in forward
    h = self.stg3_full_band_net(self.stg3_bridge(h))
  File "G:\Ultimate Vocal Remover\lib_v5\nets_123821KB.py", line 35, in __call__
    h = self.dec1(h, e1)
  File "G:\Ultimate Vocal Remover\lib_v5\layers_123821KB.py", line 78, in __call__
    x = torch.cat([x, skip], dim=1)
"
RuntimeError: "CUDA out of memory. Tried to allocate 288.00 MiB (GPU 0; 6.00 GiB total capacity; 793.31 MiB already allocated; 3.31 GiB free; 936.00 MiB reserved in total by PyTorch)"

Error Time Stamp [2022-08-01 15:04:53]

==========

**Comment by Anjok07** [comment]
Looks like a different error now. Make sure you close any GPU intensive applications.

Is UVR installed on your main drive?

**Comment by Cowared** [comment]
I closed any foreground-running program but UVR and ran once again without changing settings, but it seemed to go back to the beginning......

Error Log:

==========
Last Error Received:

Error Received while processing "4175640287.flac":
Process Method: VR Architecture

If this error persists, please contact the developers with the error details.

Traceback Error: "  File "inference_v5.py", line 842, in main
  File "lib_v5\spec_utils.py", line 365, in cmb_spectrogram_to_wave_d
  File "lib_v5\spec_utils.py", line 264, in spectrogram_to_wave
"
MemoryError: "Unable to allocate 177. MiB for an array with shape (513, 22589) and data type complex128"

Error Time Stamp [2022-08-01 15:20:31]

==========

UVR was not installed on C: but on G: , same as my audio file at.
G:\Ultimate Vocal Remover\UVR_Launcher.exe.

And I found that each time UVR seems to have made a mistake in saving the accompaniment file after doing the actual calculations?

GUI Output:

==========
File 1/1 Loading model...Done!
File 1/1 Loading assigned model parameters "4band_44100"... Done!
File 1/1 Loading audio source...Done!
File 1/1 Loading the stft of audio source... Done!
File 1/1 Please Wait...
File 1/1 Running Inferences (TTA)...
File 1/1 Processing 89 Slices... Done!
File 1/1 Processing 90 Slices... Done!
File 1/1 Saving Instrumental... 
File 1/1 Separation failed for the following audio file:
File 1/1 "4175640287.flac"

Error Received:

For raw error details, go to the Error Log tab in the Help Guide.

Please address the error and try again.
If this error persists, please contact the developers with the error details.

Time Elapsed: 00:00:45

==========

**Comment by Anjok07** [comment]
Ahh! That's the issue. UVR should be installed on the c drive to prevent issues like this. Try running UVR from the C drive and try again.

**Comment by Cowared** [comment]
Oh, if it really is I had better to do some cleaning on my PC because my C drive is almost full :\
If installing on C drive is necessary, why not add a note to readme file?
But anyway, thanks for your patient! :D

**Comment by Anjok07** [comment]
You're welcome! I updated the main readme recommending users only install UVR on the main c:\ drive.
