### ISSUE TITLE
使用中遇到1个问题

### ISSUE THREAD

**Issue by penghuade** [Anjok07/ultimatevocalremovergui#248]
在选择输入文件的时候，如果选择的文件太多（比如超过150个文件，有时甚至低于150个文件高于100个文件）整个UI就会卡住不动，建议以后选择输入文件的时候可以选择文件夹。

**Comment by Anjok07** [comment]
Thank you for the suggestion! For now it's safer to not to select more than 100 audio files to process at a time.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
