### ISSUE TITLE
Tuturials about packing to execuatable files

### ISSUE THREAD

**Issue by HowcanoeWang** [Anjok07/ultimatevocalremovergui#250]
Maybe not very related to the programme's target, in the readme file: 

> This installation bundle contains the UVR interface, Python, PyTorch, and other dependencies needed to run the application effectively. No prerequisites are required.

Could you give some instructions about packing the previous dependents to exe file (we have another deep learning project based on pytorch want to pack)? The pyinstaller can not pack so perfectly as this project did ...

Hoping for your reply!

**Comment by Anjok07** [comment]
This wasn't done with Pyinstaller alone, I had to make sure to include the packages with a work-a-round.

**Comment by HowcanoeWang** [comment]
Thanks a lot for your reply. If it costs too much time to give detailed instructions, would you mind just sharing what tools have been used to pack the full packages perfectly?

**Comment by Anjok07** [comment]
It was a lot of trial and error. I'll need to go through the instructions I made for myself, organize them, and give them here. I'll do it as soon as I have time.

**Comment by HowcanoeWang** [comment]
Thanks for your detailed reply and your efforts to make such an easy-to-use tool. I will try as your instructed!

**Comment by jie-chen** [comment]
Hi, running into similar problem. Would appreciate it if the .spec file is included in the project.
