### ISSUE TITLE
The software is invalid and keeps reporting errors

### ISSUE THREAD

**Issue by miria0** [Anjok07/ultimatevocalremovergui#251]
![QQ截图20220806183051](https://user-images.githubusercontent.com/50533928/183245158-4a4bc201-11c3-4bf1-b622-adb523ad506a.png)
![QQ截图20220806183045](https://user-images.githubusercontent.com/50533928/183245160-776c07c9-0765-49c8-8afc-a80cd645e44d.png)
The software is invalid and keeps reporting errors

**Comment by miria0** [comment]
Ensemble Mode - Running Model - 2_HP-UVR

File 1/1 Loading 2_HP-UVR... Done!
File 1/1 Loading assigned model parameters "4band_v2"... Done!
File 1/1 Loading audio source... Done!
File 1/1 Loading the stft of audio source... Done!
File 1/1 Please Wait...
File 1/1 Running Inferences (TTA)... 
File 1/1 Processing 332 Slices... 
File 1/1 Separation failed for the following audio file:
File 1/1 "111.mp4"

Error Received:

The application was unable to allocate enough system memory to use this 
model.

Please do the following:

1. Restart this application.
2. Ensure any CPU intensive applications are closed.
3. Then try again.

Please Note: Intel Pentium and Intel Celeron processors do not work well with 
this application.

If the error persists, the system may not have enough RAM, or your CPU might 
not be supported.

Time Elapsed: 00:00:22
![QQ截图20220806183045](https://user-images.githubusercontent.com/50533928/183246320-af2f3eef-d55d-4c1c-ba82-4c5dbdc5507b.png)

**Comment by miria0** [comment]
CPU：3900
GPU：2080S
32G
1T M2

**Comment by miria0** [comment]
Last Error Received:

Error Received while processing "[SHANA]4123.mp3":
Process Method: Ensemble Mode

If this error persists, please contact the developers with the error details.

Traceback Error: "  File "inference_v5_ensemble.py", line 2959, in main
  File "librosa\util\decorators.py", line 104, in inner_f
    return f(**kwargs)
  File "librosa\core\audio.py", line 599, in resample
    y_hat = scipy.signal.resample_poly(y, target_sr // gcd, orig_sr // gcd, axis=-1)
  File "scipy\signal\signaltools.py", line 3294, in resample_poly
  File "scipy\signal\_upfirdn.py", line 215, in upfirdn
  File "scipy\signal\_upfirdn.py", line 101, in apply_filter
  File "_upfirdn_apply.pyx", line 312, in scipy.signal._upfirdn_apply._apply
"
MemoryError: ""

Error Time Stamp [2022-08-07 13:26:26]

**Comment by miria0** [comment]
From yesterday to now... Not used once!

**Comment by Anjok07** [comment]
I've never seen these errors before.

I have a few questions:

1. Do you have UVR installed on your main C:\ drive?
2. How long is the audio file you're trying to process?
3. Are you running out of hard drive space?

**Comment by miria0** [comment]
> 我以前从未见过这些错误。
> 
> 我有几个问题：
> 
> 1. 您的主 C:\ 驱动器上是否安装了 UVR？
> 2. 您尝试处理的音频文件有多长？
> 3. 你的硬盘空间不够用了吗？

Solved... It is my audio is too long to cause the error!
