### ISSUE TITLE
Download center does not work

### ISSUE THREAD

**Issue by martjay** [Anjok07/ultimatevocalremovergui#253]
Download center does not work for me, each time click update can only download 2%, 5%, up to 25%, not once can download the complete, and the download process will be interrupted will not continue, please tell me UVR_Patch_8_01_2022_121 where to download

**Comment by Anjok07** [comment]
Have you checked your internet connection? I noticed a spotty internet connection will cause instability in the download center. You can actually download that new patch here - https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.4.0/UVR_v5.4_Update_Package.exe

I update the main update package concurrently with the newest patch.

**Comment by MCredbear** [comment]
> Have you checked your internet connection? I noticed a spotty internet connection will cause instability in the download center. You can actually download that new patch here - https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.4.0/UVR_v5.4_Update_Package.exe
> 
> I update the main update package concurrently with the newest patch.

So why not put a full package on Github Release Page ?

**Comment by Anjok07** [comment]
I do, I make commits to the release page everytime there's a new patch so brand new users also have the latest update.

**Comment by martjay** [comment]
> 

Thank you very much.
