### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by JomSpoons** [Anjok07/ultimatevocalremovergui#26]
When attempting to open the GUI I receive an error;

```
C:\Other\Ultimate Vocal Remover>vocalremover.py
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "C:\Other\Ultimate Vocal Remover\VocalRemover.py", line 24, in <module>
    import inference_v2
  File "C:\Other\Ultimate Vocal Remover\inference_v2.py", line 4, in <module>
    import cv2
  File "C:\Users\Username\AppData\Local\Programs\Python\Python37\lib\site-packages\cv2\__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
```

Running Python 3.7.0 and have all the required applications and packages listed in the readme installed.

**Comment by DilanBoskan** [comment]
Please try:
`pip install -U numpy`

**Comment by lucassantilli** [comment]
> Please try:
> `pip install -U numpy`

Requirement already up-to-date: numpy in c:\users\lucas\appdata\local\programs\python\python37\lib\site-packages (1.19.4)

**Comment by DilanBoskan** [comment]
Hmm, please look at this thread:
https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import

If it still does not work, please tell me you OS and current Python version.

**Comment by lucassantilli** [comment]
> Look at this thread:
> https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import
> 
> If it still does not work, please tell me your OS and current Python version.

Following each error I was able to track down the issue to being numpy's incompatibility with latest Windows 10 versions 2004 and above. I went to numpy's folder and removed the whole "Win10 sanity check" (starting at line 305) and after that I managed to open the GUI and everything works fine.

**Comment by DilanBoskan** [comment]
Great, thank you for your cooperation!

**Comment by JomSpoons** [comment]
> 
> 
> > Look at this thread:
> > https://stackoverflow.com/questions/20518632/importerror-numpy-core-multiarray-failed-to-import
> > If it still does not work, please tell me your OS and current Python version.
> 
> Following each error I was able to track down the issue to being numpy's incompatibility with latest Windows 10 versions 2004 and above. I went to numpy's folder and removed the whole "Win10 sanity check" (starting at line 305) and after that I managed to open the GUI and everything works fine.

Could you please give a step by step on how to do this? I'd appreciate it.

**Comment by DilanBoskan** [comment]
@JomSpoons Did you try the other suggestions on the thread?

**Comment by JomSpoons** [comment]
> 
> 
> @JomSpoons Did you try the other suggestions on the stackoverflow thread?

Almost every reply says to update numpy but it doesn't do anything. I'm already running numpy-1.19.4. Same error as before.

**Comment by JomSpoons** [comment]
Ok I was able to fix this issue by reverting back to version 1.19.3 of numpy by uninstalling 1.19.4 and then running `pip install numpy==1.19.3`, hopefully this'll be fixed in the next numpy update

**Comment by DilanBoskan** [comment]
Good to know, thanks!
