### ISSUE TITLE
Problem with GPU Conversion

### ISSUE THREAD

**Issue by muhfelmi** [Anjok07/ultimatevocalremovergui#266]
Error Received:

The application was unable to allocate enough GPU memory to use this model.
Please close any GPU intensive applications and try again.
If the error persists, your GPU might not be supported.

GPU used: NVIDIA GTX 1650Ti 4GB VRAM
Any solution for this issue ?

**Comment by Tang895** [comment]
did u install cuda?

**Comment by muhfelmi** [comment]
> did u install cuda?

Yes, I have already installed latest cuda driver.
