### ISSUE TITLE
您好，我在构建中遇到NumPy版本差异的问题

### ISSUE THREAD

**Issue by Vincent-the-gamer** [Anjok07/ultimatevocalremovergui#267]
您好，抱歉打扰，我看到您的项目建议在3.9以下，并且没有中文，所以尝试在Python 3.10中打包并且汉化，我使用的是您给出的numpy==1.22.0版本，但是我收到下面的错误
UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  def uniform_quantize(p: torch.Tensor, bits: torch.Tensor = torch.tensor(8.)):
这个0x10的numpy API版本具体是哪个版本？我可以重新在1.22.0下编译这个模块吗？

**Comment by lblp82nlf** [comment]
我已经汉化好了 给作者 提交了 等他 合并

**Comment by taozhiyu** [comment]
> 我已经汉化好了 给作者 提交了 等他 合并

推荐在设置中加上language选项而不是加一个文件。。。

也没办法但单独打包是吧=_=

推荐采用规范命名：zh-CN

**Comment by sduiop** [comment]
> 

可不可以单独发一个补丁？

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
