### ISSUE TITLE
A feature

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#27]
Can you add in this program a feature to separate the woman’s voice from the man’s voice

**Comment by Anjok07** [comment]
@404000 - That's going to require models trained on specific types of datasets. It'll be a good while before we get to that point.

**Comment by 404000** [comment]
I didn't understand what you mean

**Comment by 404000** [comment]
> It'll be a good while before we get to that point.
I didn't understand what you mean

**Comment by Anjok07** [comment]
> > It'll be a good while before we get to that point.
> > @Anjok07
> > I didn't understand what you mean

I mean It'll be a while before I get have the data needed to train models that can accomplish this.

**Comment by 404000** [comment]
I get this, thank you
