### ISSUE TITLE
no module named 'dora'

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#270]

**Comment by lblp82nlf** [comment]
pip install dora

**Comment by 404000** [comment]
You didn't understant .read again my problem
Pip install dora .didn't work for me

**Comment by seq2193** [comment]
pip install -U dora-search
https://pypi.org/project/dora-search/

**Comment by 404000** [comment]
> pip install -U dora-search https://pypi.org/project/dora-search/

You didn't understant .read again my problem
pip install -U dora-search .didn't work for me
