### ISSUE TITLE
无法启动软件 - Error loadling Python DLL

### ISSUE THREAD

**Issue by metaocean30** [Anjok07/ultimatevocalremovergui#275]
系统：windows10专业版21H2 x64  19044.1889 
![image](https://user-images.githubusercontent.com/111335769/186138664-97cd5cc2-574d-4bd9-b3b4-8fabd494f8df.png)
如图，在启动软件时提示Error loadling Python DLL

**Comment by MERF2007** [comment]
![屏幕截图 2022-08-29 144105](https://user-images.githubusercontent.com/60052073/187274468-077609a3-6016-4bc7-bfdb-2e9dec409984.png)
我也是一样的问题，点击确定后就卡在启动界面不动了

**Comment by lonelygoneby** [comment]
我也是嗷嗷啊啊啊

**Comment by Anjok07** [comment]
Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
