### ISSUE TITLE
The path is truncated when dragging

### ISSUE THREAD

**Issue by aufr33** [Anjok07/ultimatevocalremovergui#28]
**Describe the bug**

In some cases, the path is truncated when dragging.

**To Reproduce**

1. I put the program in C:\Soft\ultimatevocalremovergui-master
2. And named the file as my_favourite_game.mp3
3. I drag it to the window.

**Screenshots**

![scr](https://user-images.githubusercontent.com/65520685/99355620-aeb39e80-28b9-11eb-9f1e-37310ce0519c.png)

**Desktop**
 - OS: Windows 10
- Python: 3.7.4

**Comment by DilanBoskan** [comment]
Hello!
Thank you for the detailed report.

Can you try extracting this zip and replacing the VocalRemover.py from this to yours and tell me if everything works?
[VocalRemover.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/5554084/VocalRemover.zip)

**Comment by aufr33** [comment]
Now everything works as it should!
