### ISSUE TITLE
GPU conversion failed to start, CUDA core not found

### ISSUE THREAD

**Issue by fenginsc** [Anjok07/ultimatevocalremovergui#281]
GPU conversion failed to start, CUDA core not found
CUDA version 11.4.4 installed
The graphics card version is GTX 780 Ti

**Comment by hockinsk** [comment]
I have the same error running this on my laptop which has an Nvidia GeForce GTX 965 which has 1024 CUDA cores I believe. Not sure why it would be rejected, it seems to only want to use the CPU mode.

**Comment by 8bit-coder** [comment]
I have the same issue, GTX 550 Ti, clearly has 196 CUDA cores yet UVR5 doesn't let me use the GPU. It seems like it expects an RTX series or something and the developers forgot older generations exist.

**Comment by Anjok07** [comment]
Unfortunately, GPU compatibility with Pytoch is out of my control. UVR requires the latest version of Pytorch in order to run many of the models in the application, including the Demucs v4 models.

**Comment by fenginsc** [comment]
It seems that the minimum requirement for graphics cards is GTX 1000 series graphics cards, and some GTX 900 series graphics cards can also run.
