### ISSUE TITLE
App does not respond when i import large amount of files

### ISSUE THREAD

**Issue by XcantloadX** [Anjok07/ultimatevocalremovergui#282]
Now I have 103 audio files to process. Directly importing them will make the app unresponsive, and I also found no command line options, and unfortunately I don't know python. So how can I batch process large amount of files?

**Comment by Anjok07** [comment]
This will be addressed in the next patch.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
