### ISSUE TITLE
当我使用Demucs v3试图提取鼓的时候，出现了traceback error

### ISSUE THREAD

**Issue by lmh12138** [Anjok07/ultimatevocalremovergui#288]
以下是报错信息：
Last Error Received:

Error Received while processing "雷佳 - 人世间.flac":
Process Method: Demucs v3

If this error persists, please contact the developers with the error details.

Traceback Error: "  File "inference_demucs.py", line 1180, in main
  File "inference_demucs.py", line 149, in prediction
  File "inference_demucs.py", line 664, in demix
"
ValueError: "invalid literal for int() with base 10: 'Full'"

Error Time Stamp [2022-09-19 01:07:08]

**Comment by Anjok07** [comment]
This will be addressed in the next update. For now, set the chunk size to "0" instead of "Full". The 2 are the same.
