### ISSUE TITLE
Error loading Python DLL

### ISSUE THREAD

**Issue by SusiKette** [Anjok07/ultimatevocalremovergui#291]
I get the following error when I try to run the program:

```
Error loading Python DLL 'D:\Ultimate Vocal
Remover\python39.dll'.
LoadLibrary: Määritettyä osaa ei löydy.
```

I have Python 3.9.0 installed on my PC, so what is the issue?

**Comment by scratchfury** [comment]
Did you click on the "Main Download Link" or just get the Update from the Assests section like I did thinking it was the whole thing?

**Comment by krigeta** [comment]
I am getting the same error too, any solution? the python is installed in my PC.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
