### ISSUE TITLE
LoadLibrary failed with Error 1114

### ISSUE THREAD

**Issue by zakazbigpro** [Anjok07/ultimatevocalremovergui#295]
Dear
Inatall all ok 
After start UVR  have error 1114  not create DLL  LoadLibrary failed with Error 1114
My OS Windows 10 Pro 21H2 X-64
Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz   2.50 GHz
Please help me 
![1114](https://user-images.githubusercontent.com/115007682/193827311-926117c4-528d-4df7-85e4-b4feaeda9997.png)

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
