### ISSUE TITLE
FileNotFoundError when saving the instrumental after processing appears to finish

### ISSUE THREAD

**Issue by aezick** [Anjok07/ultimatevocalremovergui#298]
This is the error that I see, where "song-name" is the same as the input file that I am trying to process.
`FileNotFoundError - "[Errno 2] No such file or directory: 'C:/Users/andre/OneDrive/Desktop/UVR files/song-name.wav'"`

Unfortunately when I open the error log via the settings button, there is nothing in the error log.

I am on Windows 11 if that might matter. I have installed ffmpeg and confirmed it can be found in my system path.

Here is the processing output that I can see before the error clears it all out:
```File 1/1 Loading ONNX model... Done!
File 1/1 Chunk size auto-set to 60... 
File 1/1 Running ONNX Inference...
File 1/1 Processing 4 slices... Done!
File 1/1 Inferences complete!
File 1/1 Saving Vocals... Done!
File 1/1 Performing Noise Reduction... Done!
File 1/1 Saving Instrumental...```

**Comment by ProFire** [comment]
I'm also having this error.

`FileNotFoundError - "[Errno 2] No such file or directory: 'C:/Users/shurn/Desktop/1_1_ရွှေလက်တွဲ - Bawa ဘဝ-ေရႊလက္တြဲ (Official MV)_(Vocals)_No_Reduction_(Vocals).wav'"`

I'm on Windows 10. My file name is "1_ရွှေလက်တွဲ - Bawa ဘဝ-ေရႊလက္တြဲ (Official MV)_(Vocals)_No_Reduction.wav". Error log also shows nothing.

**Comment by Andrei1744** [comment]
You need to disable noise reduction.

**Comment by ProFire** [comment]
Interesting! It worked. I'm curious as to why I needed to set noise reduction to "none". Other files worked with noise reduction set to "3".

**Comment by ChromaPIE** [comment]
The issue was also on my end till I tried removing all accented characters from the file name. Try renaming it, make sure it doesn't include things like Burmese characters, should solve the problem.

**Comment by Anjok07** [comment]
This has been addressed. Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation
