### ISSUE TITLE
Change options design 

### ISSUE THREAD

**Issue by AlbyTree** [Anjok07/ultimatevocalremovergui#3]
I think that the options that let you insert numbers have their "boxes" too close to the check options and this might confuse at first.
A solution is to move those boxes to the right of the options but by doing this the options texts are too close the the other check options so I suggest to
*  Enclose the check options and the number options in separate rectangles
*  Move the number options more to the right 

![vocal-remover-gui-menu-fix-2](https://user-images.githubusercontent.com/34436621/88476237-37878280-cf37-11ea-94af-883e22e2d6cb.png)

**Comment by eugene0396** [comment]
Hi, do you have a link to google colab program from tsurumeso-vocal-remover, or maybe there is a video tutorial on how to install it, I can't do this. I just don't understand because new to thi,help me please..

**Comment by eugene0396** [comment]
Hi, do you have a link to google colab program from tsurumeso-vocal-remover, or maybe there is a video tutorial on how to install it, I can't do this. I just don't understand because new to this,help me please..

**Comment by DilanBoskan** [comment]
@AlbyTree The new version should make this a lot clearer. You can look it up at in the beta branch
