### ISSUE TITLE
No module named "cv2"

### ISSUE THREAD

**Issue by lucellent** [Anjok07/ultimatevocalremovergui#30]
The GUI closes itself the moment I open it, so I ran it with CMD. I'm getting this error

https://i.imgur.com/EQ8jbIf.png

I have Python 3.7 added to path and everything from the requirements installed into the GUI folder.

**Comment by DilanBoskan** [comment]
Please try:
https://stackoverflow.com/a/59025632

**Comment by lucellent** [comment]
I tried both commands but nothing happens in CMD, I tried opening it as an admin also

**Comment by DilanBoskan** [comment]
Could you try some googling on behalf of your issue?
I can assure you that this has nothing to do with our application but rather your installation of open-cv.

**Comment by lucellent** [comment]
Can change the status to solved. I had to install a couple of things.

**Comment by DilanBoskan** [comment]
Great!
If you could leave the link here that solved your issue that may be helpful for others.

**Comment by lucellent** [comment]
It was a couple of things, like installing opencv, limbosa, torch etc. I just Googled "install *name of the issue*" and the CMD command appeared on the first website.

**Comment by DilanBoskan** [comment]
Ahh, sure, alright.
