### ISSUE TITLE
Vocal/instrumental remove range options

### ISSUE THREAD

**Issue by ClausMandal** [Anjok07/ultimatevocalremovergui#301]
In the new CLI version mentioned, it would be very useful if one could specify a range to be processed:

--FROM 1:10 --TO 2:25

When processed the range will be inserted back into the track and saved.

This would work for both vocal and instrumental:

--REMOVE vocal

Later a GUI could be made for it, where you mark a range in a waveform to be processed. Then one can do several ranges easily, and then save.

Thanks for a wonderful package!

**Comment by otomad** [comment]
I think it's not necessary, in fact, to do it all once and then mix it with the original using other audio processing software, such as Audition.

**Comment by ClausMandal** [comment]
I use Audacity. A simple plugin from there could call vocal remover with a marked area. But haven't seen that yet. So my thought is of course that a CLI version that does that would do the trick fast. Easy to find areas of interest in Audacity and then changing the command to process the file. 

So you're processing it all, putting the original and processed into Audition, then fade in/out the desired areas?
