### ISSUE TITLE
Please add demucs v4!

### ISSUE THREAD

**Issue by dillfrescott** [Anjok07/ultimatevocalremovergui#303]
It was released a few days ago under the `ht` branch. I'd love to see it in UVR!

**Comment by Anjok07** [comment]
Once they officially release it, I will add it to UVR!

**Comment by yueyin85** [comment]
@Anjok07 demucs v4：https：//github.com/facebookresearch/demucs/tree/ht

**Comment by Anjok07** [comment]
**Update**

I actually added it this week and all of the v4 models work perfectly in the new IVR code! 

The public release of UVR v5.5 will be available very soon

**Comment by Lukasz858585** [comment]
It's great news that UVR will be adding a new version of Demucs v4. Can you see a significant improvement over Demucs version 3 ?

**Comment by dillfrescott** [comment]
> It's great news that UVR will be adding a new version of Demucs v4. Can you see a significant improvement over Demucs version 3 ?

Yes it seems to be a decent improvement!

**Comment by Lukasz858585** [comment]
I tested the Demucs 4 version and I must say that the instruments have less artifacts and the sound is more consistent compared to the Demucs 3 version. I tried three models htdemucs, htdemucs_ft and mdx_q. I didn't notice much difference between htdemucs and htdemucs_ft.

**Comment by Anjok07** [comment]
Demucs 4 has been added! Please download the latest version of UVR.

Link:
https://github.com/Anjok07/ultimatevocalremovergui#installation

**Comment by dillfrescott** [comment]
Awesome!
