### ISSUE TITLE
Demucs Version 4 was officially released today

### ISSUE THREAD

**Issue by thenormal** [Anjok07/ultimatevocalremovergui#307]
https://github.com/facebookresearch/demucs

**Comment by sduiop** [comment]
How to add ultimatevocalremovergui ？

**Comment by Cuarizma2020** [comment]
Demucs Version 4: https://github.com/facebookresearch/demucs

How do I update Demucs Version 4 in the UVR program?

**Comment by Anjok07** [comment]
Demucs v4 is not compatible with the current release. However, UVR v5.5 will be released this week, and it's fully compatible with Demucs v4 and the 6 stem model.

**Comment by sduiop** [comment]
> Demucs v4 与当前版本不兼容。然而，UVR v5.5 将于本周发布，它与 Demucs v4 和 6 杆模型完全兼容。

This is really exciting news。
I watch the channel every day

**Comment by hockinsk** [comment]
Great news!

**Comment by Anjok07** [comment]
UVR has been updated to include Demucs v4 and much more - https://github.com/Anjok07/ultimatevocalremovergui/releases
