### ISSUE TITLE
Demucs Version 4: https://github.com/facebookresearch/demucs

### ISSUE THREAD

**Issue by Cuarizma2020** [Anjok07/ultimatevocalremovergui#309]
How do I update Demucs Version 4 in the UVR program?

**Comment by hockinsk** [comment]
Is being added to 5.5 update I believe. https://x-minus.pro has it in the premium subscription.

**Comment by Anjok07** [comment]
Demucs v4 is not compatible with the current release. However, UVR v5.5 will be released this week, and it's fully compatible with Demucs v4 and the 6 stem model.

**Comment by Anjok07** [comment]
UVR has been updated to include Demucs v4 and much more - https://github.com/Anjok07/ultimatevocalremovergui/releases
