### ISSUE TITLE
How can I use htdemucs.yaml (Demucs V. 4) with MDX-Net (error message)?

### ISSUE THREAD

**Issue by KatieBelli** [Anjok07/ultimatevocalremovergui#313]
I want to use the MDX-Net models with the newest Demucs model (version 4, htdemucs). I added htdemucs.yaml it to the Demucs models folder and I receive this error when I want to use this model with MDX-Net:

> Last Error Received:
> 
> Error Received while processing "hello demo test.flac":
> Process Method: MDX-Net
> 
> If this error persists, please contact the developers with the error details.
> 
> Traceback Error: "  File "inference_MDX.py", line 1692, in main
>   File "inference_MDX.py", line 321, in prediction_setup
>   File "demucs\pretrained.py", line 68, in get_model
>   File "demucs\repo.py", line 154, in get_model
>   File "demucs\repo.py", line 136, in get_model
>   File "demucs\repo.py", line 136, in <listcomp>
>   File "demucs\repo.py", line 104, in get_model
> "
> ModelLoadingError: "Could not find pre-trained model with signature 955717e8."
> 
> Error Time Stamp [2022-12-09 15:07:19]

![error](https://user-images.githubusercontent.com/109644887/206720586-aabca978-a6a0-4103-9fbd-f8c33ab3b7a8.JPG)

What can I do to solve this?

**Comment by KatieBelli** [comment]
I searched for 955717e8.th but the search result is a txt-file where 955717e8-8726e21a.th is mentioned.

How can I get 955717e8.th?

**Comment by ryrycd** [comment]
Short Answer: Wait until version 5.5 comes out. It should be out before the end of the year.

Long Answer: Get whichever audio you're trying to separate and run it through your preferred MDX models on UVR. Take the same audio and run it through the new demucs 4 model in your terminal. Check [this](https://github.com/facebookresearch/demucs/blob/main/docs/windows.md) for instructions on how to get that set up. Also, I'd recommend using the fine-tuned model by putting "n htdemucs_ft" into your command.

Then, take both of these separations and go back to UVR. Use Manual Ensemble mode and select both separations (MDX separation and the Demucs 4 separation). This is a workaround way to start using htdemucs with MDX-Net. But, this feature will be added in a couple of weeks maximum.

Feel free to reply if you have any questions!

**Comment by KatieBelli** [comment]
> Short Answer: Wait until version 5.5 comes out. It should be out before the end of the year.
> 
> Long Answer: Get whichever audio you're trying to separate and run it through your preferred MDX models on UVR. Take the same audio and run it through the new demucs 4 model in your terminal. Check [this](https://github.com/facebookresearch/demucs/blob/main/docs/windows.md) for instructions on how to get that set up. Also, I'd recommend using the fine-tuned model by putting "n htdemucs_ft" into your command.
> 
> Then, take both of these separations and go back to UVR. Use Manual Ensemble mode and select both separations (MDX separation and the Demucs 4 separation). This is a workaround way to start using htdemucs with MDX-Net. But, this feature will be added in a couple of weeks maximum.
> 
> Feel free to reply if you have any questions!

I followed your long answer and the results sound better than using any of the already existing demucs models.
Thank you for helping me. I will do it this way until the update is available.
