### ISSUE TITLE
Demucs 4.0 released 

### ISSUE THREAD

**Issue by vijaykrsvkr** [Anjok07/ultimatevocalremovergui#316]
Please update to include Demucs 4.0

**Comment by TRvlvr** [comment]
UVR has been updated to include Demucs v4 and much more - https://github.com/Anjok07/ultimatevocalremovergui/releases

**Comment by Anjok07** [comment]
UVR has been updated to include Demucs v4 and much more - https://github.com/Anjok07/ultimatevocalremovergui/releases

**Comment by vijaykrsvkr** [comment]
Thank you very much 😊...  where can i find info on newly added demucs 4.0 models such as htdemucs, htdemucs_ff, htdemucs_6s and hdemucs_mmi

**Comment by thenormal** [comment]
> Thank you very much 😊... where can i find info on newly added demucs 4.0 models such as htdemucs, htdemucs_ff, htdemucs_6s and hdemucs_mmi

Ask their forum here: https://github.com/facebookresearch/demucs

**Comment by Anjok07** [comment]
Go to "Download More Models" under the model selections. You can download them directly from the application.
