### ISSUE TITLE
Problem with opening the PY

### ISSUE THREAD

**Issue by fooometoo** [Anjok07/ultimatevocalremovergui#32]
I did all that was meant to be done in order to open the file, but when I click at Vocalremover.py it only opens a blank CMD. I am new to it all.

C:\UVR-V4GUI>python VocalRemover.py
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
                 It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
Traceback (most recent call last):
  File "VocalRemover.py", line 24, in <module>
    import inference_v2
  File "C:\UVR-V4GUI\inference_v2.py", line 10, in <module>
    from lib_v2 import dataset
  File "C:\UVR-V4GUI\lib_v2\dataset.py", line 4, in <module>
    import torch
  File "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\__init__.py", line 127, in <module>
    raise err
OSError: [WinError 126] Nie można odnaleźć określonego modułu. Error loading "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\lib\asmjit.dll" or one of its dependencies.

**Comment by DilanBoskan** [comment]
Hello!
Please read the error message before considering to create an issue.

It clearly says:
```
Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
```
And you have a dll load failure in the end:
```
Error loading "C:\Users\name\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\lib\asmjit.dll" or one of its dependencies.
```

Consider installing Microsoft Visual C++ Redistributable, thank you!
