### ISSUE TITLE
macos m1 mac cannot run python script

### ISSUE THREAD

**Issue by blacklein** [Anjok07/ultimatevocalremovergui#320]
```
❯ python uvr.py
Traceback (most recent call last):
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/soundfile.py", line 267, in <module>
    _snd = _ffi.dlopen('sndfile')
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: ctypes.util.find_library() did not manage to locate a library called 'sndfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxx/Downloads/ultimatevocalremovergui-master/uvr.py", line 7, in <module>
    import librosa
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
    from . import core
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/librosa/core/__init__.py", line 6, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/soundfile.py", line 276, in <module>
    _snd = _ffi.dlopen(_os.path.join(
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
    raise OSError(msg)
OSError: cannot load library '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib'
```

**Comment by TRvlvr** [comment]
I'm still working on making this compatible with Mac. Manual installs are still not recommended at this time.

**Comment by Anjok07** [comment]
I'm still working on making this compatible with Mac. Manual installs are still not recommended at this time.

**Comment by Anjok07** [comment]
> ❯ python uvr.py
> Traceback (most recent call last):
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/soundfile.py", line 267, in <module>
>     _snd = _ffi.dlopen('sndfile')
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
>     lib, function_cache = _make_ffi_library(self, name, flags)
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
>     backendlib = _load_backend_lib(backend, libname, flags)
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
>     raise OSError(msg)
> OSError: ctypes.util.find_library() did not manage to locate a library called 'sndfile'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/xxx/Downloads/ultimatevocalremovergui-master/uvr.py", line 7, in <module>
>     import librosa
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/librosa/__init__.py", line 209, in <module>
>     from . import core
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/librosa/core/__init__.py", line 6, in <module>
>     from .audio import *  # pylint: disable=wildcard-import
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/librosa/core/audio.py", line 8, in <module>
>     import soundfile as sf
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/soundfile.py", line 276, in <module>
>     _snd = _ffi.dlopen(_os.path.join(
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 150, in dlopen
>     lib, function_cache = _make_ffi_library(self, name, flags)
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 832, in _make_ffi_library
>     backendlib = _load_backend_lib(backend, libname, flags)
>   File "/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/cffi/api.py", line 827, in _load_backend_lib
>     raise OSError(msg)
> OSError: cannot load library '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib': dlopen(/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib, 0x0002): tried: '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file), '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib' (no such file).  Additionally, ctypes.util.find_library() did not manage to locate a library called '/Users/xxx/.virtualenvs/22-ballontranslator-3.9.13shared/lib/python3.9/site-packages/_soundfile_data/libsndfile.dylib'

I just uploaded the MacOS code. You can try it [here](https://github.com/Anjok07/ultimatevocalremovergui/tree/uvr_5_5_MacOS)

**Comment by blacklein** [comment]
i tried mac branch, same OSError Msg

**Comment by blacklein** [comment]
I found why comes up the OSError Msg. In my M1 Max macOS 'libsndfile.dylib' is named 'libsndfile_arm64.dylib', i rename it to without'_arm64' tag, and run python3 UVR.py. Now it works, GUI shows up but in terminal there is some new error:

`cannot import name 'windll' from 'ctypes' (/Users/chenzhiyu/.pyenv/versions/3.10.9/lib/python3.10/ctypes/__init__.py)`

does this error msg matter?

and one more question, which model should I download for M1 Mac?

**Comment by blacklein** [comment]
I use following UVR.spec file and run `sudo pyinstaller UVR.spec` to create a standalone macOS app, but the app open crashes, can you help, thanks alot.

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['UVR.py'],
    pathex=['./', './demucs', './lib_v5'],
    binaries=[],
    datas=[('gui_data', './gui_data'), ('models', './models'), ('ffmpeg', '.'), ('lib_v5', './lib_v5')],
    hiddenimports=['ffmeg'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='UVR',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['icon.icns'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='UVR',
)
app = BUNDLE(
    coll,
    name='UVR.app',
    icon='icon.icns',
    bundle_identifier=None,
)

```

**Comment by Anjok07** [comment]
I'm still working on the stand alone version. It will be released soon.

**Comment by Anjok07** [comment]
The stand line Mac version will be released by the end of the week

**Comment by Lukasz858585** [comment]
Are we talking about the GUI version ?

**Comment by Anjok07** [comment]
> I use following UVR.spec file and run `sudo pyinstaller UVR.spec` to create a standalone macOS app, but the app open crashes, can you help, thanks alot.
> 
> ```
> # -*- mode: python ; coding: utf-8 -*-
> 
> 
> block_cipher = None
> 
> 
> a = Analysis(
>     ['UVR.py'],
>     pathex=['./', './demucs', './lib_v5'],
>     binaries=[],
>     datas=[('gui_data', './gui_data'), ('models', './models'), ('ffmpeg', '.'), ('lib_v5', './lib_v5')],
>     hiddenimports=['ffmeg'],
>     hookspath=[],
>     hooksconfig={},
>     runtime_hooks=[],
>     excludes=[],
>     win_no_prefer_redirects=False,
>     win_private_assemblies=False,
>     cipher=block_cipher,
>     noarchive=False,
> )
> pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
> 
> exe = EXE(
>     pyz,
>     a.scripts,
>     [],
>     exclude_binaries=True,
>     name='UVR',
>     debug=False,
>     bootloader_ignore_signals=False,
>     strip=False,
>     upx=True,
>     console=False,
>     disable_windowed_traceback=False,
>     argv_emulation=False,
>     target_arch=None,
>     codesign_identity=None,
>     entitlements_file=None,
>     icon=['icon.icns'],
> )
> coll = COLLECT(
>     exe,
>     a.binaries,
>     a.zipfiles,
>     a.datas,
>     strip=False,
>     upx=True,
>     upx_exclude=[],
>     name='UVR',
> )
> app = BUNDLE(
>     coll,
>     name='UVR.app',
>     icon='icon.icns',
>     bundle_identifier=None,
> )
> 
> ```

The stand-alone Mac version has been released! Check out the releases page.
