### ISSUE TITLE
UVR 5.50 MacOS - ModuleNotFoundError: No module named 'audioread'

### ISSUE THREAD

**Issue by ryrycd** [Anjok07/ultimatevocalremovergui#327]
Hi! I know this MacOS version is just 3 hours old but UVR.py will not open or run due to this error. All requirements are installed and I have confirmed audioread installed, but I keep getting the ModuleNotFoundError.

Thank you and UVR 5.50 looks amazing!!

**Comment by loaykhalifa** [comment]
> Hi! I know this MacOS version is just 3 hours old but UVR.py will not open or run due to this error. All requirements are installed and I have confirmed audioread installed, but I keep getting the ModuleNotFoundError.
> 
> Thank you and UVR 5.50 looks amazing!!

me too & i can't run i don't know what to do
