### ISSUE TITLE
Error in Llvmlite pakage

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#33]
When installing librosa everything is fine but llvmlite does not want to install
/storage/emulated/0 $ pip install librosa
Collecting librosa
  Using cached librosa-0.8.0-py3-none-any.whl
Requirement already satisfied: scikit-learn!=0.19.0,>=0.14.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (0.23.1)
Requirement already satisfied: scipy>=1.0.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.4.1)
Requirement already satisfied: joblib>=0.14 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (0.14.1)
Requirement already satisfied: numpy>=1.15.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.19.3)
Collecting audioread>=2.0.0
  Using cached audioread-2.1.9-py3-none-any.whl
Collecting decorator>=3.0.0
  Using cached decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting numba>=0.43.0
  Using cached numba-0.51.2-cp38-cp38-linux_aarch64.whl
Requirement already satisfied: numpy>=1.15.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.19.3)
Requirement already satisfied: setuptools in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from numba>=0.43.0->librosa) (46.4.0)
Collecting llvmlite<0.35,>=0.34.0.dev0
  Using cached llvmlite-0.34.0.tar.gz (107 kB)
Collecting pooch>=1.0
  Using cached pooch-1.3.0-py3-none-any.whl (51 kB)
Collecting appdirs
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting packaging
  Using cached packaging-20.7-py2.py3-none-any.whl (35 kB)
Requirement already satisfied: pyparsing>=2.0.2 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from packaging->pooch>=1.0->librosa) (2.4.7)
Collecting requests
  Using cached requests-2.25.0-py2.py3-none-any.whl (61 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from requests->pooch>=1.0->librosa) (1.26.2)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.11.8-py2.py3-none-any.whl (155 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting resampy>=0.2.2
  Using cached resampy-0.2.2-py3-none-any.whl
Requirement already satisfied: scipy>=1.0.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.4.1)
Requirement already satisfied: numpy>=1.15.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.19.3)
Requirement already satisfied: six>=1.3 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from resampy>=0.2.2->librosa) (1.15.0)
Requirement already satisfied: joblib>=0.14 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (0.14.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from scikit-learn!=0.19.0,>=0.14.0->librosa) (2.1.0)Requirement already satisfied: scipy>=1.0.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.4.1)
Requirement already satisfied: numpy>=1.15.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.19.3)
Requirement already satisfied: numpy>=1.15.0 in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from librosa) (1.19.3)
Collecting soundfile>=0.9.0
  Using cached SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting cffi>=1.0
  Using cached cffi-1.14.4-cp38-cp38-linux_aarch64.whl
Requirement already satisfied: pycparser in /data/data/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages (from cffi>=1.0->soundfile>=0.9.0->librosa) (2.20)
Building wheels for collected packages: llvmlite  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:   command: /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/setup.py'"'"'; __file__='"'"'/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /data/data/ru.iiec.pydroid3/cache/pip-wheel-28q1s35c
       cwd: /data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/
  Complete output (26 lines):
  running bdist_wheel
  /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8 /data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 489, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 856, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 1728, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 191, in <module>
      main()
    File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite, idna, chardet, certifi, requests, packaging, numba, cffi, appdirs, soundfile, resampy, pooch, decorator, audioread, librosa
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/setup.py'"'"'; __file__='"'"'/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/ru.iiec.pydroid3/cache/pip-record-cz61w2b5/install-record.txt --single-version-externally-managed --compile --install-headers /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/include/python3.8/llvmlite
         cwd: /data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/
    Complete output (29 lines):
    running install
    running build
    got version from file /data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8 /data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 411, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 489, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 856, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/subprocess.py", line 1728, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 191, in <module>
        main()
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/bin/python3.8 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/setup.py'"'"'; __file__='"'"'/data/data/ru.iiec.pydroid3/cache/pip-install-w4wa3mx_/llvmlite_5a26a0668de8430cbbbcf30a7d29e94d/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /data/data/ru.iiec.pydroid3/cache/pip-record-cz61w2b5/install-record.txt --single-version-externally-managed --compile --install-headers /data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/include/python3.8/llvmlite Check the logs for full command output.

**Comment by DilanBoskan** [comment]
Hm, try upgrading your pip version and also have you tried doing some online research on the issue? It certainly does not have something to do with our application.
Thank you!
