### ISSUE TITLE
Best module

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#339]
Is the vocal & instrument output from vr architecture:7_hp2_uvr the same as the vocal & instrument output from mdx net:uvr-mdx-net main?
Who is the best model that gives us the best result?

**Comment by thenormal** [comment]
Apparently, the best results are provided when using Multi-AI Ensemble. Check https://mvsep.com/quality_checker/leaderboard.php for a list of models/combos which give the best results
