### ISSUE TITLE
UVR is not freeing VRAM after inference

### ISSUE THREAD

**Issue by Zcooger** [Anjok07/ultimatevocalremovergui#34]
As seen by some users.
I noticed it personally after using V4 models with stacking and not.

**Comment by DilanBoskan** [comment]
I will look into it.
I guess a temporary work-around would be to restart the application after an inference.

**Comment by Zcooger** [comment]
Good, once application is restarted keeping last selected models will be useful too.

**Comment by DilanBoskan** [comment]
Can you give me more information? How much VRam is being used up, is it only on v4 or also on v2? With which options is the VRAM usage the highest?

> As seen by some users.
Who, how many?

Every detail helps, thank you.

**Comment by DilanBoskan** [comment]
Please try out the newest commit in the dev branch.

**Comment by Zcooger** [comment]
Tested and working properly, VRAM is now cleaned after inference.
From 1,98GB VRAM during inference regardless of settings 0,23GB is still free.
3 or 4 users of Audio Separation Discord that use UVR GUI noticed that.

**Comment by DilanBoskan** [comment]
Thank you for the info.

**Comment by lesecs** [comment]
I have installed all the programs  to run vocal remover. When i want to open vocal remover.py, i have a black screen few sec, and ils not open.
Can you tell me why,,,,,,,Ty

**Comment by DilanBoskan** [comment]
@lesecs Please open a new issue with a detailed description. Every piece of info helps
