### ISSUE TITLE
When will uvr release for Mac (standalone)

### ISSUE THREAD

**Issue by codplay89** [Anjok07/ultimatevocalremovergui#346]
Hey I'm new to GitHub and uvr and have loved uvr since recently finding out about it. I was just wondering, can anyone give me a time frame of when UVR standalone will release for Mac? I understand the devs are hard at work and I truly appreciate everything you guys are doing for uvr 5!

**Comment by Anjok07** [comment]
Very soon! I'm shooting for a Stand alone Mac release within the next 2 weeks, with a beta release coming sooner. There are a few small but import issues that still need to be worked out.

**Comment by codplay89** [comment]
Bro thank you so much! and its UVR 5? will it have all the features that make the export quality higher like windows has?
I love making hq instrumentals and I'm so thankful uvr is a thing! I hope you guys never stop making UVRs.

**Comment by Anjok07** [comment]
That's correct, it will be the latest version

**Comment by Lukasz858585** [comment]
I have a question if it will be a version that will support the potential of m1 processors ?

**Comment by Anjok07** [comment]
> I have a question if it will be a version that will support the potential of m1 processors ?

Yes, actually, I made sure to include the Torch library with M1 support, and the GUI will automatically detect it it's available. Check out the master UVR branch for updated instructions for MacOS.

**Comment by Lukasz858585** [comment]
Thanks for your reply, I'm curious what will be the difference in the efficiency of stem separation. I am currently testing on an old Intel i3 8100 procesor.

**Comment by Anjok07** [comment]
The MacOS stand-alone version has been released!
