### ISSUE TITLE
one progress bar instead of two progress bars

### ISSUE THREAD

**Issue by 404000** [Anjok07/ultimatevocalremovergui#35]
I wonder why I see two progress bars, I think one progress bar is sufficient, knowing that the first progress bar is the same as the second progress bar
Is it possible to modify the program to show one progress bar in stead of two progress bars to reduce the time
![Annotation 2020-02-29 181042](https://user-images.githubusercontent.com/66131317/100813175-0536e600-343f-11eb-8e1c-ded4ae83e95a.png)

**Comment by Zcooger** [comment]
It's because TTA option or extra stacked model is counted as extra inference/filter pass and in result console shows 2 progress bars.
