### ISSUE TITLE
MemoryError: "Unable to allocate 8.00 KiB for an array with shape (2048,) and data type float32"

### ISSUE THREAD

**Issue by cjhines7** [Anjok07/ultimatevocalremovergui#350]
I get memory errors, even on older low power models. Never had this issue with 5.4

Last Error Received:

Process: Ensemble Mode

If this error persists, please contact the developers with the error details.

Raw Error Details:

MemoryError: "Unable to allocate 8.00 KiB for an array with shape (2048,) and data type float32"
Traceback Error: "
  File "UVR.py", line 4502, in process_start
  File "separate.py", line 245, in seperate
  File "separate.py", line 865, in prepare_mix
  File "librosa\util\decorators.py", line 88, in inner_f
  File "librosa\core\audio.py", line 170, in load
  File "librosa\core\audio.py", line 242, in __audioread_load
  File "librosa\util\decorators.py", line 88, in inner_f
  File "librosa\util\utils.py", line 1381, in buf_to_float
"

Error Time Stamp [2022-12-27 16:36:04]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 10
window_size: 512
batch_size: 4
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: v3 | mdx_extra
segment: Default
overlap: 0.25
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: UVR-MDX-NET Inst 3
chunks: Auto
margin: 44100
compensate: Auto
is_denoise: False
is_invert_spec: False
mdx_voc_inst_secondary_model: MDX-Net: Kim_Vocal_1
mdx_other_secondary_model: Demucs: v4 | htdemucs_ft
mdx_bass_secondary_model: Demucs: v4 | htdemucs_ft
mdx_drums_secondary_model: Demucs: v4 | htdemucs_ft
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: True
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_gpu_conversion: False
is_primary_stem_only: False
is_secondary_stem_only: False
is_testing_audio: False
is_add_model_name: False
is_accept_any_input: False
is_task_complete: False
is_normalization: False
is_create_model_folder: False
mp3_bit_set: 320k
save_format: WAV
wav_type_set: PCM_16
help_hints_var: True
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems

**Comment by Anjok07** [comment]
There could be an issue with the track you are processing. Have you tried a different audio file?

**Comment by cjhines7** [comment]
I tried different files and got the same result. It worked on my PC but not on my laptop, so I knew the problem was definitely on my end. I reset my laptop and that fixed it 🙂 Thanks for all you hard work on this excellent software 👍
