### ISSUE TITLE
Report Error

### ISSUE THREAD

**Issue by PlautoCam** [Anjok07/ultimatevocalremovergui#353]
Last Error Received:

Process: MDX-Net

If this error persists, please contact the developers with the error details.

Raw Error Details:

RuntimeError: "Error opening 'C:/Users/Mumusic/Downloads/Ultimate Chord Engine (1)\\1_Dalva de Oliveira - Bandeira Branca_45_second_sample_(Vocals).wav': System error."
Traceback Error: "
  File "UVR.py", line 4502, in process_start
  File "separate.py", line 260, in seperate
  File "separate.py", line 218, in write_audio
  File "soundfile.py", line 430, in write
    duration = "{0:02.0g}:{1:05.3f} min".format(minutes, seconds)
  File "soundfile.py", line 740, in __init__
    "'SoundFile' object has no attribute {0!r}".format(name))
  File "soundfile.py", line 1264, in _open
  File "soundfile.py", line 1455, in _error_check
    return mode_int
"

Error Time Stamp [2022-12-28 07:38:54]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 10
window_size: 512
batch_size: 4
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
demucs_voc_inst_secondary_model: MDX-Net: UVR-MDX-NET Inst 1
demucs_other_secondary_model: Demucs: v3 | mdx_q
demucs_bass_secondary_model: Demucs: v4 | htdemucs_ft
demucs_drums_secondary_model: Demucs: v4 | htdemucs_ft
demucs_is_secondary_model_activate: True
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: Kim_Vocal_1
chunks: Auto
margin: 44100
compensate: Auto
is_denoise: False
is_invert_spec: True
mdx_voc_inst_secondary_model: MDX-Net: UVR-MDX-NET 1
mdx_other_secondary_model: Demucs: v3 | mdx_q
mdx_bass_secondary_model: Demucs: v4 | htdemucs_ft
mdx_drums_secondary_model: Demucs: v4 | htdemucs_ft
mdx_is_secondary_model_activate: True
mdx_voc_inst_secondary_model_scale: 0.01
mdx_other_secondary_model_scale: 0.99
mdx_bass_secondary_model_scale: 0.99
mdx_drums_secondary_model_scale: 0.99
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_gpu_conversion: False
is_primary_stem_only: False
is_secondary_stem_only: False
is_testing_audio: False
is_add_model_name: False
is_accept_any_input: False
is_task_complete: False
is_normalization: False
is_create_model_folder: False
mp3_bit_set: 320k
save_format: WAV
wav_type_set: PCM_24
help_hints_var: False
model_sample_mode: True
model_sample_mode_duration: 45
demucs_stems: All Stems

**Comment by Anjok07** [comment]
Thank you for reporting. Does this happen with all your tracks or just this one?

**Comment by PlautoCam** [comment]
Hi, I did some more tests and it seems that the problem occurs with that audio file. Anyway, I'll pay attention!
