### ISSUE TITLE
For UVR 5.50, pictures should be added to the Github page explaining how the program should be used.  In previous versions these images were available on the Github page, but as of the new version, they are no longer on the page.

### ISSUE THREAD

**Issue by Cuarizma2020** [Anjok07/ultimatevocalremovergui#354]
For UVR 5.50, pictures should be added to the Github page explaining how the program should be used.  In previous versions these images were available on the Github page, but as of the new version, they are no longer on the page.

**Comment by Anjok07** [comment]
This is because I added a new feature to the GUI called "Help Hints". When enabled, you can hover over options in the GUI to get more information on them.
