### ISSUE TITLE
Cannot launch UVR

### ISSUE THREAD

**Issue by emmrecs** [Anjok07/ultimatevocalremovergui#356]
A very new user here...

On first install and initial run, no problem to open the app

Any and all subsequent attempts to open it produce the error message shown in the attached screenshot.
![ScreenShot01088](https://user-images.githubusercontent.com/121627661/209976098-a8654590-3d5c-4464-ab8f-0049aa788924.jpg)

Any and all advice very gratefully received!

(Installation is on D:\ because that is where I choose to install almost all programs.)

**Comment by Anjok07** [comment]
UVR must be installed to the C drive.

**Comment by emmrecs** [comment]
Sorry to ask, but why?

As I wrote, the initial runs of the app following installation were successful.  Only after the computer had been turned off overnight and then rebooted the following morning did the problem arise.

**Comment by Anjok07** [comment]
Because UVR does not have administrative privileges. Some of the libraries also depend on the application being on the c drive.

**Comment by emmrecs** [comment]
Thank you for taking the time to reply!  I understand now and have uninstalled it and reinstalled to its default location.  All seems to be running well!
