### ISSUE TITLE
Why Download center keeps saying "No Internet Connection", can't download any model...

### ISSUE THREAD

**Issue by czhou** [Anjok07/ultimatevocalremovergui#358]
Version: 5.5.0
Plateform: Win10
![image](https://user-images.githubusercontent.com/1319245/210034293-7b6eb26b-e0fa-4010-a162-235b15aab74a.png)

**Comment by Anjok07** [comment]
Please check the error log and paste the output here.

**Comment by czhou** [comment]
I went through 'C:\Users\me\AppData\Local\Programs\Ultimate Vocal Remover' directory, didn't find any log file, any hint please?

**Comment by czhou** [comment]
OK, here is it:
===================
Last Error Received:

Process: Online Data Refresh

If this error persists, please contact the developers with the error details.

Raw Error Details:

URLError: "<urlopen error [Errno 11004] getaddrinfo failed>"
Traceback Error: "
  File "UVR.py", line 3440, in online_check
  File "urllib\request.py", line 214, in urlopen
  File "urllib\request.py", line 517, in open
  File "urllib\request.py", line 534, in _open
  File "urllib\request.py", line 494, in _call_chain
  File "urllib\request.py", line 1389, in https_open
  File "urllib\request.py", line 1349, in do_open
"

Error Time Stamp [2022-12-31 11:57:29]
================================
seems that GFW blocked github address " https://raw.githubusercontent.com/TRvlvr/application_data/main/filelists/download_checks.json"
I am going to test it through a VPN.

**Comment by Ethkuil** [comment]
@czhou Excuse me but would you mind teaching me how to fix it? I failed even I have setup global proxy😭.

**Comment by Ethkuil** [comment]
> @czhou Excuse me but would you mind teaching me how to fix it? I failed even I have setup global proxy😭.

I have fixed it. I edit the `hosts` file and it works.

**Comment by Roopchand2023** [comment]
What lines to edit the hosts files for solving No internet Connection error? can you please share?

**Comment by SoftCharacter** [comment]
I am experiencing the same problem, please let me know how to fix it, thanks!

**Comment by Axolyz** [comment]
The same problem. But after reinstalling to D drive it solved.
