### ISSUE TITLE
Mac exporting time

### ISSUE THREAD

**Issue by codplay89** [Anjok07/ultimatevocalremovergui#362]
Hey so I just got uvr 5 for Mac. I have an m1 MacBook Air, 256 gb ssd and 8 gb ram. Whenever I process a song using ensemble, it takes literally like over 2 hours to finish. Even now it's still exporting as I'm typing this. Will this be fixed in future updates?

**Comment by Anjok07** [comment]
This is the limitation of Mac. Pytorch with Cuda performs best with newer Nvidia GPUs on Windows. However, there's no way to speed up conversion speeds on Mac until Pytorch compatibility with MPS expands.

**Comment by codplay89** [comment]
Got you. The online vocal remover of uvr 5 works a bit faster so I just use that. Also, the online version of uvr 5 does a way better job at removing vocals than uvr 5. do you know what I'm doing wrong? I'm very new to this whole code stuff with vocal removing

**Comment by Lukasz858585** [comment]
What do you mean by online version ? Are you referring to mvsep ?
I too am testing on a mac mini with m1 processor and it takes about 10 hours to process a full CD (18 tracks) on my old i3 8100 takes 8 hours.
I thought there would be a big performance gain.
But still the final processing quality is really very good. Great job and a big thank you to the whole team.

Przetłumaczono za pomocą DeepL (https://www.deepl.com/app/?utm_source=ios&utm_medium=app&utm_campaign=share-translation

**Comment by codplay89** [comment]
[https://colab.research.google.com/git...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbDJXYkdvbmJ4NkVlbjBRVTJzZTdvM0hZN2VSUXxBQ3Jtc0tsaU9ZbUJTd2J2eHlOQ0w4a3FBOVBjNGNZNUJRbDRRanVGel8ydDlrbExIa2cwelRKUlZKWVdyQ2ZnaUVKNzNJNG5aNjRvMENNejcxZ0czNkFjc0NCQmlabVg5RHA3dzhPazU5SlplUEFrY09qTnNPWQ&q=https%3A%2F%2Fcolab.research.google.com%2Fgithub%2FNaJeongMo%2FColaboratory-Notebook-for-Ultimate-Vocal-Remover%2Fblob%2Fmain%2FVocal%2520Remover%25205_arch.ipynb&v=F2EeRok6uo4)

that's the online version I'm referring to. I saw on YouTube some settings and tried them and on pretty much all the songs I've tested, the vocals are completely removed with little to no vocal bleed or audio distortion. Here are the settings I use. 

For instrumental: 
Pretrained model: HP2-4BAND-3090_4band_ar h-500m_1.pth
(or _2)
Window size: 272
Parameter: 4band_44100.json
high_end_process: Mirroring 2
aggressiveness: 0.0
tta: enabled

**Comment by Anjok07** [comment]
I can assure you the stand alone version is better and has more features. This model HP2-4BAND-3090_4band_arch-500m_1.pth is available in the GUI, you just need to download it from the download center and add it (That particular model actually goes by a different name in the GUI - "_VR Arch Single Model v5: 7_HP2-UVR_").

**Comment by Lukasz858585** [comment]
Is it possible to install the new version of UVR on colab ?
This link that is above does not have all the options that UVR 5.5 and models have.

**Comment by codplay89** [comment]
Thank you so much man! is there gonna be any tutorials for UVR 5? id really like to know what settings are best

**Comment by codplay89** [comment]
Lukas, no I don't believe you can download it as it's just for online use. Id recommend downloading the GUI version of UVR which the dev has just stated is better and has more features.

**Comment by Lukasz858585** [comment]
What I mean is that I am using the settings that can be found at: https://mvsep.com/quality_checker/leaderboard.php Only to get the best results as many as 4 models are used and on the m1 processor it takes over 10 hours sic!

I thought to use the power of the layout that is on the google colab, but the version that is at the link you provided does not have the models and settings that are found in UVR 5.5.

Try the settings found at this address https://mvsep.com/quality_checker/leaderboard.php item (number 3)

**Comment by Anjok07** [comment]
Please download the M1 version of the application for better performance. - https://github.com/Anjok07/ultimatevocalremovergui#macos-installation

**Comment by Anjok07** [comment]
> 

There should be now since I just released an M1 specific version of UVR. It turns out the universal one was holding the M1 back by quite a bit. Please download the update and try again.

**Comment by Anjok07** [comment]
> 

There should be a bigger performance gain now since I just released an M1 specific version of UVR. It turns out the universal one was holding the M1 back by quite a bit. Please download the update and try again. See the install instructions here - https://github.com/Anjok07/ultimatevocalremovergui#macos-installation

> What do you mean by online version ? Are you referring to mvsep ? I too am testing on a mac mini with m1 processor and it takes about 10 hours to process a full CD (18 tracks) on my old i3 8100 takes 8 hours. I thought there would be a big performance gain. But still the final processing quality is really very good. Great job and a big thank you to the whole team.

**Comment by Lukasz858585** [comment]
I have just downloaded the new version dedicated for m1, I will share my experience after tests.

**Comment by Lukasz858585** [comment]
The time it takes to lay out an approximately 5 minute song in the new version for m1.
The configuration comes from the leaderboard table at mvsep.com

<img width="676" alt="Zrzut ekranu 2023-01-2 o 11 06 20" src="https://user-images.githubusercontent.com/108218963/210217590-8c1a7224-e7cb-41ad-bd16-ed85d41458de.png">

**Comment by Anjok07** [comment]
> The time it takes to lay out an approximately 5 minute song in the new version for m1.
> The configuration comes from the leaderboard table at mvsep.com
> 
> <img width="676" alt="Zrzut ekranu 2023-01-2 o 11 06 20" src="https://user-images.githubusercontent.com/108218963/210217590-8c1a7224-e7cb-41ad-bd16-ed85d41458de.png">
> 

Wow, was this the same configuration that took 10 hours before?

**Comment by Lukasz858585** [comment]
> > The time it takes to lay out an approximately 5 minute song in the new version for m1.
> > The configuration comes from the leaderboard table at mvsep.com
> > <img alt="Zrzut ekranu 2023-01-2 o 11 06 20" width="676" src="https://user-images.githubusercontent.com/108218963/210217590-8c1a7224-e7cb-41ad-bd16-ed85d41458de.png">
> 
> Wow, was this the same configuration that took 10 hours before?

Nie, wtedy kolejka zawierała 18 utworów

**Comment by Anjok07** [comment]
> > > The time it takes to lay out an approximately 5 minute song in the new version for m1.
> > > The configuration comes from the leaderboard table at mvsep.com
> > > <img alt="Zrzut ekranu 2023-01-2 o 11 06 20" width="676" src="https://user-images.githubusercontent.com/108218963/210217590-8c1a7224-e7cb-41ad-bd16-ed85d41458de.png">
> > 
> > Wow, was this the same configuration that took 10 hours before?
> 
> No, then the queue was 18 songs.

Understood. Did you notice a performance boost in comparison to the previous install?

**Comment by Lukasz858585** [comment]
Rather, I did not notice a higher performance. Apparently, 4 models used at once need very powerful hardware.

**Comment by Anjok07** [comment]
Understood. In the comparisons I did on my M1, I found conversions for the same 5-minute track with the same settings took 90 seconds longer to convert with the original (x86_64) build.

**Comment by Lukasz858585** [comment]
I also test on configuration: 
- Intel i3 8100 
- 16 gb ram 
- Nvidia Gtx 1060 3 gb.

I noticed that when I enabled the GPU conversion feature, it is only used when the ensemble uses the demucs v4 model, for other models only the CPU conversion is used. I find it strange that only this one model benefits from the GPU.

**Comment by Anjok07** [comment]
> I also test on configuration: 
> - Intel i3 8100 
> - 16 gb ram 
> - Nvidia Gtx 1060 3 gb.
> 
> I noticed that when I enabled the GPU conversion feature, it is only used when the ensemble uses the demucs v4 model, for other models only the CPU conversion is used. I find it strange that only this one model benefits from the GPU.

That's very unusual because I also have an Acer laptop with a Nvidia GTX 1060 6GB and found the gpu is utilized across all models when enabled.

**Comment by Lukasz858585** [comment]
Is there a possibility to provide you with a log file that will tell you more about it?

**Comment by Anjok07** [comment]
> Is there a possibility to provide you with a log file that will tell you more about it?

Not unless you're getting errors. I think your GPU is being used but is only able to handle a very small chunk size (since your GPU only has 3GBs)

**Comment by sslupsky** [comment]
I am running on an M1 Max MBP with 64GB of RAM.  I recently ran UVR on Taylor Swift's Love Story using the demucs 6 stem model.  I compared the processing time with GPU Conversion checked and unchecked.  There didn't appear to be a difference in the amount of time.

For comparison, Spleeter separates the track about 30 seconds.  Note that Spleeter is using a version of Tensorflow that was compiled for Metal on ARM:
https://developer.apple.com/metal/tensorflow-plugin/

For this track, the separation quality of Demucs appears to be superior to Spleeter but I do not have a way to quantify that ... it just sounds better to me with less bleed.

<img width="792" alt="Screenshot 2023-01-18 at 12 58 06 PM" src="https://user-images.githubusercontent.com/16888734/213281932-37c4ab03-369f-48eb-b702-010c29d37546.png">

<img width="792" alt="Screenshot 2023-01-18 at 12 52 52 PM" src="https://user-images.githubusercontent.com/16888734/213281965-34a985e5-edbe-4f82-bb88-c36366a3b5a5.png">

**Comment by Anjok07** [comment]
> I am running on an M1 Max MBP with 64GB of RAM. I recently ran UVR on Taylor Swift's Love Story using the demucs 6 stem model. I compared the processing time with GPU Conversion checked and unchecked. There didn't appear to be a difference in the amount of time.
> 
> For comparison, Spleeter separates the track about 30 seconds. Note that Spleeter is using a version of Tensorflow that was compiled for Metal on ARM: https://developer.apple.com/metal/tensorflow-plugin/
> 
> For this track, the separation quality of Demucs appears to be superior to Spleeter but I do not have a way to quantify that ... it just sounds better to me with less bleed.
> 
> <img alt="Screenshot 2023-01-18 at 12 58 06 PM" width="792" src="https://user-images.githubusercontent.com/16888734/213281932-37c4ab03-369f-48eb-b702-010c29d37546.png">
> 
> <img alt="Screenshot 2023-01-18 at 12 52 52 PM" width="792" src="https://user-images.githubusercontent.com/16888734/213281965-34a985e5-edbe-4f82-bb88-c36366a3b5a5.png">

Unfortunately, M1 GPU acceleration only works for the VR Architecture models at this time.

**Comment by sslupsky** [comment]
> Unfortunately, M1 GPU acceleration only works for the VR Architecture models at this time.

Ahh, ok.  I used the 1_HP-UVR model and processed the same audio track with GPU Conversion on and off.  There was about a 10x speed improvement with GPU on vs off (about 30 sec vs 6 min).
