### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by codplay89** [Anjok07/ultimatevocalremovergui#363]
OSError: cannot load library '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib': dlopen(/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib, 0x0002): tried: '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file), '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file)

If this error persists, please contact the developers with the error details.

Would you like to open the error log for more details?

Can anyone help?

**Comment by Anjok07** [comment]
Did this just start happening, or does it only happen sometimes?

**Comment by codplay89** [comment]
This just started happening. I used the vr architecture fine before but then this issue started popping up out of nowhere

**Comment by codplay89** [comment]
It happened after I downloaded some or a uvr vr architecture model

**Comment by Anjok07** [comment]
It looks like it's because of this - 

```
'/System/Volumes/Preboot/Cryptexes/OS/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib'
```

There's an security setting interfering with the libraries. You might need to reinstall the application and follow the instructions under https://github.com/Anjok07/ultimatevocalremovergui#macos-installation -> MacOS Users: Having Trouble Opening UVR?

**Comment by Anjok07** [comment]
I can verify this issue has been fixed. There was a bug in the code.

Please download the new version here (make sure to choose the installation for your architecture) - https://github.com/Anjok07/ultimatevocalremovergui#macos-installation
