### ISSUE TITLE
can author share spec file for pyinstaller to create macOS app？

### ISSUE THREAD

**Issue by blacklein** [Anjok07/ultimatevocalremovergui#364]
can author upload spec file for pyinstaller to create macOS app？

I need to compile arm64 version app for my m1 mac, thx a lot.

**Comment by Anjok07** [comment]
Does it not work with your M1? This bundle worked fine on the M1 I tested it on.

**Comment by blacklein** [comment]
the provided bundle works on m1 but startup very slow

i really wish to have arm64 version app for faster startup speed

**Comment by Anjok07** [comment]
I can release an M1 specific bundle, however, drag-n-drop will **not** work. I'm surprised the start-up time is slow. I tested the current bundle on my M1 it opens within 3-7seconds (depending on how many processes are already open). Only the very first start-up takes more time. The local M1 bundle I currently have doesn't open any faster.

**Comment by blacklein** [comment]
> I can release an M1 specific bundle, however, drag-n-drop will **not** work. I'm surprised the start-up time is slow. I tested the current bundle on my M1 and it opens within 3-7seconds (depending on how many applications are already open). Only the very first start-up takes time. The local M1 bundle I currently have doesn't open any faster.

The reason why the drag-and-drop function cannot be used is that the lib of tkdnd only has x64? If so, I sent an issue at the tkdnd project repository before and has been solved, but must to build the tkdnd of arm64 locally on M1 Mac. please refer to this issue：https://github.com/petasis/tkdnd/issues/54

**Comment by Anjok07** [comment]
> > I can release an M1 specific bundle, however, drag-n-drop will **not** work. I'm surprised the start-up time is slow. I tested the current bundle on my M1 and it opens within 3-7seconds (depending on how many applications are already open). Only the very first start-up takes time. The local M1 bundle I currently have doesn't open any faster.
> 
> The reason why the drag-and-drop function cannot be used is that the lib of tkdnd only has x64? If so, I sent an issue at the tkdnd project repository before and has been solved, but must to build the tkdnd of arm64 locally on M1 Mac. please refer to this issue：[petasis/tkdnd#54](https://github.com/petasis/tkdnd/issues/54)
> 
> In addition, the official website of ffmepg only has x64 version, and there is no arm64 version of mac. How did you solve that in M1 bundle？I have tested it in the super-resolution project. In the case of universal2 and arm64 only, the executable with Universal2 arch is 48% more time than arm64-only. So I don't think the efficiency of the Universal2 architecture on the M1 chip is equivalent to that of an arm64-only architecture. If you want to speed up this project further, ffmpeg also needs a single architecture version of arm64.

I'll put an M1 version together and release it on Sunday or Monday (depending on when I get home). Do you have the correct dnd library for arm64? Regarding FFmpeg, I'll need double check the exact version I have.

**Comment by blacklein** [comment]
[runtime-arm64.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/10327278/runtime-arm64.zip)
Above is the tkdnd of my own locally built arm64 architecture. 

```
❯ tree
.
├── bin
├── include
├── lib
│   └── tkdnd2.9.3
│       ├── libtkdnd2.9.3.dylib
│       ├── pkgIndex.tcl
│       ├── tkdnd.tcl
│       ├── tkdnd_compat.tcl
│       ├── tkdnd_generic.tcl
│       ├── tkdnd_macosx.tcl
│       ├── tkdnd_unix.tcl
│       ├── tkdnd_utils.tcl
│       └── tkdnd_windows.tcl
└── share
    └── man
        └── mann
            └── tkDND.n

7 directories, 10 files
```

**Comment by Anjok07** [comment]
Thank you for sending the dnd library! It worked with M1. I did some more testing on this and found that the universal build is not fully utilizing M1. CPU conversions are much slower on the universal build. I'll be releasing the M1 version tonight.

**Comment by Anjok07** [comment]
Everything has been updated. A new M1 stand alone version has been updated. All of the libraries are for the arm64 architecture, including FFmpeg. Please let me know if you run into any issues.

Link: https://github.com/Anjok07/ultimatevocalremovergui#macos-installation
