### ISSUE TITLE
Another problem

### ISSUE THREAD

**Issue by codplay89** [Anjok07/ultimatevocalremovergui#366]
Sorry I keep having an issue. here is the text
Last Error Received:

Process: Ensemble Mode

If this error persists, please contact the developers with the error details.

Raw Error Details:

OSError: "cannot load library '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib': dlopen(/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib, 0x0002): tried: '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file), '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file)"
Traceback Error: "
  File "UVR.py", line 4578, in process_start
  File "separate.py", line 621, in seperate
  File "separate.py", line 678, in loading_mix
  File "librosa/util/decorators.py", line 104, in inner_f
  File "librosa/core/audio.py", line 179, in load
  File "librosa/util/decorators.py", line 88, in inner_f
  File "librosa/core/audio.py", line 637, in resample
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "samplerate/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "samplerate/lowlevel.py", line 28, in <module>
"

Error Time Stamp [2022-12-31 21:58:57]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 10
window_size: 512
batch_size: 4
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: Choose Model
chunks: Auto
margin: 44100
compensate: Auto
is_denoise: False
is_invert_spec: False
mdx_voc_inst_secondary_model: No Model Selected
mdx_other_secondary_model: No Model Selected
mdx_bass_secondary_model: No Model Selected
mdx_drums_secondary_model: No Model Selected
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_gpu_conversion: False
is_primary_stem_only: False
is_secondary_stem_only: False
is_testing_audio: False
is_add_model_name: False
is_accept_any_input: False
is_task_complete: False
is_normalization: False
is_create_model_folder: False
mp3_bit_set: 320k
save_format: WAV
wav_type_set: PCM_16
help_hints_var: False
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems

ive made sure to go to terminal and enable all apps to be allowed in security settings

**Comment by codplay89** [comment]
I tried choosing a different model just using vr architecture and it's still not working. 
Last Error Received:

Process: VR Architecture

If this error persists, please contact the developers with the error details.

Raw Error Details:

OSError: "cannot load library '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib': dlopen(/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib, 0x0002): tried: '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file), '/Applications/Ultimate Vocal Remover.app/Contents/MacOS/samplerate/_samplerate_data/libsamplerate.dylib' (no such file)"
Traceback Error: "
  File "UVR.py", line 4578, in process_start
  File "separate.py", line 621, in seperate
  File "separate.py", line 678, in loading_mix
  File "librosa/util/decorators.py", line 104, in inner_f
  File "librosa/core/audio.py", line 179, in load
  File "librosa/util/decorators.py", line 88, in inner_f
  File "librosa/core/audio.py", line 637, in resample
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "samplerate/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "samplerate/lowlevel.py", line 28, in <module>
"

Error Time Stamp [2022-12-31 22:01:36]

Full Application Settings:

vr_model: 8_HP2-UVR
aggression_setting: 1
window_size: 272
batch_size: 4
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: Choose Model
chunks: Auto
margin: 44100
compensate: Auto
is_denoise: False
is_invert_spec: False
mdx_voc_inst_secondary_model: No Model Selected
mdx_other_secondary_model: No Model Selected
mdx_bass_secondary_model: No Model Selected
mdx_drums_secondary_model: No Model Selected
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_gpu_conversion: True
is_primary_stem_only: True
is_secondary_stem_only: False
is_testing_audio: False
is_add_model_name: False
is_accept_any_input: False
is_task_complete: False
is_normalization: False
is_create_model_folder: False
mp3_bit_set: 320k
save_format: MP3
wav_type_set: PCM_16
help_hints_var: False
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems

**Comment by Anjok07** [comment]
I know what's causing and will be releasing a fix in a few hours.

**Comment by Anjok07** [comment]
I can verify this issue has been fixed. 

Please download the new version here (make sure to choose the installation for your architecture) - https://github.com/Anjok07/ultimatevocalremovergui#macos-installation

**Comment by Anjok07** [comment]
I can verify this issue has been fixed. There was a bug in the code.

Please download the new version here (make sure to choose the installation for your architecture) - https://github.com/Anjok07/ultimatevocalremovergui#macos-installation
