### ISSUE TITLE
Encountered a very strange problem

### ISSUE THREAD

**Issue by penghuade** [Anjok07/ultimatevocalremovergui#369]
Encountered a very strange problem. The same model "UVR-MDX-NET Inst 3" uses UVR_ V5.4.0 Silence no current sound, use UVR_ V5.5.0 Sound attenuation but current noise.

**Comment by Anjok07** [comment]
> Encountered a very strange problem. The same model "UVR-MDX-NET Inst 3" uses UVR_ V5.4.0 Silence no current sound, use UVR_ V5.5.0 Sound attenuation but current noise.

That's because Noise Reduction was enabled by default in v5.4.0. Noise Reduction has been replaced with the "Denoise Output" option, and is not on by default.

**Comment by penghuade** [comment]
> > 遇到一个很奇怪的问题。同款“UVR-MDX-NET Inst 3”使用UVR_V5.4.0 Silence无电流声，使用UVR_V5.5.0声音衰减但有电流噪声。
> 
> 这是因为在 v5.4.0 中默认启用了降噪功能。降噪已被“降噪输出”选项取代，默认情况下不启用。
Thank you very much. The problem has been solved.

**Comment by penghuade** [comment]
> > Encountered a very strange problem. The same model "UVR-MDX-NET Inst 3" uses UVR_ V5.4.0 Silence no current sound, use UVR_ V5.5.0 Sound attenuation but current noise.
> 
> That's because Noise Reduction was enabled by default in v5.4.0. Noise Reduction has been replaced with the "Denoise Output" option, and is not on by default.

Thank you very much. The problem has been solved.
