### ISSUE TITLE
Downloading models always fails

### ISSUE THREAD

**Issue by ybhka2022** [Anjok07/ultimatevocalremovergui#371]
Anjok07, hello, thank you for your excellent work. I always fail to download the model. When the download reaches 6%, it prompts failure. Please guide me, thank you!
![微信图片_20230106161308](https://user-images.githubusercontent.com/96546197/210959299-9c7acc79-cdc3-44a6-b78c-2ef75944f3f6.jpg)

**Comment by unbadfish** [comment]
This web problem only appears in China, So I answer in zh-cn.
您应该挂个梯子上网，并且设置为一直开启，这样应该就不会有问题了🤣 
问题解决了记得关闭Issue
