### ISSUE TITLE
Denoise Output

### ISSUE THREAD

**Issue by Lukasz858585** [Anjok07/ultimatevocalremovergui#372]
I have this question does enabling this feature have a big effect on the degradation of the sound ? 
Does it somehow reduce the quality of the final file when selected in the settings.

**Comment by Anjok07** [comment]
It does not degrade the sound quality at all

**Comment by Lukasz858585** [comment]
Thank you very much for your quick reply 👍🏻.
I still have such a question about the spectral inversion option, could you say something more about it, does it give a significant difference in sound quality ?

**Comment by Anjok07** [comment]
> Thank you very much for your quick reply 👍🏻.
> I still have such a question about the spectral inversion option, could you say something more about it, does it give a significant difference in sound quality ?

It just helps eliminate some of the noise generated by those models.
