### ISSUE TITLE
Can't convert any audio file anymore

### ISSUE THREAD

**Issue by booToToM** [Anjok07/ultimatevocalremovergui#378]
Once again it no longer works, maybe that's because I tried ensemble mode recently using the recommendations in another thread but even with original settings MDX-Net..., nothing works. 24 bits FLAC, 16 bits FLAC

"

Last Error Received:

Process: MDX-Net

If this error persists, please contact the developers with the error details.

Raw Error Details:

Fail: "[ONNXRuntimeError] : 1 : FAIL : bad allocation"
Traceback Error: "
  File "UVR.py", line 4574, in process_start
  File "separate.py", line 248, in seperate
  File "separate.py", line 316, in demix_base
  File "onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
"

Error Time Stamp [2023-01-09 23:59:31]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 10
window_size: 512
batch_size: 4
crop_size: 256
is_tta: False
is_output_image: False
is_post_process: False
is_high_end_process: False
post_process_threshold: 0.2
vr_voc_inst_secondary_model: No Model Selected
vr_other_secondary_model: No Model Selected
vr_bass_secondary_model: No Model Selected
vr_drums_secondary_model: No Model Selected
vr_is_secondary_model_activate: False
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.25
shifts: 2
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: True
demucs_voc_inst_secondary_model: No Model Selected
demucs_other_secondary_model: No Model Selected
demucs_bass_secondary_model: No Model Selected
demucs_drums_secondary_model: No Model Selected
demucs_is_secondary_model_activate: False
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: No Model Selected
is_demucs_pre_proc_model_activate: False
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: UVR-MDX-NET Main
chunks: Auto
margin: 44100
compensate: Auto
is_denoise: False
is_invert_spec: False
mdx_voc_inst_secondary_model: MDX-Net: UVR-MDX-NET Main
mdx_other_secondary_model: Demucs: v4 | htdemucs
mdx_bass_secondary_model: Demucs: v4 | htdemucs
mdx_drums_secondary_model: Demucs: v4 | htdemucs
mdx_is_secondary_model_activate: False
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: False
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_gpu_conversion: False
is_primary_stem_only: False
is_secondary_stem_only: False
is_testing_audio: False
is_add_model_name: False
is_accept_any_input: False
is_task_complete: False
is_normalization: False
is_create_model_folder: False
mp3_bit_set: 320k
save_format: WAV
wav_type_set: 32-bit Float
help_hints_var: False
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems

"

It's becoming annoying.

**Comment by Anjok07** [comment]
I have a few questions:

1. Is it not working with any files at all? 
2. Did you try wav or mp3s? 
3. What platform are you on?
4. What are your machine specs?

**Comment by booToToM** [comment]
Yeah, I found out it's a problem of disk space. I'll pay attention to that before opening a new issue thread.

However, it could be interesting to have a more eloquent error message for that type of error, if that's not too much to ask.

Cheers for answering.
