### ISSUE TITLE
 A NEW MODEL THAT ALLOWS TO FILTER VERY-HIGH PITCHED OR WHISTLING VOICES

### ISSUE THREAD

**Issue by ValentyneMu** [Anjok07/ultimatevocalremovergui#39]
Hi, I just want to say that this program works great with 99% of songs, and with almost 98% of quality; way above Spleeter and others. But I have a problem with certain songs by the falsetto queens: Mariah Carey and Ariana Grande (the program doesn't filter very well the whistles parts). I would very much like you to add a model that allows us to do this job better, and thus be able to obtain 99% clean instruments. Otherwise the program is excellent. I would say that it doesn't need any more improvements apart from the one I mentioned. Thanks for reading my suggestion.

**Comment by Anjok07** [comment]
That you for the feedback! I'm hoping to have that and a few other drawbacks addressed in the next release

**Comment by ValentyneMu** [comment]
Thank you very much for answering! =D
BTW it would also be fantastic if over time you add modules to separate songs into 4 or 5 STEMS (bass, vocals, drums and others). But well that is not so important for now, at the moment I'm very happy enjoying your program that creates perfect karaokes of my favorite singers like no other software did in history! Congratulations!

**Comment by aufr33** [comment]
The tsurumeso's engine only supports 2 tracks. However, am already working on a 4 stems dataset. Even if the vocal remover doesn't change, I'll release a drums model (2 stems) next year.
