### ISSUE TITLE
macOS app icon is really LARGE

### ISSUE THREAD

**Issue by Jerry23011** [Anjok07/ultimatevocalremovergui#391]
Hi, really appreciate your work and thank you very much for compiling a Mac version that runs smoothly.

I think UVR's app icon on macOS is too large and doesn't meet [Apple's human interface standards for app icons](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/), so the icon now looks quite abrupt compared to other apps.

Could you consider making some refinements to the icon?

This is how UVR looks like compared to other apps.

<img width="683" alt="截屏2023-01-24 12 15 23" src="https://user-images.githubusercontent.com/89069957/214211086-87a105b7-078a-4e28-8a1e-267d691372fb.png">

**Comment by Anjok07** [comment]
I can fix this for the next update. Thank you for pointing that out!

**Comment by Jerry23011** [comment]
Thanks!

**Comment by bascurtiz** [comment]
<img width="1440" alt="Screenshot 2023-02-05 at 20 23 41" src="https://user-images.githubusercontent.com/34075088/216840389-4f601040-ffc1-489d-8f09-83123e58d710.png">

Based on the template of https://macosicons.com

See attachment for the .icns file @Anjok07 
[uvr5_icon_macosicons.zip](https://github.com/Anjok07/ultimatevocalremovergui/files/10611959/uvr5_icon_macosicons.zip)

**Comment by blacklein** [comment]
icon on [macosicons.com](https://macosicons.com/) is uploaded by me. that icon is made based on the original one to fit style of macOS Venture.

btw, i upload a universal tkinterdnd2 onto PyPI, may be useful for this project @Anjok07 
https://github.com/blacklein/tkinterdnd2-universal
`pip install tkinterdnd2-universal'

**Comment by ybhka2022** [comment]
> 你好，非常感谢你的工作，非常感谢你编译了一个运行流畅的 Mac 版本。
> 
> 我认为 UVR 在 macOS 上的应用程序图标太大，不符合[苹果对应用程序图标的人机界面标准](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/)，所以现在的图标与其他应用程序相比看起来相当突兀。
> 
> 你能考虑对图标做一些改进吗？
> 
> 这就是 UVR 与其他应用程序相比的样子。
> 
> <img alt="截图2023-01-24 12 15 23" width="683" src="https://user-images.githubusercontent.com/89069957/214211086-87a105b7-078a-4e28-8a1e-267d691372fb.png">
Approximately how long does it take to separate a song using a MacBook Air M1 computer?

**Comment by Jerry23011** [comment]
Depends on several factors, but on my 14' MacBook Pro equipped with M1 Pro it takes ~1 min to process a 3 min mp3.

**Comment by ybhka2022** [comment]
> 取决于几个因素，但在配备 M1 Pro 的 14 英寸 MacBook Pro 上，处理 3 分钟的 mp3 大约需要 1 分钟。

Thanks for the reply, could you please send me the configuration details of your computer?

**Comment by doinkythederp** [comment]
Here's how to change it in the meantime:

1. Download the "Ultimate Vocal Remover" icon from https://macosicons.com/
2. Open Finder, right click the UVR app and click Get Info
3. Drag the icon you downloaded and drop it on the old icon (in the upper left of the Get Info panel)

And if you're a nerd like me you can also follow these steps to make the updated icon also work while the app is running:

5. Right click the icon -> Quick Actions -> Convert Image
  a. set Format to PNG
  b. press convert and name it "GUI-Icon.png"
6. Open a new Finder window
  a. press <kbd>command</kbd>-<kbd>shift</kbd>-<kbd>G</kbd>, type `/Applications/Ultimate Vocal Remover.app/Contents/Resources/gui_data/img/GUI-Icon.png`
  b. move the converted image into the new finder window

**Comment by Jerry23011** [comment]
@Anjok07 Is it possible that we have an official implementation of this in the future?

**Comment by Anjok07** [comment]
> @Anjok07 Is it possible that we have an official implementation of this in the future?

Yes, thank you for bringing this to my attention. This will be addressed in the next patch.

**Comment by Anjok07** [comment]
This has been addressed! Please download the latest version here - https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.6

**Comment by Jerry23011** [comment]
@Anjok07 Thank you so much for addressing the issue, the new icon looks super nice!

**Comment by Anjok07** [comment]
> @Anjok07 Thank you so much for addressing the issue, the new icon looks super nice!

Thanks! BasCurtiz knocked that design out of the park. I'm sorry it took so long to finally address it. This newest version has also been heavily optimized for speed as well!
