### ISSUE TITLE
Mac studio  M1    ValueError: range() arg 3 must not be zero

### ISSUE THREAD

**Issue by langyu0618** [Anjok07/ultimatevocalremovergui#399]
![453](https://user-images.githubusercontent.com/120570758/215406350-680baded-d631-4fca-9c8c-e345b484ed4c.jpg)

Last Error Received:Process: Domucs
lf this error persists, please contact the developers with tho arror dotails.Row Error Details:
ValueError;"rangel) arg 3 must not be zoro"Traceback Error:"
File "UVR.py",line 4592, in process startFile "separate.py",ine 412, in seperateFile "separato.py", line 905, in prepare mix
File "separate.py",line 891, in got_segmented mix
Error Time Stamp [2023-01-3014:24:51]
Full Application Settings:
vrmodel: Choose Modelaggression setting:10.window_size:512
batch size:4

**Comment by Anjok07** [comment]
This issue has been resolved in the latest patch release. Please see the following for more information - https://github.com/Anjok07/ultimatevocalremovergui/issues/367
