### ISSUE TITLE
[Ubuntu] Can't start the program

### ISSUE THREAD

**Issue by Diego92Ita** [Anjok07/ultimatevocalremovergui#40]
**Describe the bug**
Invalid syntax in the code

**To Reproduce**
1. Go to folder where the program is located
2. Open terminal
3. Type "python VocalRemover.py"
**Expected behavior**
Starting of the program

**Screenshots**
![immagine](https://user-images.githubusercontent.com/63115610/103170891-275a3300-4848-11eb-9892-7869ae3ad7bd.png)

**Desktop (please complete the following information):**
 - OS: [Zorin (Ubuntu)]
 - Browser [Firefox]
 - Version [84.0]

**Additional context**
Terminal indicates the two points as error

**Comment by aufr33** [comment]
What's your python version? Try to run with python3.

**Comment by Diego92Ita** [comment]
Ok it was that. Python is already installed in linux but only version 2.7. I had to update Python and uninstall the previous version. FOR USERS THAT FIND THE SAME PROBLEM: REMEMBER TO COMPLETELY UNINSTALL PYTHON 2.7
