### ISSUE TITLE
it just doesn't open

### ISSUE THREAD

**Issue by smrtmsdns** [Anjok07/ultimatevocalremovergui#41]
I tried to install it many times and it just doesn't work for me. Could anyone help me?
Thank you.

![problem1](https://user-images.githubusercontent.com/76754233/103316748-60013480-4a21-11eb-8a98-d68d6a5f413d.png)

**Comment by DilanBoskan** [comment]
Hm, did you try googling the error message?
Starting with ImportError:

**Comment by smrtmsdns** [comment]
Thank you for your reply. 
I did, but I had no luck yet..

**Comment by DilanBoskan** [comment]
Exclude the text in brackets

**Comment by smrtmsdns** [comment]
It works now. Thank you.
I had to upgrade my pip, deleted sklearn and reinstalled it and it opened. So far so good.
