### ISSUE TITLE
Extremely slow to convert

### ISSUE THREAD

**Issue by Aeiron2** [Anjok07/ultimatevocalremovergui#43]
**Describe the bug**
Why does It takes aprox 20 min to convert a single flac file

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aufr33** [comment]
This software is very resource intensive. What is your hardware?

**Comment by DilanBoskan** [comment]
Could you give more information?
Thank you.

**Comment by Aeiron2** [comment]
Hello, I downloaded the software correctly and installed FFmpeg correctly
with the path applied the audio converter path but I still cannot convert
anything

**Comment by lesecs** [comment]
Hello.
I install everything Thing  correctly and when i open vocalremover.py, i have â black screen few seconds and cannot open the program.
Can you tell me why.
Ty

**Comment by DilanBoskan** [comment]
Any error messages that come up? Otherwise I would not be able to help. Please make sure everything is installed correctly once again

**Comment by Aeiron2** [comment]
All I'm getting is
Loading models...
Done!
File 1/1: Loading wave source...
File 1/1: Done!
File 1/1: Stft of wave source...
then in the other windows it says  10%|███████▉
                                            | 22/224 [01:04<09:45,
 2.90s/it] and moves so slow

To explain further, I installed the program and got it to run and I know it
needs another program to convert something other than WAV which is why I
downloaded FFmpeg , and since you didn't include a tutorial on how to
install it, I used this video (https://www.youtube.com/watch?v=r1AtmY-RMyQ)
 and set the path for it to
(C:\Users\MYNAME\Documents\Path\ffmpeg-2020-12-27-git-bff6fbead8-full_build\bin),
now I run the program at last and it still refuses to convert my flac files.

**Comment by lesecs** [comment]
hi
  Dont have any error. FFmpeg running very well. I work with it.
  Only vocalremover .py dont work.
  tx
  
   ---------- Message d origine ----------
   De : Dilan Boskan <notifications@github.com>
   Daté : 9 janvier 2021 à 14:43
   
   
    
   Any error messages that come up? Otherwise I would not be able to help. Please make sure everything is installed correctly once again

**Comment by lesecs** [comment]
Hi
  Eveyr things going well, only vocalremover.py dont work. Cannot open vocal remover. I have a blacke screen for few sec, and after nothing open. I have install all teh programs that we need.
  ty
  
   ---------- Message d origine ----------
   De : Aeiron2 <notifications@github.com>
   Daté : 9 janvier 2021 à 23:55
   
   
    All I'm getting is
    Loading models...
    Done!
    File 1/1: Loading wave source...
    File 1/1: Done!
    File 1/1: Stft of wave source...
    then in the other windows it says 10%|███████▉
    | 22/224 [01:04<09:45,
    2.90s/it] and moves so slow
    
    To explain further, I installed the program and got it to run and I know it
    needs another program to convert something other than WAV which is why I
    downloaded FFmpeg , and since you didn't include a tutorial on how to
    install it, I used this video (https://www.youtube.com/watch?v=r1AtmY-RMyQ)
    and set the path for it to
    (C:\Users\MYNAME\Documents\Path\ffmpeg-2020-12-27-git-bff6fbead8-full_build\bin),
    now I run the program at last and it still refuses to convert my flac files.

**Comment by DilanBoskan** [comment]
I do not know why this would happen either.
