### ISSUE TITLE
ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by korewatori** [Anjok07/ultimatevocalremovergui#44]
![image](https://user-images.githubusercontent.com/76889884/103469817-1ca21f80-4dad-11eb-934a-6284f7fc0439.png)

Got this just now while running ```pip install --no-cache-dir -r requirements.txt```. Updated pip and installed Python 3.7 (I had 3.9)
It doesn't feel like there's a clear way of resolving this in the error description, any ideas on how I could fix this?

**Comment by DilanBoskan** [comment]
There seems to be an issue with your python versions conflicting their PATHS? Try uninstalling both python versions completely, with no trace and then installing python 3.7 on your system and make sure to select "Add to PATH" in the installation problem.
Either way, this is not an issue related to the UVR, therefore I will have to close it.
