### ISSUE TITLE
CUDA 3.5 is not supported

### ISSUE THREAD

**Issue by AlExKrYt** [Anjok07/ultimatevocalremovergui#45]
**Describe the bug**

I have a Geforce GT 730 graphics card that uses CUDA version 3.5, but pyTorch does not support this version of CUDA. Is there some way to build pyTorch with this option supported?

**To Reproduce**
1. GPU Acceleration

**Expected behavior**

I would like to run hardware acceleration on my graphics card, as without it the conversion process takes 3 to 6 hours.

**Screenshots**
![photo_2021-01-07_14-50-20](https://user-images.githubusercontent.com/27852427/103895436-1ab3c580-50f9-11eb-9bef-174f84499d61.jpg)
![photo_2021-01-07_14-50-21](https://user-images.githubusercontent.com/27852427/103895441-1b4c5c00-50f9-11eb-8432-de9768512981.jpg)
![photo_2021-01-07_14-53-59](https://user-images.githubusercontent.com/27852427/103895443-1be4f280-50f9-11eb-96d1-06c6b38bb917.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 7 Ultimate
 - Browser Chrome
 - Version 87.0.4280.88
 - Python version: 3.8.7

**Comment by DilanBoskan** [comment]
Unfortunately, I do not know of any solutions to this.
