### ISSUE TITLE
 UVR-MDX-NET_Main_427?

### ISSUE THREAD

**Issue by IcicleTF** [Anjok07/ultimatevocalremovergui#453]
Hi, I've seen this model referenced several times on the mvsep leaderboards. However, I can't seem to find the model anywhere myself. Is it a model trained by an individual, or is there a repository for it somewhere?

**Comment by sabaasa** [comment]
click the "Settings" button (it's the wrench icon to the left of the conversion button)

go to the "Download Center" tab

click the button with the key icon at the bottom.

input the following into the "user code" box:

02aeb35c203ed0a9

**Comment by sabaasa** [comment]
you'll be able to download VIP models from the download center, including the 427 model you mentioned in this issue.

**Comment by IcicleTF** [comment]
Oh wow, thank you so much! Much appreciated.
