### ISSUE TITLE
Video tutorial pls, i can't install((

### ISSUE THREAD

**Issue by eugene0396** [Anjok07/ultimatevocalremovergui#46]

**Comment by CyberLykan** [comment]
A quick search on YouTube bought this up. https://www.youtube.com/watch?v=Dpu_me3xxcM

**Comment by eugene0396** [comment]
this is a stupid video, I did not understand anything what to do (

**Comment by eugene0396** [comment]
> A quick search on YouTube bought this up. https://www.youtube.com/watch?v=Dpu_me3xxcM

this is a stupid video, I did not understand anything what to do (

**Comment by CyberLykan** [comment]
> > A quick search on YouTube bought this up. https://www.youtube.com/watch?v=Dpu_me3xxcM
> 
> this is a stupid video, I did not understand anything what to do (

Well, I'm sorry, but that's the only one available right now.
