### ISSUE TITLE
Audio enhancer sister project?

### ISSUE THREAD

**Issue by rubjo** [Anjok07/ultimatevocalremovergui#471]
This is a question, not an issue, so feel free to close if inappriopriate.

We have this wonderful project, and we have a whole industry of AI tools popping up.

Image AI tools typically have an "upscale" command to add detail and definition. Would it be possible to make something similar for audio? Which, given a recording of mediocre or low quality, is able to improve the crispness/cleanness of the sound using educated guesses and deep learning?

Does something like this already exist that anyone knows of?

**Comment by Lukasz858585** [comment]
I too am curious if there is such a solution ?

**Comment by L0rdVetinari** [comment]
Hey, check out this maybe? An AI DAW: https://wavtool.com/

**Comment by rubjo** [comment]
Thanks everyone, esp for those last ones! 🙏
