### ISSUE TITLE
How can I use the same model but with different settings?

### ISSUE THREAD

**Issue by KatieBelli** [Anjok07/ultimatevocalremovergui#499]
I imported one model in MDX model folder.

When it wants me to specify the settings, I want choose those options:
![grafik](https://user-images.githubusercontent.com/109644887/231728284-c52dcf14-e0d2-47f3-8d89-6dbd0cc521a1.png)

I want to use the same model, one version with N_FFT Scale value 6144 and the other version with N_FFT Scale value 4096.

I renamed both versions differently before I opened UVR 5 and if I finished the settings for one version of the model then I can't specify the settings for the other version.

What's the correct way to make this possible?

**Comment by Anjok07** [comment]
The application is coded to make those settings static once they're set. However, you can simply clear the model cache by doing the following:

- Advanced MDX-Net Options -> Clear Auto-Set Cache

Clearing this cache will clear any user set model settings and the window to set those parameters should re-appear.

**Comment by KatieBelli** [comment]
Thank you, this is a good solution. :)
