### ISSUE TITLE
bug in conversion

### ISSUE THREAD

**Issue by Dudaldy** [Anjok07/ultimatevocalremovergui#50]
after i click to start the conversion, the program freezes,  and it stays like this forever.

**Comment by DilanBoskan** [comment]
Please give more than details than a single sentence. I am not able to help you that way.

**Comment by Dudaldy** [comment]
http://prntscr.com/wp2ivr
this happens when i start conversion

**Comment by DilanBoskan** [comment]
Thank you.
Can you try opening the python file with the console (cmd) so that I can see the error message?

**Comment by Dudaldy** [comment]
Nothing appears on the cmd.

**Comment by DilanBoskan** [comment]
Hmm, very weird that there is no error message. I have not changed anything significant.
I will close this issue for now, and if it still persists when the beta version is appended to the master simply write it in this issue again and I'll reopen.

**Comment by Dudaldy** [comment]
thx.
