### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by ProHackerJ0e** [Anjok07/ultimatevocalremovergui#51]
Hi, this problem randomly happened to me. So I don't know how to fix it. Maybe it's a bug or something ?
![Screenshot 2021-02-03 180518](https://user-images.githubusercontent.com/47935295/106734342-dfe87300-664d-11eb-8913-ae59b44f98a4.png)
![Screenshot 2021-02-03 183007](https://user-images.githubusercontent.com/47935295/106734349-e119a000-664d-11eb-9fd5-1935615740c8.png)

**Comment by DilanBoskan** [comment]
Please try:
`!pip install torch==1.4.0 torchvision==0.5.0`

**Comment by ProHackerJ0e** [comment]
Okay, I will try it later. BTW, I'm appreciate your project. : )

**Comment by ProHackerJ0e** [comment]
Well, there's have another error here : (
![Screenshot 2021-02-03 204411](https://user-images.githubusercontent.com/47935295/106748801-aff69b00-6660-11eb-8ebd-f4e6e0053040.png)
