### ISSUE TITLE
I can't open the program

### ISSUE THREAD

**Issue by Corey-Stowe** [Anjok07/ultimatevocalremovergui#52]
File "VocalRemover.py", line 64
    def open_image(path: str, size: tuple = None, keep_aspect: bool = True, rotate: int = 0) -> ImageTk.PhotoImage:
                       ^
SyntaxError: invalid syntax

**Comment by Corey-Stowe** [comment]
![Capture](https://user-images.githubusercontent.com/55090875/106894052-03302280-6721-11eb-8511-fc09b2e9b8e2.PNG)

**Comment by DilanBoskan** [comment]
Are you using the correct Python version?

**Comment by Corey-Stowe** [comment]
![image](https://user-images.githubusercontent.com/55090875/106914855-0256bb00-6738-11eb-9d4a-252de601fe5a.png)
I am using version 3.6
I will try on the latest version

**Comment by DilanBoskan** [comment]
Please use Python 3.7, Python 3.9 and above is not yet supported by the libraries used in this application.

**Comment by Corey-Stowe** [comment]
I will close the issue as I am having problems with pip python2  And pls adding without GUI methods

**Comment by DilanBoskan** [comment]
A CLI version is already ready but still in beta.
Go to the PySidePort branch to see it. It is the uvrcli.py file.
For more info, please visit our discord where all our upcoming updates and releases are announced.
Discord: https://discord.gg/P7FhQFH
