### ISSUE TITLE
Model training tutorial 

### ISSUE THREAD

**Issue by ProHackerJ0e** [Anjok07/ultimatevocalremovergui#53]
It's me Joe again. So this time I have a little request. Can you make a tutorial about how you training your own v4 model please? I can't find any video about the "vocal remove model training" on youtube or other website. Anyway, once again, I love your project.

**Comment by DilanBoskan** [comment]
Thank you for the feedback, I appreciate it.
Feel free to join the discord channel where we host current progress on the new GUI overhaul which is upcoming as well as the progress on model training!
I am certain others are willing to help you. I myself am not experienced with model training.

Discord link: https://discord.gg/P7FhQFH

**Comment by ProHackerJ0e** [comment]
Thanks a lot. >_<
