### ISSUE TITLE
Training dataset

### ISSUE THREAD

**Issue by shriyavanvari** [Anjok07/ultimatevocalremovergui#56]
Hi could you please provide the dataset that you used to train your model? 
Thank you

**Comment by enver89** [comment]
İ don't model  среда, 24 марта 2021г., 22:50 +04:00 от shriyavanvari  ***@***.*** :

**Comment by Anjok07** [comment]
Unfortunately, we cannot accommodate their request. I will providing a detailed training guide for those who would like to train their own models. This guide will consist of all of what I learned during this project.

**Comment by atom-smasher** [comment]
Where can I find some guidance to make my own models? Thanks.

**Comment by 980202006** [comment]
@Anjok07 Hi, where can I find the training guide?
