### ISSUE TITLE
Output file names swapped on vocal models.

### ISSUE THREAD

**Issue by lucassantilli** [Anjok07/ultimatevocalremovergui#58]
When using models MGM-v5-Vocal_2Band-32000-BETA1 and MGM-v5-Vocal_2Band-32000-BETA2 the outputted WAV file names are swapped, being the instruments labeled as vocals and vice-versa.

**Comment by DilanBoskan** [comment]
This is because your used models are vocal models and vocal models are not yet supported.
They will likely be officially supported in later versions.

**Comment by DilanBoskan** [comment]
I will reference the issue on a fix.

**Comment by Anjok07** [comment]
> When using models MGM-v5-Vocal_2Band-32000-BETA1 and MGM-v5-Vocal_2Band-32000-BETA2 the outputted WAV file names are swapped, being the instruments labeled as vocals and vice-versa.

While the vocal models are fully operational, the name switch issue will be addressed in the final release.

**Comment by aufr33** [comment]
Fixed. Use the **-vm** argument.
