### ISSUE TITLE
'pip' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by mariofan12ify** [Anjok07/ultimatevocalremovergui#59]
When trying to install the requirements needed in 'requirements.txt' I keep on getting this error and I don't know how to fix it.

![image](https://user-images.githubusercontent.com/35483921/114311918-d7218b00-9b2f-11eb-8162-298e499b3dcc.png)

**Comment by DilanBoskan** [comment]
Please google the error, you will find the fix online
