### ISSUE TITLE
The end of the song remains unprocessed

### ISSUE THREAD

**Issue by heaad13m** [Anjok07/ultimatevocalremovergui#6]
There's a bug in version 2.2.0. Like the command version, the last few seconds in the accompaniment are unprocessed. Hope you'll fix it soon. Thank you!

**Comment by aufr33** [comment]
This has already been fixed in version 3.0.0. But the author will need some time to update, given that the model needs to be retrained.

**Comment by eugene0396** [comment]
Hey,download video tutorial pls,after I need to open VocalRemover, I do not understand what to do, the command line opens and immediately disappears)
