### ISSUE TITLE
Couldn't find "torch==1.8.1+cu111"

### ISSUE THREAD

**Issue by mariofan12ify** [Anjok07/ultimatevocalremovergui#60]
Getting an error when trying to run this install:

`pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`

![image](https://user-images.githubusercontent.com/35483921/114314581-82cfd880-9b3a-11eb-8949-7f1636ba12dd.png)

**Comment by DilanBoskan** [comment]
Do you have Python 3.7 installed? UVR is for now only officially supported on that python version.

**Comment by mariofan12ify** [comment]
I have Python 3.8 installed.

**Comment by mariofan12ify** [comment]
Ok, so installing Python 3.7 didn't seem to work

**Comment by DilanBoskan** [comment]
Please make sure you have the 64 bit of python installed.

**Comment by deton24** [comment]
If you haven't solved your issue yet, try to run the tool remotely:
https://colab.research.google.com/drive/1aFpsQGPK5ayfzg8lS6dtpoavg3Dt5wvy?usp=sharing

Just paste to your Google Drive root directory: 
- "ultimatevocalremovergui-5.0.0" (extracted sources.zip)
- models: https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/5.0.0 to models directory
