### ISSUE TITLE
ultimatevocalremovergui in Google Colab (testing v5 beta 1 and 2 44100 models)

### ISSUE THREAD

**Issue by deton24** [Anjok07/ultimatevocalremovergui#61]
Just for your info

You can try to run the tool remotely in Google Colab:

1. Go to: https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/5.0.0
2. Extract and paste "ultimatevocalremovergui-5.0.0" (sources.zip) to your Google Drive root filder
3. Extract models to ultimatevocalremovergui-5.0.0\models directory (V5-UVR-Beta-Model-Pack.rar)
4. Upload your track to root directory of your Google Drive
5. Open Google Colab notebook: https://colab.research.google.com/drive/1aFpsQGPK5ayfzg8lS6dtpoavg3Dt5wvy?usp=sharing
6. Follow the steps in the notebook

It's based on a notebook from https://youtu.be/xyQgsWeihQM with some basic modifications to make it work on UVR.

I've tested 44100 beta 1 and 2 from V5 version of UVR, and it's worse than in model "baseline.pth" 51,8MB attached in the package with voice-removal above on my testing track. Beta 2 removes vocal a bit better, but in cost of overall sound quality. And baseline doesn't have any cut off, while betas have one on 20,5kHz.

**Comment by Anjok07** [comment]
> Just for your info
> 
> You can try to run the tool remotely in Google Colab:
> https://colab.research.google.com/drive/1aFpsQGPK5ayfzg8lS6dtpoavg3Dt5wvy?usp=sharing
> 
> Just paste to your Google Drive root directory:
> https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/5.0.0
> 
> * "ultimatevocalremovergui-5.0.0" (extracted sources.zip)
> * models (to models directory) (V5-UVR-Beta-Model-Pack.rar)
> 
> It's based on https://youtu.be/xyQgsWeihQM
> 
> I've tested 44100 beta 1 and 2 from V5 version of UVR, and it's worse than in model "baseline.pth" 51,8MB attached in the package with voice-removal above on my testing track. Beta 2 removes vocal a bit better, but in cost of overall sound quality. And baseline doesn't have any cut off while betas have on 20,5kHz.

Using the scripts from the master branch or tsurumeso's original code to run the v5 models will result in _terrible_ performance. You must use the scripts provided here - https://github.com/Anjok07/ultimatevocalremovergui/tree/v5-beta-cml

Please review the Readme on that branch for more information and instructions. The code used in the Colab link is out of date.

**Comment by deton24** [comment]
Thank you for your support!

Actually it takes like 11 minutes to process one song, but before I messed
something in the code it was like 40 seconds. Or maybe just Google
decreased computing performance when I was using the sheet. Actually at one
point it showed that GPU acceleration will be disabled and somehow then it
started to work slowly, but I doubt the acceleration was even used.

sob., 17 kwi 2021, 08:33 użytkownik Anjok07 ***@***.***>
napisał:

**Comment by aufr33** [comment]
In this case, **performance** does not mean inference speed, but _separation quality_. The newer models are definitely better than the old ones. However, I admit that Colab may not work correctly.

Please send an example file here: https://discord.com/channels/708579735583588363/708912741980569691 This will help solve the problem better.

**Comment by deton24** [comment]
Both result files have the same checksums.

Thank you for your link!

sob., 17 kwi 2021, 14:05 użytkownik aufr33 ***@***.***>
napisał:

**Comment by deton24** [comment]
I'm sorry, but this is not valid Discord invitation link.

**Comment by aufr33** [comment]
>  I'm sorry, but this is not valid Discord invitation link
Oh! Here is the correct link: https://discord.gg/C79G7CrB
