### ISSUE TITLE
Untracked Error

### ISSUE THREAD

**Issue by christinez-bmp** [Anjok07/ultimatevocalremovergui#62]
I tried to run the application as expected, selected every recommended option for the program to start converting, but I get the message below.

![image](https://user-images.githubusercontent.com/83171947/115996398-095dce80-a5ad-11eb-989c-9a84c310a311.png)

This is the setup I put together from the info.

![image](https://user-images.githubusercontent.com/83171947/115996907-272c3300-a5af-11eb-9a9c-d0dff03c24df.png)

I didn't know what to expect, and I think I did everything correctly.

I need to add something, and is that when I was setting everything up, when I was downloading the stuff from the second pip install line, I lost connection in the middle of the download, when I was back, I didnt have time to wait for it, so I just restarted it, and let it run, I don't know if its supposed to redownload, or if I have to delete something and download it again, but I think that's info that could help, i don't know the name of the file, but it's a 3055,something MB thing that got cut at around 38%.

**Comment by christinez-bmp** [comment]
Sorry if this is too rough, I just created a github account for this, And I simply don't understand any of this.

**Comment by aufr33** [comment]
pip install ffmpeg

**Comment by christinez-bmp** [comment]
I have ffmpeg installed, it still shows me the same prompt.

**Comment by jobason93** [comment]
did u install everything 
pip install python and torch from the main page

**Comment by NaJeongMo** [comment]
add ffmpeg to PATH
