### ISSUE TITLE
Ultimate Vocal Remover v5 (KAROKEE model - not work)

### ISSUE THREAD

**Issue by JsonStudio** [Anjok07/ultimatevocalremovergui#63]
Hi.

KAROKEE model (MGM-v5-KAROKEE-32000-BETA2-AGR.pth) not work. Can you check it, please?
I have added a screenshot of the error.

KAROKEE model (MGM-v5-KAROKEE-32000-BETA1.pth) not work with 2band_32000.json file (according to manual).
But this model works with:   2band_48000/3band_44100/3band_44100_mid/4band_44100

Thanks.

![111](https://user-images.githubusercontent.com/76520064/116435604-367fda80-a854-11eb-8ba4-4bce2d679730.PNG)

**Comment by aufr33** [comment]
Open the pth file with 7-zip and delete param.json.
