### ISSUE TITLE
There is a issues with the new lib for windows 

### ISSUE THREAD

**Issue by jobason93** [Anjok07/ultimatevocalremovergui#64]
The new update one yall did two days ago when you put the audio in the new batch file and u choose the number it works good until the end. it give a error but i put the old lib and it works but it comes up with a error with reverse

**Comment by Voicizer** [comment]
same here. Help

**Comment by jobason93** [comment]
The copy the old lib n putin the new one it should work until they fix it

**Comment by jobason93** [comment]
Also if doesn't handle WAV file after it process I have to turn it to mp3 again to run it another issue

**Comment by Noneedtofight** [comment]
> The copy the old lib n putin the new one it should work until they fix it

Which one is the old lib

**Comment by jobason93** [comment]
here ill attach a link for you guys to download the old lib folder

**Comment by jobason93** [comment]
https://file.io/7HjEOtS6q5aF

**Comment by aufr33** [comment]
Please update ALL files and let me know if it works now.

**Comment by jobason93** [comment]
so far it works but i am confuse with the new setting and update is there a new read me i can see?

**Comment by jobason93** [comment]
the new setting like high precison and big layer doesnt work

**Comment by jobason93** [comment]
the new setting like high precison and big layer doesnt work and there no information on what they do and it gives a error

**Comment by jobason93** [comment]
until there more information ill just keep using the old way because there alot of errors atm with the new stuff you added
