### ISSUE TITLE
Issue with the new spec_utils

### ISSUE THREAD

**Issue by Noneedtofight** [Anjok07/ultimatevocalremovergui#65]
I have everything installed correctly, from the requirements.

I drag and drop the file into the cmd batch file.

Everything goes well until the end
![issue](https://user-images.githubusercontent.com/83436448/116636563-7e3c5a00-a959-11eb-8f7d-326302047085.png)

Can someone tell me how to fix this?

**Comment by jobason93** [comment]
until they fix it copy the old lib folder and put it that folder

**Comment by jobason93** [comment]
https://anonymousfiles.io/AUa03Lqm/

**Comment by aufr33** [comment]
Fixed. Please update ALL files and let me know if it works now.

**Comment by Noneedtofight** [comment]
Thank you Aufr33, it works perfectly now!
