### ISSUE TITLE
[ENHANCEMENT]

### ISSUE THREAD

**Issue by Noneedtofight** [Anjok07/ultimatevocalremovergui#66]
I really truly love this project you have going on, it's helped me create many a acapellas and instrumentals of songs for my private use.

Recently I have seen the creators have added .bat files to process one track at a time. Is there any way you can create a bat file that would allow me to create multiple vocal/karoke instrumentals at once in one setting.

For example
python inference.py -g 0 -m 2band_32000.json -P models/MGM-v5-2Band-32000-BETA1.pth -i "INPUT"

that allows me to do one file after the other at once, rather than dragging one at a time.

**Comment by jobason93** [comment]
did you update the new version is a bat that does that

**Comment by Noneedtofight** [comment]
Yes I have updated to the latest, but the multiple file bat file doesn't work.
I drag two files and select 2 files dropped

this shows
![Untitled](https://user-images.githubusercontent.com/83436448/116948304-f0bd7a80-ac76-11eb-9a51-a165d4f99092.png)

**Comment by jobason93** [comment]
it does work check ur esemble folder

**Comment by monkeh88** [comment]
hi, is this program limited to use? cause i cant use it anymore, its saying request access

**Comment by aufr33** [comment]
Please wait for the final release. The program is still in development.

**Comment by monkeh88** [comment]
oh ok thank you

**Comment by Noneedtofight** [comment]
> Please wait for the final release. The program is still in development.

Okay, thank you for coding this.
