### ISSUE TITLE
Now it's stuck at this screen.

### ISSUE THREAD

**Issue by KillingWithlove** [Anjok07/ultimatevocalremovergui#68]
![image](https://user-images.githubusercontent.com/74067902/118379125-cb1a6480-b5d8-11eb-905a-a924bcea1c58.png)

**Comment by KillingWithlove** [comment]
after 20 min its finally showed progress and installed. but when trying to launch this error happens

![image](https://user-images.githubusercontent.com/74067902/118379471-e7b79c00-b5da-11eb-80c7-b1aed92f0f96.png)

**Comment by DilanBoskan** [comment]
Please also run the install torch command which you will find in the README.md

**Comment by KillingWithlove** [comment]
i'm sorry i missed that part thank you

**Comment by KillingWithlove** [comment]
it worked
