### ISSUE TITLE
can you help me im stuck here what is the problem? im not able to download

### ISSUE THREAD

**Issue by kingmadwik** [Anjok07/ultimatevocalremovergui#69]
![Screenshot (171)](https://user-images.githubusercontent.com/84263433/118388745-dd7db800-b643-11eb-8a28-8cf20b6f2afc.png)
![Screenshot (170)](https://user-images.githubusercontent.com/84263433/118388748-e1113f00-b643-11eb-8fc5-6d136df7dea5.png)

 my windows details, is this inefficient to handle this program?
![Screenshot 2021-05-16 124616](https://user-images.githubusercontent.com/84263433/118388903-bd022d80-b644-11eb-8798-4740a35dea73.jpg)

**Comment by KillingWithlove** [comment]
try to reinstall python 2.7 and make sure to enable path to

**Comment by DilanBoskan** [comment]
Please rather use Python 3.7 as this is the official supported Python version for UVR

**Comment by kingmadwik** [comment]
> Please rather use Python 3.7 as this is the official supported Python version for UVR

I downloaded everything from links on the original page. As far as i can understand .. the download stopped midway .. so will the half downloaded file stay in the directory ? And will it cause any problem if i redownload UVR ? I also want to clear half downloaded file.. is there anything i can do now? How to proceed?

**Comment by DilanBoskan** [comment]
It seems like you tried downloading this on a public space where there was limit on download.
Try downloading the package again from your home.
Running the download command again won't cause any issues.

**Comment by kingmadwik** [comment]
> It seems like you tried downloading this on a public space where there was limit on download.
> Try downloading the package again from your home.
> Running the download command again won't cause any issues.

i did it again and it got stuck, just in previous way but this time at 53%. so can i manually download from the given link [https://download.pytorch.org/whl/torch_stable.html]  using chrome and link it or copy it to the file or is there some method to download the 3055mb by not using command line?

**Comment by aufr33** [comment]
This will probably help: https://github.com/Anjok07/ultimatevocalremovergui/issues/72#issuecomment-850770764
