### ISSUE TITLE
vocalremover.py keeps closing

### ISSUE THREAD

**Issue by dendrobium1** [Anjok07/ultimatevocalremovergui#7]
Hi. I have followed your instructions by installing what is needed using command line, but when I try to open vocal remover.py, it closes automatically.

**Comment by aufr33** [comment]
Open a command prompt, go to the directory with the program. Run:

`python VocalRemover.py`

Then copy the error text here.

**Comment by tcafranz** [comment]
Traceback (most recent call last):
  File "VocalRemover.py", line 22, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

CMD will not let me install torch per your instructions.

**Comment by DilanBoskan** [comment]
@tcafranz 
Run this command to download torch:
`pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
