### ISSUE TITLE
Don't work Model MGM-v5-KAROKEE-32000-BETA2-AGR.pth

### ISSUE THREAD

**Issue by JsonStudio** [Anjok07/ultimatevocalremovergui#71]
Hi.
This model still doesn't work, I've tried it on different computers. Can you check this please?
Running through Windows Batch Files.

Thanks.

**Comment by JsonStudio** [comment]
![22](https://user-images.githubusercontent.com/76520064/118800134-3ea5c580-b8a8-11eb-960f-c2ed04b42e14.png)

**Comment by aufr33** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/issues/63#issuecomment-829858503

**Comment by JsonStudio** [comment]
Hi it not work..
Windows Batch Files!
