### ISSUE TITLE
I can't open UVR after using a restore point that uninstalled Python

### ISSUE THREAD

**Issue by lNoZl** [Anjok07/ultimatevocalremovergui#72]
**Describe the bug**
I downloaded and followed the UVR installation steps and everything worked great. Some time later I had to use a Windows restore point, which was from before I installed UVR, so I uninstalled Python from my system and when I reinstalled it, it no longer worked even though when I entered the commands:
pip install --no-cache-dir -r requirements.txt
pip install torch == 1.8.1 + cu111 torchvision == 0.9.1 + cu111 torchaudio === 0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
The system detected that everything was downloaded.
**To Reproduce**
1. Selected settings: 'python VocalRemover.py'
2. See error
ImportError: numpy.core.multiarray failed to import
Traceback (most recent call last):
  File "VocalRemover.py", line 25, in <module>
    import inference_v2
  File "C: \ Users \ angel \ Documents \ UVR_V4GUI_All_IN_ONE_12_10 \ UVR-V4GUI \ inference_v2.py", line 4, in <module>
    import cv2
  File "C: \ Users \ angel \ AppData \ Local \ Programs \ Python \ Python37 \ lib \ site-packages \ cv2 \ __ init__.py", line 5, in <module>
    from .cv2 import *
ImportError: numpy.core.multiarray failed to import
**Expected behavior**
I expected the program to open and work normally
**Screenshots**
![image](https://user-images.githubusercontent.com/85001648/120054830-f436ee00-bff7-11eb-98f8-1eff3f0f34dc.png)
![image](https://user-images.githubusercontent.com/85001648/120054842-13358000-bff8-11eb-8502-3296c3fb3eb4.png)
![image](https://user-images.githubusercontent.com/85001648/120054852-1e88ab80-bff8-11eb-9ef8-810cd95bca97.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 10

**Additional context**

**Comment by aufr33** [comment]
Try:

pip install torch==1.6.0+cu101 torchvision==0.8.2+cu110 numpy>=1.20.2 torchaudio==0.8.1 librosa==0.8.0 -f https://download.pytorch.org/whl/torch_stable.html

And use python**3**.

**Comment by lNoZl** [comment]
I tried the command, and I got this warning in red.
![image](https://user-images.githubusercontent.com/85001648/120115259-80582b00-c148-11eb-933c-885dbb2fae30.png)

When I use the command:
 python VocalRemover.py
I get this:
![image](https://user-images.githubusercontent.com/85001648/120115287-a8e02500-c148-11eb-96e6-1d23ae9bc021.png)

**Comment by lNoZl** [comment]
After what was written above, I have reinstalled Python because I had two versions of it installed on my system: (Python 3.7.0 and 3.9.5). I uninstalled both and reinstalled Python 3.9.5. Then I used the command to install UVR found in the guide:
 pip install --no-cache-dir -r requirements.txt
>> pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
And it was installed normally
![image](https://user-images.githubusercontent.com/85001648/120116012-aaf7b300-c14b-11eb-9442-ac47a1ae5f23.png)
Although some words appeared in red.
![image](https://user-images.githubusercontent.com/85001648/120116032-c6fb5480-c14b-11eb-87c2-17a5e1e903f6.png)
But more things kept downloading
![image](https://user-images.githubusercontent.com/85001648/120116039-d8446100-c14b-11eb-90cb-bff874fbdf57.png)
Finally, I used the code:
python VocalRemover.py
And this message appeared:
![image](https://user-images.githubusercontent.com/85001648/120116080-05910f00-c14c-11eb-9018-d1dfe0d052ee.png)
I appreciate the help you have offered me so far

**Comment by DilanBoskan** [comment]
Python 3.7 is the officially supported version for UVR. Consider switching your version.
