### ISSUE TITLE
UVR does not open after reinstalling Python 3.9.5

### ISSUE THREAD

**Issue by lNoZl** [Anjok07/ultimatevocalremovergui#75]
**Describe the bug**
When I introduce the command:
python VocalRemover.py
UVR does not work and sends me an error message.

**To Reproduce**
I have reinstalled Python because I had two versions of it installed on my system: (Python 3.7.0 and 3.9.5). I uninstalled both and reinstalled Python 3.9.5. Then I used the command to install UVR found in the guide:
 pip install --no-cache-dir -r requirements.txt
>> pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
And it was installed normally
![image](https://user-images.githubusercontent.com/85001648/120116012-aaf7b300-c14b-11eb-9442-ac47a1ae5f23.png)
Although some words appeared in red.
![image](https://user-images.githubusercontent.com/85001648/120116032-c6fb5480-c14b-11eb-87c2-17a5e1e903f6.png)
But more things kept downloading
![image](https://user-images.githubusercontent.com/85001648/120116039-d8446100-c14b-11eb-90cb-bff874fbdf57.png)
Finally, I used the code:
python VocalRemover.py
And this message appeared:
![image](https://user-images.githubusercontent.com/85001648/120116080-05910f00-c14c-11eb-9018-d1dfe0d052ee.png)
**Expected behavior**
I expected the application to work normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/85001648/120116012-aaf7b300-c14b-11eb-9442-ac47a1ae5f23.png)
![image](https://user-images.githubusercontent.com/85001648/120116032-c6fb5480-c14b-11eb-87c2-17a5e1e903f6.png)
![image](https://user-images.githubusercontent.com/85001648/120116039-d8446100-c14b-11eb-90cb-bff874fbdf57.png)
![image](https://user-images.githubusercontent.com/85001648/120116080-05910f00-c14c-11eb-9018-d1dfe0d052ee.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Opera GX
 - Version: 10

**Additional context**

**Comment by KimberleyJensen** [comment]
Use python 3.7 https://www.python.org/ftp/python/3.7.0/python-3.7.0-amd64.exe

**Comment by lNoZl** [comment]
> Use python 3.7 https://www.python.org/ftp/python/3.7.0/python-3.7.0-amd64.exe
Now I am using Python 3.7 and I get this error message
![image](https://user-images.githubusercontent.com/85001648/120699223-bf062200-c475-11eb-9552-cd9bf90adc96.png)

**Comment by aufr33** [comment]
Try pip3 and python3.
