### ISSUE TITLE
it says i don't have a cuda gpu

### ISSUE THREAD

**Issue by POLTERGEIST322** [Anjok07/ultimatevocalremovergui#77]
**Describe the bug**
when i convert the song
the command line says i don't have a cuda gpu
[](url)
**To [`Reproduce**`](url)
1. Selected settings: 'python VocalRemover.py'
2. See error
    D:\python37\lib\site-packages\torch\cuda\__init__.py:52: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
    D:\python37\lib\site-packages\librosa\core\audio.py:161: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn('PySoundFile failed. Trying audioread instead.')

**Expected   @#behavior**
i expect the program can detect my cuda gpu since i do have a cuda gpu and it worked perfectly fine before

**Screenshots**

!(https://user-images.githubusercontent.com/73595271/121000521-e5e98e80-c7bc-11eb-96ed-4b04e592a5bc.PNG)

> url 

)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge
 - Version 91.0

**Additional context**

**Comment by aufr33** [comment]
>     * Browser Edge

Unfortunately, this information is irrelevant. Please specify:

- GPU model or microarchitecture
- CUDA version
- NVIDIA Driver version
- Pytorch version

**Comment by POLTERGEIST322** [comment]
my pytorch version is the same version you provided
(https://user-images.githubusercontent.com/73595271/121099586-b4a7a780-c82a-11eb-8430-5af4fe7b4713.PNG)

**Comment by DilanBoskan** [comment]
Do you have a CUDA supporting NVIDIA graphics card?
