### ISSUE TITLE
module 'sys' has no attribute 'setcheckitnerval'

### ISSUE THREAD

**Issue by finsbar** [Anjok07/ultimatevocalremovergui#78]
I cannot get this software to work whatsoever - I know little about Python, so I presume I may have messed something up in the installation process? Thank you. This happens with any combination of options whatsoever.

![image](https://user-images.githubusercontent.com/82964969/121269833-6a6d0780-c8b8-11eb-8123-321f52a14d9e.png)

**Comment by DilanBoskan** [comment]
We are currently on heavy works on the new and improved v5 for UVR as well as a completely revamped GUI. As we no longer support the GUI for v4, please stay tuned for the new release.

For more info, or help on any other questions, feel free to join the audio seperation discord! https://discord.gg/P7FhQFH
