### ISSUE TITLE
Hi, how can I update the program without reinstalling from 4.00 to 4.01 ?

### ISSUE THREAD

**Issue by eugene0396** [Anjok07/ultimatevocalremovergui#80]
**To Reproduce**
On which installation step did you encounter the issue.

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by DilanBoskan** [comment]
This is not possible as of yet. For a new version you will need to reinstall the whole application.
