### ISSUE TITLE
Issue on recent new update 2 hours ago 

### ISSUE THREAD

**Issue by jobason93** [Anjok07/ultimatevocalremovergui#82]
h. MGM-v5-MIDSIDE-44100-BETA1
i. MGM-v5-MIDSIDE-44100-BETA2
j. MGM-v5-Vocal_2Band-32000-BETA1
k. MGM-v5-Vocal_2Band-32000-BETA2
l. LOFI_2band-1_33966KB
m. LOFI_2band-2_33966KB
n. HighPrecison_4band_1
o. HighPrecison_4band_2
p. NewLayer_4band_1.pth
q. NewLayer_4band_2.pth
r. NewLayer_4band_3.pth
s. Ensemble All Models (14 Models) - Final Outputs Save to Ensembled Folder!
Type the letter associated with the option you choose and hit 'Enter': s
Include Deep Vocal Extraction Instrumental? [Y/N]: n
Ensemble All Models
loading MGM-v5-4Band-44100-BETA1... done
C:\Users\jobas\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
loading & stft of wave source... Traceback (most recent call last):
  File "ensemble_inference.py", line 385, in <module>
    main()
  File "ensemble_inference.py", line 250, in main
    X_spec_s[d] = spec_utils.wave_to_spectrogram(X_wave[d], bp['hl'], bp['n_fft'], mp, True)
  File "C:\Users\jobas\OneDrive\Desktop\Desktop\Documents\Vocal Remover Update\lib\spec_utils.py", line 35, in wave_to_spectrogram
    elif mp.param['mid_side_b']:
KeyError: 'mid_side_b'
--------------------------------
Press any key to continue . . .

**Comment by jobason93** [comment]
all the recent update on you did the last 4 hours or so have alot of error it rewind the music and error

**Comment by aufr33** [comment]
Fixed
