### ISSUE TITLE
Ultimate Vocal Removal error

### ISSUE THREAD

**Issue by Bilbofett** [Anjok07/ultimatevocalremovergui#825]
Last Error Received:

Process: Ensemble Mode

If this error persists, please contact the developers with the error details.

Raw Error Details:

AttributeError: "'SeperateMDX' object has no attribute 'trim'"
Traceback Error: "
  File "UVR.py", line 6576, in process_start
  File "separate.py", line 819, in seperate
  File "separate.py", line 1212, in process_secondary_model
  File "separate.py", line 475, in seperate
  File "separate.py", line 518, in demix
"

Error Time Stamp [2023-09-27 20:12:34]

Full Application Settings:

vr_model: Choose Model
aggression_setting: 5
window_size: 320
mdx_segment_size: 384
batch_size: Default
crop_size: 256
is_tta: True
is_output_image: False
is_post_process: True
is_high_end_process: True
post_process_threshold: 0.1
vr_voc_inst_secondary_model: VR Arc: 1_HP-UVR
vr_other_secondary_model: MDX-Net: kuielab_a_other
vr_bass_secondary_model: MDX-Net: kuielab_a_bass
vr_drums_secondary_model: Demucs: v4 | htdemucs
vr_is_secondary_model_activate: True
vr_voc_inst_secondary_model_scale: 0.9
vr_other_secondary_model_scale: 0.7
vr_bass_secondary_model_scale: 0.5
vr_drums_secondary_model_scale: 0.5
demucs_model: Choose Model
segment: Default
overlap: 0.75
overlap_mdx: 0.75
overlap_mdx23: 6
shifts: 1
chunks_demucs: Auto
margin_demucs: 44100
is_chunk_demucs: False
is_chunk_mdxnet: False
is_primary_stem_only_Demucs: False
is_secondary_stem_only_Demucs: False
is_split_mode: True
is_demucs_combine_stems: False
is_mdx23_combine_stems: False
demucs_voc_inst_secondary_model: MDX-Net: MDX23C_D1581.ckpt
demucs_other_secondary_model: Demucs: v4 | htdemucs
demucs_bass_secondary_model: MDX-Net: kuielab_a_bass
demucs_drums_secondary_model: Demucs: v4 | hdemucs_mmi
demucs_is_secondary_model_activate: True
demucs_voc_inst_secondary_model_scale: 0.9
demucs_other_secondary_model_scale: 0.7
demucs_bass_secondary_model_scale: 0.5
demucs_drums_secondary_model_scale: 0.5
demucs_pre_proc_model: MDX-Net: UVR-MDX-NET Inst HQ 3
is_demucs_pre_proc_model_activate: True
is_demucs_pre_proc_model_inst_mix: False
mdx_net_model: Choose Model
chunks: Auto
margin: 44100
compensate: Auto
denoise_option: Denoise Model
is_match_frequency_pitch: True
phase_option: Automatic
phase_shifts: None
is_save_align: False
is_match_silence: True
is_spec_match: False
is_mdx_c_seg_def: True
is_invert_spec: True
is_deverb_vocals: False
deverb_vocal_opt: Main Vocals Only
voc_split_save_opt: Lead Only
is_mixer_mode: False
mdx_batch_size: Default
mdx_voc_inst_secondary_model: MDX-Net: UVR-MDX-NET_Main_438
mdx_other_secondary_model: Demucs: v4 | htdemucs_6s
mdx_bass_secondary_model: MDX-Net: kuielab_a_bass
mdx_drums_secondary_model: Demucs: v4 | htdemucs_ft
mdx_is_secondary_model_activate: True
mdx_voc_inst_secondary_model_scale: 0.9
mdx_other_secondary_model_scale: 0.7
mdx_bass_secondary_model_scale: 0.5
mdx_drums_secondary_model_scale: 0.5
is_save_all_outputs_ensemble: True
is_append_ensemble_name: True
chosen_audio_tool: Manual Ensemble
choose_algorithm: Min Spec
time_stretch_rate: 2.0
pitch_rate: 2.0
is_time_correction: True
is_gpu_conversion: True
is_primary_stem_only: False
is_secondary_stem_only: False
is_testing_audio: False
is_auto_update_model_params: True
is_add_model_name: False
is_accept_any_input: True
is_task_complete: True
is_normalization: False
is_wav_ensemble: False
is_create_model_folder: False
mp3_bit_set: 320k
semitone_shift: 0
save_format: WAV
wav_type_set: 32-bit Float
help_hints_var: True
set_vocal_splitter: No Model Selected
is_set_vocal_splitter: False
is_save_inst_set_vocal_splitter: False
model_sample_mode: False
model_sample_mode_duration: 30
demucs_stems: All Stems
mdx_stems: All Stems

**Comment by Anjok07** [comment]
I found the bug. A new patch will be available within the next few hours to address this bug and a few others that were reported to me. Thank you!

**Comment by Bilbofett** [comment]
Thanks, I'll keep an eye on the links page for when it goes up, I'm anxious
to see if this will work.
Any tips on a mostly instrumental stems track downmix I want to make? I'd
like to split up a stereo source into multiple instrumental tracks (no
vocals) for remixing purposes.
I really don't know what I'm doing but trying alot of experimentation. I
have no idea which models would be best for this.
Also.. I played with some of the overlap and N_FFT scale (model defaults)
and what used to take an average of.. 10-15 mins per 3 minute song is now
taking up to 7-8 hours?! I'd like to go back, but really want the most
quality I can possibly have.

Lastly, I noticed it took some stereo-sounding keyboards in my song and
made them mono.. is there any trick to preserve the stereo imagery.. or is
this just the way it is for now w/ AI?
Thanks for all your time and help friend!! AI track separation is exciting!
:)

P.S. I heard George Martin's son Giles used an AI "de-mix" software to take
mono (or was it stereo 2-track?) mixes of old Beatles songs, somehow
extracted multitrack stems, then remixed the songs as if there was perfect
separation of each instrument.. guitar, piano, drums, vocals? Pretty
impressive. I'd imagine it was something much more powerful than UVR? 🤣

Here's a bit of that:
https://www.musicradar.com/news/the-beatles-revolver-stereo-remix-ai-tech
https://www.abbeyroad.com/de-mix
https://youtu.be/KsYxTuX5wC4

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Anjok07** [comment]
This has been fixed. Please download the latest patch. Thank you!

**Comment by Bilbofett** [comment]
Awesome, thanks for the update!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
