### ISSUE TITLE
UVR-VR Architecture-De-Echo-Aggressive fields

### ISSUE THREAD

**Issue by KedarCZ** [Anjok07/ultimatevocalremovergui#827]
Hello, this error is very simple. If you use VR Architecture and the De-Echo-Aggressive model, the "Echo Only" and "No Echo Only" fields are swapped. 
So if you use "Echo Only" you will get "No Echo Only" output and vice versa. 
I'm on v5.6

**Comment by Anjok07** [comment]
This has been fixed. Thank you for the head-up!
