### ISSUE TITLE
i got a issue with lib spec new updated

### ISSUE THREAD

**Issue by jobason93** [Anjok07/ultimatevocalremovergui#83]
Type the letter associated with the option you choose and hit 'Enter': s
Include Deep Vocal Extraction Instrumental? [Y/N]: n
Ensemble All Models
loading MGM-v5-4Band-44100-BETA1... done
C:\Users\jobas\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\audio.py:162: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
loading & stft of wave source... Traceback (most recent call last):
  File "ensemble_inference.py", line 375, in <module>
    main()
  File "ensemble_inference.py", line 240, in main
    X_spec_s[d] = spec_utils.wave_to_spectrogram_mt(X_wave[d], bp['hl'], bp['n_fft'], mp.param['mid_side'], mp.param['reverse'])
AttributeError: module 'lib.spec_utils' has no attribute 'wave_to_spectrogram_mt'
--------------------------------
Press any key to continue . . .

**Comment by aufr33** [comment]
You need to update all scripts, not just spec_utils.py.
