### ISSUE TITLE
**MAC SONOMA USERS** - Application not receiving clicks on Mac Samona 14.0 (23A344)

### ISSUE THREAD

**Issue by majaabal** [Anjok07/ultimatevocalremovergui#840]
Hello,

I've recently updated my Mac to the latest Samona 14.0 version and have observed an issue with the application's responsiveness to clicks. It appears that I need to click on buttons multiple times before they respond as intended.

For your reference, my system is equipped with an Intel processor and an AMD graphics card.

I kindly request your prompt attention to address this matter.

Thank you

**Comment by Anjok07** [comment]
This is a known issue and I'm working on a fix at this time.

**Comment by Anjok07** [comment]
After doing some research, it's a miracle UVR opens on Sonoma at all. You might want to consider downgrading back to Ventura until a viable fix is found. Currently, this appears to be affecting all Tkinter based application running on Sonoma.

**Comment by avichou** [comment]
yeah sonoma seems to have messed the GUI super badly xD . I'd wait for a fix 

do you not have a non-gui version ? something with terminal with less chances of being bugged the fuck out by apple bullshit 

> After doing some research, it's a miracle UVR opens on Sonoma at all. You might want to consider one of the following options -
> 
> 1. Click the buttons while moving your mouse.
> 
> Or
> 
> 2. Downgrade back to Ventura until a viable fix is found.
> 
> Currently, this appears to be affecting all Tkinter based applications running on Sonoma.

**Comment by majaabal** [comment]
I am using GUI version

**Comment by avichou** [comment]
> I am using GUI version

i was asking the owner :)

**Comment by dennis777** [comment]
Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:

https://github.com/Anjok07/ultimatevocalremovergui/assets/25965937/b132e8ad-5468-42e6-bd93-ff9bbc38ed4e

**Comment by avichou** [comment]
> Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> 
>  Screen.Recording.2023-10-03.at.09.37.38.mov

yeah it's rly terrible how sonoma destroyed it lol, but indeed it works thank you !

**Comment by avichou** [comment]
> Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> 
>  Screen.Recording.2023-10-03.at.09.37.38.mov

my issue is that UVR does not open AT ALL , lol, lemme show you . it opens only the first time after install, but if I quit the app it just stops opening ever again

https://github.com/Anjok07/ultimatevocalremovergui/assets/86660671/80710fd4-e7f2-4d43-b4f6-869738f6a3d2

**Comment by dennis777** [comment]
Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue

**Comment by avichou** [comment]
> Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue 

Hmm let me try to safe boot and see if I can isolate the issue to some third party app perhaps 

Otherwise ; MacBook air M1 16gb , sonoma 14 stable public release , install the app, open it , close it , then try to reopen it

**Comment by Anjok07** [comment]
If you move your mouse as you click it will register the click every time.

**Comment by Anjok07** [comment]
> Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> 
>  Screen.Recording.2023-10-03.at.09.37.38.mov

If you move your mouse as you click it will register the click every time.

**Comment by dennis777** [comment]
> > Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> > Screen.Recording.2023-10-03.at.09.37.38.mov
> 
> If you move your mouse as you click it will register the click every time.

Little tricky on a trackpad 😅 but yes I guess this is more reliable :)

**Comment by Anjok07** [comment]
In the next 2 days, I'll release another update with a workaround fix. I made it so you can use either the middle mouse button (the scroll button) or the space bar to register a left-click. Until updates are made to Sonoma, I'm not sure there's anything else I can do yet.

**Comment by avichou** [comment]
> Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue

hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue 

look at this 

https://github.com/Anjok07/ultimatevocalremovergui/assets/86660671/f5555bf4-258b-4305-a40d-1af14ebe02a8



speaking of do you know of a freaking app to reduce file size, for example make video40mb.mp4 become video10mb.mp4 ? i only find online websites for that but no offline app

**Comment by kaixxx** [comment]
Bugtracker for what seems to be the underlying issue in tkinter or even tcl/tk: https://github.com/python/cpython/issues/110218

People over there report that updating tcl/tk might solve the issue. I cannot test this myself, but it looks promising.

**Comment by dennis777** [comment]
> > Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue
> 
> hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue
> 
> look at this
> 
>  Enregistrement.de.l.ecran.2023-10-04.a.12.46.30.mp4 
> 
> speaking of do you know of a freaking app to reduce file size, for example make video40mb.mp4 become video10mb.mp4 ? i only find online websites for that but no offline app


interesting I see. I don’t use better touch tool myself but I’ve could assume there’s some conflict between better touch and tkinter.

And in terms of a video compressor I do not. I’ve been looking to create one myself sometime cause yeah macOS screen recordings are massive files and I’ve also never found an offline app to do it

**Comment by avichou** [comment]
> > > Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue
> > 
> > hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue
> > 
> > look at this
> > 
> >  Enregistrement.de.l.ecran.2023-10-04.a.12.46.30.mp4 
> > 
> > speaking of do you know of a freaking app to reduce file size, for example make video40mb.mp4 become video10mb.mp4 ? i only find online websites for that but no offline app
> 
> 
> interesting I see. I don’t use better touch tool myself but I’ve could assume there’s some conflict between better touch and tkinter.
> 
> And in terms of a video compressor I do not. I’ve been looking to create one myself sometime cause yeah macOS screen recordings are massive files and I’ve also never found an offline app to do it

Probably yeah ...idk if a fix for that can be expected

Uhuh yeah exactly, imma follow you in case you drop some compressor :)

**Comment by doinkythederp** [comment]
> > Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue
> 
> hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue
> 
> look at this
> 
>  Enregistrement.de.l.ecran.2023-10-04.a.12.46.30.mp4 
> speaking of do you know of a freaking app to reduce file size, for example make video40mb.mp4 become video10mb.mp4 ? i only find online websites for that but no offline app

Would recommend https://handbrake.fr. I hope this Tkinter issue gets fixed!

**Comment by avichou** [comment]
> > > Interesting, how can I reproduce it? I would like to investigate it, that seems like a separate issue
> > 
> > hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue
> > 
> > look at this
> > 
> >  Enregistrement.de.l.ecran.2023-10-04.a.12.46.30.mp4 
> > speaking of do you know of a freaking app to reduce file size, for example make video40mb.mp4 become video10mb.mp4 ? i only find online websites for that but no offline app
> 
> Would recommend https://handbrake.fr. I hope this Tkinter issue gets fixed!

I hope too ! 

Handbrake doesn't allow you to set a predefined file size sadly...only websites seem to allow you to do that 

You can't set your wished file size like "compress this to 10mb"

**Comment by samuelhe864** [comment]
> Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> 
>  Screen.Recording.2023-10-03.at.09.37.38.mov

I think I may have found a better workaround when using the internal trackpad. Simply press the button for a long time and press it hard until its color changes, release the press and UVR would receive the "click".

Like this

https://github.com/Anjok07/ultimatevocalremovergui/assets/104753697/cbfe24d3-ad7d-4d84-8128-2ba382dd54d0

**Comment by djbrettb** [comment]
> hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue

Confirming this. The good news is you can disable BetterSnapTool per-application (with UVR in focus, click BST's menu bar icon and select 'Disable BetterSnapTool for current application').

With that issue now out of the way it seems to be running fine on Sonoma.

**Comment by doinkythederp** [comment]
I don't use Better Touch Tool but I'm still getting the mouse issues, so I'm not convinced that's the issue.On Oct 4, 2023, at 9:08 PM, djbrettb ***@***.***> wrote:﻿

hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue

Confirming this. The good news is you can disable BetterSnapTool per-application (with UVR in focus, click BST's menu bar icon and select 'Disable BetterSnapTool for current application').
With that issue now out of the way it seems to be running fine on Sonoma.

**Comment by chriscousin** [comment]
I have the same issue here. No matter it Better Touch Tool is activated or not. Thanks for your help.

**Comment by Anjok07** [comment]
I found a resolution to this issue! Be on the look out for a patch update later this evening.

**Comment by avichou** [comment]
> I don't use Better Touch Tool but I'm still getting the mouse issues, so I'm not convinced that's the issue.On Oct 4, 2023, at 9:08 PM, djbrettb ***@***.***> wrote:﻿ hey. better touch tool seems to be the issue , not sure how and why though . but look at this. with better touch tool closed, there is no issue Confirming this. The good news is you can disable BetterSnapTool per-application (with UVR in focus, click BST's menu bar icon and select 'Disable BetterSnapTool for current application'). With that issue now out of the way it seems to be running fine on Sonoma. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

so i've just tried it , disabling BTT altogether for UVR, but i still cannot open UVR if btt is working 

i mean if i open uvr then open btt it works 

however if i open btt , close uvr, then try to re-open uvr, it wont work 

you say it's okay for you ?

**Comment by avichou** [comment]
> Chiming in again to hopefully clear up any confusion - I'm referring specifically to BetterSnapTool, a tool for managing window positions. I don't use BetterTouchTool or have it installed.
> 
> It makes sense that BetterSnapTool, a tool used for manipulating the macOS GUI, would have an impact on the GUI of this application.

Gotcha . It's interesting that disabling BTT entirely for UVR still doesn't allow me to have UVR to show up , whilst doing so with better snap tool does (with your config at least and imma test it to see if it's the same for me cuz I suspect there might be something going on with my Mac. What's your config (device,macOS version)

**Comment by djbrettb** [comment]
> Gotcha . It's interesting that disabling BTT entirely for UVR still doesn't allow me to have UVR to show up , whilst doing so with better snap tool does (with your config at least and imma test it to see if it's the same for me cuz I suspect there might be something going on with my Mac. What's your config (device,macOS version)

M1 Air, 16GB, Sonoma 14.1 DB2.

FWIW, the click-not-registering issue occurs for me both when using an external monitor and when using the built-in display. And it doesn't matter whether I'm using a mouse or the trackpad.

**Comment by Anjok07** [comment]
This issue has been resolved. Please update to UVR_Patch_10_6_23_4_27.

**Comment by kaixxx** [comment]
@Anjok07 How did you solve the issue? I'm facing the same problem with my app and would like to know. 
I've looked at your last commits but don't find much changes regarding the frontend or tkinter.
Thanks

**Comment by Anjok07** [comment]
> @Anjok07 How did you solve the issue? I'm facing the same problem with my app and would like to know. 
> I've looked at your last commits but don't find much changes regarding the frontend or tkinter.
> Thanks

I updated tk/tcl to version from 8.6.12 to 8.6.13 and reinstalled Python, both via homebrew. Then I recompiled UVR with those updates.

**Comment by kaixxx** [comment]
Ah, nice, I'll try that. Do you also use pyinstaller for compilation?

**Comment by gernophil** [comment]
> > @Anjok07 How did you solve the issue? I'm facing the same problem with my app and would like to know. 
> > I've looked at your last commits but don't find much changes regarding the frontend or tkinter.
> > Thanks
> 
> I updated tk/tcl from 8.6.12 to 8.6.13 and reinstalled Python, both via homebrew. Then I recompiled UVR with those updates.

Any way to accomplish this with the ”original“ Python from python.org?

**Comment by Anjok07** [comment]
> Ah, nice, I'll try that. Do you also use pyinstaller for compilation? 

Yes I do

**Comment by majaabal** [comment]
This issue is fixed, download the new version - 

https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.6/Ultimate_Vocal_Remover_v5_6_MacOS_x86_64.dmg

**Comment by majaabal** [comment]
Fixed, thanks!

**Comment by f22daniel** [comment]
> Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> 
>  Screen.Recording.2023-10-03.at.09.37.38.mov

Can you please navigate us to the settings you have in the video? Thank you.

**Comment by dennis777** [comment]
> > Im using macOS Sonoma and just wanted to let y'all know it's an ongoing issue with Tkinter GUI based applications but a simple workaround for now is you just need to keep clicking and it'll eventually register the click. See below:
> 
> > 
> 
> >  Screen.Recording.2023-10-03.at.09.37.38.mov
> 
> 
> 
> Can you please navigate us to the settings you have in the video? Thank you.

Hey what do you mean? Can you be more specific?
