### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by Mixerrog** [Anjok07/ultimatevocalremovergui#86]
**To Reproduce**
On which installation step did you encounter the issue.

**Screenshots**
Add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Additional context**

**Comment by Mixerrog** [comment]
After install & when I run the "python VocalRemover.py" , I get this error message "ModuleNotFoundError: No module named 'cv2'"

Thanks for your help, Rog

**Comment by KimberleyJensen** [comment]
run this command

pip3 install opencv-python

**Comment by Mixerrog** [comment]
I did finally get it running yesterday running "pip3 install opencv-python" + one other install that an error showed up for after this but I now can not get the shortcut to work yet. I have to go through a Anaconda command promp, add the folder that UVR-V4GUI is in, then the UVR-V4GUI & finally the 
command "python VocalRemover.py" to bring up the GUI so I can run the program. The "VocalRemover.py" inside UVR-V4GUI only brings up a very short time all black dos box ? 

Even changing the line inside the UVR-V4GUI folder to "python VocalRemover.py" will not bring up the GUI interface.  

Also, is their anyway to get a Radeon RX-550 GPU to work with this to speed it up?

Thanks for your help on this, Rog

**Comment by DilanBoskan** [comment]
Only NVIDIA GPUs that support CUDA are able to use the GPU acceleration.

**Comment by DilanBoskan** [comment]
For the issues you described, if those are still present after UVR V5 released for the GUI, which is heavily in the works currently, please do not hesitate to create a seperate issue with all the steps to reproduce the issue.
Thank you!

**Comment by Mixerrog** [comment]
Dilan,

Great to hear you are working on a V5 version & hope it will do some 
backing vocal separations possibly?

Rog

**Comment by DilanBoskan** [comment]
I apologize for the incomvenience you have had to face. Support for v4 has dropped as there are currently heavy works for the revamped GUI for v5. This GUI will be much more user-friendly and hopefulls easier to set up as well.

**Comment by Mixerrog** [comment]
Dilan,

No problem. Have you looked at using Open-Unmix UMX for stem separations or using their new added training table as it is giving better results now? A GUI for it would be much appreciated.

Rog

**Comment by DilanBoskan** [comment]
Unfortunately, I do not have any more spare time to work on other projects.

**Comment by Mixerrog** [comment]
Dilan,

I understand but at least using their new larger training table in your program would likely give better results like open-unmix umx is now giving. The vocals separations with this new version is very good.

Rog

**Comment by DilanBoskan** [comment]
I am only responsible for the GUI

**Comment by aufr33** [comment]
> I understand but at least using their new larger training table in your program would likely give better results like open-unmix umx is now giving. The vocals separations with this new version is very good.

The open-unmix cannot be better than the tsurumeso's VR, because it uses several times less computing resources. In addition, VR has one very important advantage. It doesn't require large datasets, which makes it possible to create the Karokee model (it is trained on only 400 pairs).

**Comment by DilanBoskan** [comment]
I want to add just because any vocal seperator does not use as much resources as UVR does not make it automatically inferior, it could be more efficient!*

**Comment by Mixerrog** [comment]
Thanks for your responses & I am looking forward to your updated V5 version soon.

Rog
