### ISSUE TITLE
Manual Installation Error (MacOs)

### ISSUE THREAD

**Issue by alperz** [Anjok07/ultimatevocalremovergui#868]
I am on Monterey 12.7 with an AMD processor via opencore. I have downloaded Python 3.12 and run the pip3 install command from the repository folder. Python returned these errors.  I've tried the compiled .app version also. When I try to demux a wave file the application shuts down itself with no errors. What should I do?

Thank you.

> ultimatevocalremovergui-master % pip3 install -r requirements.txt

> Ignoring SoundFile: markers 'sys_platform != "darwin"' don't match your environment
> Collecting altgraph==0.17.3 (from -r requirements.txt (line 1))
>   Downloading altgraph-0.17.3-py2.py3-none-any.whl (21 kB)
> Collecting audioread==3.0.0 (from -r requirements.txt (line 2))
>   Downloading audioread-3.0.0.tar.gz (377 kB)
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 377.0/377.0 kB 928.4 kB/s eta 0:00:00
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [20 lines of output]
>       Traceback (most recent call last):
>         File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
>           main()
>         File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>                  ^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/8z/m370scds3p13g7gp3ft1hkxc0000gn/T/pip-build-env-l7635x5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "/private/var/folders/8z/m370scds3p13g7gp3ft1hkxc0000gn/T/pip-build-env-l7635x5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
>           self.run_setup()
>         File "/private/var/folders/8z/m370scds3p13g7gp3ft1hkxc0000gn/T/pip-build-env-l7635x5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 507, in run_setup
>           super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
>         File "/private/var/folders/8z/m370scds3p13g7gp3ft1hkxc0000gn/T/pip-build-env-l7635x5f/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 341, in run_setup
>           exec(code, locals())
>         File "<string>", line 17, in <module>
>       ModuleNotFoundError: No module named 'imp'
>       [end of output]
>   
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by sukualam** [comment]
try the latest dmg, it fix mdx and demucs for mps

**Comment by alperz** [comment]
> try the latest dmg, it fix mdx and demucs for mps

May I ask what do you mean by dmg? DMG of vocalremover app itself or python? Or vocalremover repository?
