### ISSUE TITLE
I can't install torch == 1.8.1 + cu111

### ISSUE THREAD

**Issue by lNoZl** [Anjok07/ultimatevocalremovergui#87]
**To Reproduce**
When I enter the command:
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html

**Screenshots**
![image](https://user-images.githubusercontent.com/85001648/125663355-c7fdd903-c620-4099-a52f-3a2e46eb60b2.png)
![image](https://user-images.githubusercontent.com/85001648/125663431-23104d0a-d426-45b4-9727-1630cf7b6f17.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**

**Comment by Voicizer** [comment]
You need to upgrade pip, ``python -m pip insall --upgrade pip``.
Read what is on your screenshot, you will realize that this is written on it

After installing the pip update, try the command again.

**Comment by samucacsm** [comment]
It worked for me when I installed it from the website. https://pytorch.org/. I downloaded the latest version available and it worked as it was supposed to.
