### ISSUE TITLE
MacOS 12.0.1 does not work

### ISSUE THREAD

**Issue by ManuManiac** [Anjok07/ultimatevocalremovergui#873]
Hey v5.6 of UVR doesn't start at all. I did all what's mentioned in the tab, where it will not open.
I'm on an MacOS 12.0.1 Monerey (M1)
I got only the message that the files may be damaged, and I can choose to delete it or to aboard it.

In the terminal window I got the following message:
[33374] Error loading Python lib '/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/Python': dlopen: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/Python, 0x000A): Symbol not found: _mkfifoat
  Referenced from: /Applications/Ultimate Vocal Remover.app/Contents/Frameworks/Python.framework/Versions/3.11/Python
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by sdflemming** [comment]
Same here. I just went back one version of UVR5 until the issue is resolved.

**Comment by elvencataccess1** [comment]
Same here. I'm not sure how to download a previous version.

**Comment by sdflemming** [comment]
https://github.com/Anjok07/ultimatevocalremovergui/releases/tag/v5.6

**Comment by sdflemming** [comment]
UVR 5.6 works for me. 

UVR_Patch_10_6_23_4_27 does not work and I get the file damaged alert.

**Comment by elvencataccess1** [comment]
I tried that and yet it didn't work. Still said it was broken.

**Comment by Anjok07** [comment]
@elvencataccess1 @sdflemming I just reuploaded the patch. Please try again - https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.6/Ultimate_Vocal_Remover_v5_6_MacOS_arm64.dmg

**Comment by Anjok07** [comment]
@elvencataccess1 @sdflemming @ManuManiac I just reuploaded the patch and fixed this issue. Please try again - https://github.com/Anjok07/ultimatevocalremovergui/releases/download/v5.6/Ultimate_Vocal_Remover_v5_6_MacOS_arm64.dmg

**Comment by sdflemming** [comment]
Your fix worked for me and is lightening fast - Thanks

--> Ultimate Vocal Remover v5.6.0 [2023-10-09 05:32:09]
--> MacBook Pro
--> Apple M1 Pro chip
--> Mac OS 13.5 (22G74)

**Comment by ManuManiac** [comment]
Yes it starts up now. 
Thank you very much for the fast fixing.
Problem solved.
