### ISSUE TITLE
@Anjok07 How to train own MDX-net model?

### ISSUE THREAD

**Issue by filispeen** [Anjok07/ultimatevocalremovergui#897]
@Anjok07 Can you say how to train own model? Please.

**Comment by ChrisTG742** [comment]
You could start with KUIELab MDX-Net for example. All sources and instructions how to train your own model can be found here:
https://github.com/kuielab/mdx-net
But I don't recommend to try to train a new model from the scratch. It takes hundreds or epochs (runs) until you get the first really satisfying results. Unless you have a really fast machine (or a cluster of dedicated GPUs) that won't be fun and a waste of energy IMHO.

**Comment by filispeen** [comment]
Thank you @ChrisTG742, for your help. But with server/cluster i dont have probems, my server/cluster copes with two A10 GPUs.
