### ISSUE TITLE
could not find version that satisfies...

### ISSUE THREAD

**Issue by tcafranz** [Anjok07/ultimatevocalremovergui#9]
this is the error i get when trying to download:

C:\WINDOWS\system32>pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.5.0+cpu (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.5.0+cpu

**Comment by Waffled-II** [comment]
it looks like the installation documentation is out of date for installing torch, as the version specified isn't available at that git anymore.
