### ISSUE TITLE
Mojave app wont launch

### ISSUE THREAD

**Issue by gatd** [Anjok07/ultimatevocalremovergui#901]
Last login: Sun Oct 15 15:24:26 on ttys001
/Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
Simons-Mac$ /Applications/Ultimate\ Vocal\ Remover.app/Contents/MacOS/UVR ; exit;
[2298] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ImportError: dlopen(/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_struct.cpython-311-darwin.so, 2): no suitable image found.  Did find:
	/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_struct.cpython-311-darwin.so: cannot load '_struct.cpython-311-darwin.so' (load command 0x80000034 is unknown)
	/Applications/Ultimate Vocal Remover.app/Contents/Frameworks/lib-dynload/_struct.cpython-311-darwin.so: cannot load '_struct.cpython-311-darwin.so' (load command 0x80000034 is unknown)
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

any help please

**Comment by Anjok07** [comment]
You must upgrade to Big Sur or higher. UVR will not function properly on Catalina and below.

**Comment by Anjok07** [comment]
@gatd You must upgrade to Big Sur or higher. UVR will not function properly on Catalina and below.
