### ISSUE TITLE
[INSTALLATION PROBLEM]

### ISSUE THREAD

**Issue by anarchocoderism** [Anjok07/ultimatevocalremovergui#91]
**To Reproduce**
I encountered the issue on step 4 while trying to paste the first command (pip install --no-cache-dir -r requirements.txt).
After pasting the first install command, it seems to install successfully, but a red error message pops up at the end. The second install command seemed to work fine. However, I was unable to run VocalRemover.py. 

**Screenshots**

Seemingly successful package install:
![image](https://user-images.githubusercontent.com/74470276/126878794-de7c721b-a04d-4ccd-9b52-cc7711758e0c.png)
Error text:
![image](https://user-images.githubusercontent.com/74470276/126878803-9285a523-85f8-4caa-bb6a-594145e0f49f.png)

What happens when I try to run VocalRemover.py:
![image](https://user-images.githubusercontent.com/74470276/126878865-ef4ce5dd-36c4-40d0-ba23-4cc84b94a588.png)

**Desktop (please complete the following information):**
OS: Windows 10

**Additional context**
I have Python 3.9 (64 bit) and ffmpeg installed.

**Comment by KimberleyJensen** [comment]
Its recommended to use Python 3.7 

You could also try

pip install opencv-python

**Comment by maxdrfr** [comment]
Linux Debian 11 (Bullseye) was released yesterday and it contains python 3.9 only. Are there any solutions?

**Comment by Plejek** [comment]
having the same problem atm

**Comment by Anjok07** [comment]
Please update to UVR v5.2.0.
