### ISSUE TITLE
v5.0.2 beta missing Ensemble 4Band Models (7 Models)?

### ISSUE THREAD

**Issue by JomSpoons** [Anjok07/ultimatevocalremovergui#92]
I just recently updated from 5.0.1 to 5.0.2 and the _Ensemble 4Band Models (7 Models)_ option appears to be missing from the _Drag-n-Drop-CHOOSE-YOUR-MODEL.bat_. I tried using the 5.0.1 batch file with 5.0.2 and got this error;
```
Ensemble All 4Band Models
loading MGM-v5-4Band-44100-BETA1... done
loading & stft of wave source... Traceback (most recent call last):
  File "4Band_ens_inference.py", line 1009, in <module>
    main()
  File "4Band_ens_inference.py", line 164, in main
    X_spec_s[d] = spec_utils.wave_to_spectrogram_mt(X_wave[d], bp['hl'], bp['n_fft'], mp.param['mid_side'], mp.param['reverse'])
AttributeError: module 'lib.spec_utils' has no attribute 'wave_to_spectrogram_mt'
```
I used the 4Band Ensemble the most out of all the presets in 5.0.1, will it be reimplemented or is it gone for good? And is there a way for me to readd the preset manually to the batch file? I'm not very good with this sort of stuff so apologies for my lack of knowledge. Any help is appreciated.

**Comment by aufr33** [comment]
The 4Band_ens_inference.py has been removed, please use the latest version of the Drag-n-Drop-CHOOSE-YOUR-MODEL.bat.
