### ISSUE TITLE
How to FULLY uninstall?

### ISSUE THREAD

**Issue by Versury** [Anjok07/ultimatevocalremovergui#93]
After install Python and the promp thing, i had problems with storage, and after uninstall Python using the program removal thing from Windows 10, I still had problems. I've cleaned a lot of cache and temp folders etc and got like 10GBs, cleaned every single folder on this HDD and i'm having problems, having only 11GB now (after cleaning for 2h). 

There's any way that I can delete any kind of temp folder or anything that is installed through the prompt thing? I remember using the prompt to install 3-4GB files there. 

Thanks.

**Comment by fran985** [comment]
Hey did you solve this problem? Because I am on kind of the same situation.

**Comment by Anjok07** [comment]
Go to "user/App/local/python" there may files there you need to delete if your trying to totally remove Python.
