### ISSUE TITLE
Windows keep crashing...

### ISSUE THREAD

**Issue by Voicizer** [Anjok07/ultimatevocalremovergui#97]
V5 Beta Issue for personal config!!

Hi, Is there any way to limit the use of ram/memory on windows 10 ?
because I physically have 8 GB, 5 GB are used by the system and the free 3 GB left are eaten by ```spec_utils.py``` without windows having time to prefetch. I created my own modelparam to isolate the mono side from a stereo track, I pre-split the stereo file into a ```L.wav``` and a ```R.wav``` file.
So when I do :
```python UVR\lib\spec_utils.py -a min_mag -m UVR\modelparams\my_own_model.json L.wav R.wav -o mono_file```
It should extract the mono center of the track.

What's in my modelparam ```my_own_model.json```?

```
{
	"bins": 4096,
	"unstable_bins": 0,
	"reduction_bins": 0,
	"band": {
		"1": {
			"sr": 44100,
			"hl": 512,
			"n_fft": 8192,
			"crop_start": 0,
			"crop_stop": 4096,
			"hpf_start": -1,
			"res_type": "sinc_best"
		}
	},
	"sr": 44100,
	"pre_filter_start": 4095,
	"pre_filter_stop": 4096
}
```

Why would I use this instead of the existing params ? It's because it needs more performance to isolate the mono side of a stereo track with a better quality, and it really needed that boost, but my windows won't stop crashing while using it. Any help to improve the quality of the separation without making the windows crashing ?
I don't know if this makes sense, but if you understand, some good help would be appreciated.😃

EDIT: It worked 1 time with small files.

**Comment by aufr33** [comment]
I do not recommend using such a large FFT size. This is overkill for high frequencies and will lead to waste of resources.

**Comment by Voicizer** [comment]
Yes i know, but is there any way to improve that ?

**Comment by aufr33** [comment]
Try:

 `"hl": 1024,`

or 

 `"hl": 2048,`

**Comment by Voicizer** [comment]
It worked, but the quality decreased

**Comment by Voicizer** [comment]
What ? Really ? Y'all not gonna help me ?

**Comment by aufr33** [comment]
Sorry, but I can't recommend anything yet.
