### ISSUE TITLE
Collecting torch==1.8.1+cu111 Exception:

### ISSUE THREAD

**Issue by lNoZl** [Anjok07/ultimatevocalremovergui#99]
**To Reproduce**
After I set the command:
pip install --no-cache-dir -r requirements.txt
pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
I get an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/85001648/129409846-666b894b-1af3-41be-9c70-4c28333aff5a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Voicizer** [comment]
You need to upgrade pip, ``python -m pip insall --upgrade pip``.
Read what is on your screenshot, you will realize that this is written on it

After installing the pip update, try the command again.

**Comment by lNoZl** [comment]
I was able to download everything thanks to what you wrote. But I still can't open the app
I get an ImportError: DLL load failed

![image](https://user-images.githubusercontent.com/85001648/129414353-9cd2bbb9-706a-4513-b68b-f9f3624997bd.png)

**Comment by Anjok07** [comment]
Please upgrade to version 5.2.
